### ISSUE TITLE
[Homework #] 直線等加速度

### ISSUE THREAD

**Issue by soniaasunn** [coding-coworking-club/basic-python-fall-2021#100]
## 程式碼

```
ip = [str(i) for i in input().split(",")]
new = []
for i in ip:
    if i != '':
        i = float(i)
        new.append(i)
    else:
        new.append(i)
print(new)

v = new[0]
a = new[1]
S = new[2]
t = new[3]
v0 = float(1.0)

if (v == '') and (t != ''):
    v = float(v0+float(a)*float(t))
    
if (S == '') and (a != '') and (t != '') :
    S = float(v0*float(t)+(1/2)*float(a)*(float(t)^2))

if (t == '') and (a != '') and (a != 0) and (v != ''):
    t == float((float(v)-v0)/float(a) )
elif (t == '') and (v != '') and (v != -1):
    t == float((2*float(S))/(float(v)+v0))
    
if (a == '') and (t !='') and (t != 0):
    a = float((float(v)-v0)/float(t))
elif (a == '') and (S != '') and (S != 0):
    a = float((float(v)^2-v0^2)/(2*float(S)))

print("v=",v," ,v0=",v0," ,a=",a," ,S=",S," ,t=",t)
```

## 錯誤訊息

<img width="359" alt="Screen Shot 2021-10-16 at 2 51 57 PM" src="https://user-images.githubusercontent.com/91780626/137577122-d7516bb1-c924-49c2-8c90-5c1404f38c76.png">

## 問題描述

Jupyter Notebook 執行無誤，但Judge 上為Runtime Error

**Comment by jasonchen1125** [comment]
嗨，關於你的程式碼我有看到幾個錯誤，列在底下：

1. 在計算的時候 t 應該只有一個等號， 兩個等號是 **條件判斷** 是才會用的，看你其他行都沒打錯我想你應該是不小心打成兩個了
2. 在Python的語法中，次方應該是 ** 而不是 ^，所以有用到次方的地方要改為 **
3. Print出來的格式應該是 **v=0.0, v0=1.0, a=-0.25, S=2.0, t=4.0**，但你的print變成 **v= 0.0  ,v0= 1.0  ,a= -0.25  ,S= 2.0  ,t= 4.0**，應該可以看得出來你的格式跟題目要求不太一樣，這部分可以想一下要怎麼達到題目要求格式

修正完上面這些問題就可以AC摟~

**Comment by soniaasunn** [comment]
> 嗨，關於你的程式碼我有看到幾個錯誤，列在底下：
> 
> 1. 在計算的時候 t 應該只有一個等號， 兩個等號是 **條件判斷** 是才會用的，看你其他行都沒打錯我想你應該是不小心打成兩個了
> 2. 在Python的語法中，次方應該是 ** 而不是 ^，所以有用到次方的地方要改為 **
> 3. Print出來的格式應該是 **v=0.0, v0=1.0, a=-0.25, S=2.0, t=4.0**，但你的print變成 **v= 0.0  ,v0= 1.0  ,a= -0.25  ,S= 2.0  ,t= 4.0**，應該可以看得出來你的格式跟題目要求不太一樣，這部分可以想一下要怎麼達到題目要求格式
> 
> 修正完上面這些問題就可以AC摟~

hi Jason! 謝謝你的回覆：）
我修改了程式
你說的1. 2. 點應該是沒有問題了
但是 根據3. 我改了如題的格式，但仍然是Wrong Answer，以下是我的程式碼: 
```
ip = [str(i) for i in input().split(",")]
new = []
for i in ip:
    if i != '':
        i = float(i)
        new.append(i)
    else:
        new.append(i)
print(new)

v = new[0]
a = new[1]
S = new[2]
t = new[3]
v0 = float(1.0)

if (v == '') and (t != ''):
    v = float(v0 + float(a)*float(t))
    
if (S == '') and (a != '') and (t != '') :
    S = float(v0*float(t) + (1/2)*float(a)*(float(t)**2))

if (t == '') and (a != '') and (a != 0) and (v != ''):
    t = float((float(v)-v0)/float(a))
elif (t == '') and (v != '') and (v != -1):
    t = float((2*float(S))/(float(v) + v0))
    
if (a == '') and (t !='') and (t != 0):
    a = float((float(v) - v0)/float(t))
elif (a == '') and (S != '') and (S != 0):
    a = float((float(v)**2-v0**2) / (2*float(S)))

print("v=",v,", v0=",v0,", a=",a,", S=",S,", t=",t, sep = "")
```

**Comment by soniaasunn** [comment]
> 嗨，關於你的程式碼我有看到幾個錯誤，列在底下：
> 
> 1. 在計算的時候 t 應該只有一個等號， 兩個等號是 **條件判斷** 是才會用的，看你其他行都沒打錯我想你應該是不小心打成兩個了
> 2. 在Python的語法中，次方應該是 ** 而不是 ^，所以有用到次方的地方要改為 **
> 3. Print出來的格式應該是 **v=0.0, v0=1.0, a=-0.25, S=2.0, t=4.0**，但你的print變成 **v= 0.0  ,v0= 1.0  ,a= -0.25  ,S= 2.0  ,t= 4.0**，應該可以看得出來你的格式跟題目要求不太一樣，這部分可以想一下要怎麼達到題目要求格式
> 
> 修正完上面這些問題就可以AC摟~

**Comment by jasonchen1125** [comment]
@soniaasunn 
抱歉我剛剛沒注意到，你的程式當中 `print(new)` 要拿到哦，不然 judge 系統會直接看這個print的結果而報錯~
拿掉應該就可以 AC 了！

**Comment by soniaasunn** [comment]
> @soniaasunn 抱歉我剛剛沒注意到，你的程式當中 `print(new)` 要拿到哦，不然 judge 系統會直接看這個print的結果而報錯~ 拿掉應該就可以 AC 了！

@jasonchen1125
對耶 沒錯 謝謝你！辛苦了：）
