### ISSUE TITLE
[Homework #] 色碼轉換

### ISSUE THREAD

**Issue by soniaasunn** [coding-coworking-club/basic-python-fall-2021#102]
## 程式碼

```#HW2-2
a = [float(i) for i in input().split(" ")]
new = []
for i in range(0,len(a)):
    if a[i] >= 255:
        a[i] = 255
        new.append(hex(a[i]))
    elif a[i] <= 0:
        a[i] = 0
        new.append(hex(a[i]))
    else:
        new.append(hex(int(a[i])))
new = "".join(new).replace("0x"," ").split(" ")
print(new)
    
hex_lst = []
for j in new[0:]:
    if len(j) == 1:
        j = "0"+ j
    hex_lst.append(j)
    hex_num = ''.join(hex_lst)
            
print("0x", hex_num, sep = '')

```

## 錯誤訊息

<img width="365" alt="Screen Shot 2021-10-16 at 3 50 33 PM" src="https://user-images.githubusercontent.com/91780626/137579116-1d7c3def-e20d-4032-9c45-b47037e55403.png">

## 問題描述

Jupyter 上執行無誤(Sample Input 1 & 2 都有跑出Sample Output 1 & 2)，但Judge 上為Wrong Answer

**Comment by jasonchen1125** [comment]
你檢查用的 `print(new)` 要拿掉哦，不然 judge 系統也會把那個 print 結果列入，就會報錯~
拿掉就可以AC了~

**Comment by soniaasunn** [comment]
> 你檢查用的 `print(new)` 要拿掉哦，不然 judge 系統也會把那個 print 結果列入，就會報錯~ 拿掉就可以AC了~

hi Jason,
我成功AC了
thank you so much!!! :)
