### ISSUE TITLE
[Homework 2] 直線等加速度

### ISSUE THREAD

**Issue by LiYiJie321** [coding-coworking-club/basic-python-fall-2021#106]
## 提交連結

https://judge.ccclub.io/status/3542a09bc37867b8f16bc06bc660551b
## 程式碼

```
cal = input().split(",")
v = cal[0]
a = cal[1]
S = cal[2]
t = cal[3]
if v == '':
    v = float(1 + float(a) * float(t))
elif a == '':
    if t != 0: 
        a = float(float(v) - 1 / float(t))
    else :
        a = float(float(v) ^ 2 - 1 / 2 * float(S))
elif S == '':
    S = float(1 * float(t) + 0.5 * float(a) * float(t) ^ 2)
elif t == '':
    if a != 0:
        t = float(float(v) - 1 / float(a))
    else:
        t = float(2 * float(S) / float(v) + 1)
v = float(v)
a = float(a)
S = float(S)
t = float(t)
ans = [f"v={v}, v0=1.0, a={a}, S={S}, t={t}"]
print(", ".join(ans))

```

## 問題描述

在 jupyter 測有成功，放到 judge 是WA，檢查不出哪裡有錯?

**Comment by jasonchen1125** [comment]
首先，你有考慮到分母為0的狀況，讚讚！
但是要注意你的 **資料型態** 是什麼，例如當你條件判斷式為` t != 0 `，但是你在input轉成list的時候，你的 `t = cal[3]` 是string，所以應該要寫為 `t != '0'` 才會符合你想判斷的，其他有判斷是不是0的部分也是如此，或是你在條件判斷前就先將資料型態轉換就可以用 `t != 0`。

第二個問題是 **Python中的次方的語法** 是 `**` 而不是 ^ 哦，所以有用到次方的地方都要改成 `**` 

第三個問題是要注意 **數學式的邏輯**，有些地方需要括號，例如 `float(v) - 1 / float(t)` 這樣是 v - (1/t)，但公式應該是 (v-1)/t，所以記得要加括號 `(float(v) - 1) / float(t)` ，其他有類似問題的地方都要檢查一下哦


以上三個問題修正就可以AC瞜~

**Comment by LiYiJie321** [comment]
成功了！太感謝您！回答的超用心！
