### ISSUE TITLE
[Week 2] ISBN檢查

### ISSUE THREAD

**Issue by ting8931** [coding-coworking-club/basic-python-fall-2021#11]
## 程式碼

a=input()

b=(int(a[0])+int(a[2])+int(a[4])+int(a[6])+int(a[8])+int(a[10]))+(int(a[1])+int(a[3])+int(a[5])+int(a[7])+int(a[9])+int(a[11]))*3

if 10-(b%10)<10:
    c=10-(b%10)
else:
    c=0

if (a[0:3]=='978') and ((a[3:6]=='986') or (a[3:6]=='957')):
    print(c==int(a[12]))

## 錯誤訊息

Judge：Wrong Answer

## 問題描述

我在Jupyter上測試都可以跑出True，不知道為什麼到Judge上面就顯示Wrong Answer
（公式中有Tab 但這裡顯示不出來）

**Comment by ting8931** [comment]
謝謝你，但我想問的是：
我在Jupyter上測試都可以跑出True，不知道為什麼到Judge上面就顯示Wrong Answer

**Comment by zhilinsu** [comment]
因為你的程式碼在第一組數字以及第二組數字檢查的時候，沒有 print 出相對應的結果；
當如果 input 的 ISBN 前六碼不對的時候，你的程式碼並不會 print 出 False，你可以試試看，例如：9739571394954。

也就是說，你目前的寫法，只有在正確的時候會 print 出 True，檢查碼錯誤的時候會 print 出 False，但其他情況時麼都不會 print 出來。
