### ISSUE TITLE
[General] 191201數字最小值排列

### ISSUE THREAD

**Issue by haowei-chen** [coding-coworking-club/basic-python-fall-2021#111]
## 提交連結
https://judge.ccclub.io/status/fe893600d6706b4163f07152974a0341

## 程式碼

```python
def sort(n1):   
    n1=sorted(n1);
    k=n1.count('0');
    if k==0:
        return n1
    else:
        nonzero=n1[k];
        del n1[k];
        return n1.insert(0, nonzero)

a=input();
s= sorted(sort(a));
print(int("".join(s)))
```

## 問題描述
我的想法是先把輸入的數字排列好，統計0有幾個後，把0之後的第一個string複製並移除，並在最前面加入
但是不知道為什麼都會return都會變成none，不知道insert 是哪裡用錯了。

**Comment by waukin** [comment]
因為 insert()方法的回傳值會是None
也就是說這一行 `n1.insert(0, nonzero)` 的值會是None

**Comment by haowei-chen** [comment]
> 因為 insert()方法的回傳值會是None
> 也就是說這一行 `n1.insert(0, nonzero)` 的值會是None

了解！
所以我是return list即可，已修正並且正確了，非常感謝您～
