### ISSUE TITLE
[Week 4] 打字機

### ISSUE THREAD

**Issue by hazel961126** [coding-coworking-club/basic-python-fall-2021#114]
## 提交連結

https://judge.ccclub.io/status/a997975cacda1f78f54b311d85c49997

## 程式碼

```
input_str = input()
answer = ''
last = ''

for i in range(len(input_str)):
    current = input_str[i]
    # 目前的字元是文字
    if current.isalpha():
        answer += current
        last = current
    # 目前的字元不是文字
    else:
        # 避免最後一個字元是沒東西的狀況
        if last != '':
            if current == '+':
                answer += last
            elif current == '-':
                # 遇到減號先確認 answer 內有東西可以扣掉
                if len(answer) != 0:
                    answer = answer[:-1]
            else:
                answer += answer
print(answer)

```

## 錯誤訊息

Wrong Answer

## 問題描述

每次抓取一個字元，變成 current，會優先檢查 current 「是文字 or 不是文字」
1. 是文字的話就先把 answer 加上該文字，然後那個文字變成 last（最後一個字元）
2. 不是文字的話，會判斷「加號、減號、乘法」。如果進到減號的迴圈，也會判斷 answer 內有東西可以扣掉

目前在試過各種「C++、C+-、C---、C+*-++」等等都可以跑出正確答案，但找不出哪個細節還有錯誤。

**Comment by r05521230** [comment]
再想想目前else的狀況，把else條件改成 elif current == '*': ，結果有些不同

**Comment by hazel961126** [comment]
> 再想想目前else的狀況，把else條件改成 elif current == '*': ，結果有些不同

感謝，目前更新了兩個處理但還是 Wrong Answer 🥲
1. 原本只寫 `if current.isalpha()`，加上 `if current.isdigit()`，確認只有字母跟數字會進來。
2. 把 else 條件改成 `elif current == '*'` 之後，`else 內輸入 pass`，避免遇到不是 +-* 這三種情況。

更新後 Submission: https://judge.ccclub.io/status/4572bc056598bea6621c0c988b726d5f

**Comment by r05521230** [comment]
目前大部分的測資都過了，差一點點。
不過因為程式還是有些時候會對，有些時候會錯，
可以試試看先不要用else的寫法(前面沒想抓到的狀況可能會有漏網之魚跑到else)，建議先只用if和elif，把四種狀況分別列出。
1. 輸入為+號，且當下輸出結果非空白
2. 輸入為-號，且當下輸出結果非空白
3. 輸入為*號，且當下輸出結果非空白
4. 輸入非上述的三種符號

並提供另一種判斷輸出結果是否存在的方式：
assign輸出結果為變數out，則可直接把out放置於if的判斷條件中，out存在時為True，會跑該條件下的程式。

**Comment by hazel961126** [comment]
謝謝！後來發現是我在 `elif current == '-':` 扣掉一個字元後，沒有重新判斷 last 是哪個字元
加入判斷條件後就可以了！
