### ISSUE TITLE
[Homework 2] 色碼轉換

### ISSUE THREAD

**Issue by hazel961126** [coding-coworking-club/basic-python-fall-2021#115]
## 程式碼

```
input_str = input()
input_str = [int(float(i)) for i in input_str.split()]
ans = '0x'

for num in input_str:
    # 轉換成十六進位並去掉開頭的 0x 後，判斷剩下的字元數量是不是剛好 2 個
    if len(hex(num)[2:]) != 1:
        ans += hex(num)[2:]
    else:
        # 判斷轉換成十六進位後是字母還是數字，字母前方補 0；數字後方補 0
        if hex(num)[2:].isalpha():
            ans += '0'
            ans += hex(num)[2:]
        else:
            ans += hex(num)[2:]
            ans += '0'
print(ans)
```

## 錯誤訊息

Wrong Answer

## 問題描述

1. 先把傳進來的文字轉換成 int 型態的 list
2. 每個數字轉換成十六進位並去掉開頭的 0x 後才串到 answer 後方
3. 如果轉換成十六進位後字母則前方補 0；是數字的話後方補 0

試過 Judge 上的「255 100 0」、「0.0 11.00 56.00000」，可以跑出正確答案，但不清楚中間有沒有邏輯錯誤。

**Comment by jasonchen1125** [comment]
目前我看到有兩個問題

1. 注意題目有說 **數值超過 255，以 255 計；如果數值小於 0，以 0 計** ，你目前的程式碼並未考慮到這點哦

2. 數字的話也是在**前方補 0** 哦，如果本來是 7 ，補個 0 變 07 等同 7 ，只是為了符合格式。若補在後面變 70，會跟原本就是 70 的相衝突。

修正後應該就可以AC摟~有問題可以再提出！

**Comment by hazel961126** [comment]
謝謝，兩個問題解決之後就有 AC 了！

> 目前我看到有兩個問題
> 
> 1. 注意題目有說 **數值超過 255，以 255 計；如果數值小於 0，以 0 計** ，你目前的程式碼並未考慮到這點哦
> 2. 數字的話也是在**前方補 0** 哦，如果本來是 7 ，補個 0 變 07 等同 7 ，只是為了符合格式。若補在後面變 70，會跟原本就是 70 的相衝突。
> 
> 修正後應該就可以AC摟~有問題可以再提出！
