### ISSUE TITLE
[Homework 2_01] 直線等加速度

### ISSUE THREAD

**Issue by david31009** [coding-coworking-club/basic-python-fall-2021#117]
## 提交連結
https://judge.ccclub.io/contest/76/problem/01

## 程式碼

```
lst = [float(i) if i != '' else '' for i in input().split(',')]

v = lst[0] 
a = lst[1] 
S = lst[2] 
t = lst[3]

if v == '':
    v = 1.0 + a*t    
elif a == '' or t == '' or (a == '' and t == ''):
    try:
        a = (v - 1.0) / t
        t = (v - 1.0) / a
    except:
        a = (v**2 - 1.0**2)/(2*S)
        t = (2*S)/(v + 1.0)
elif S == '':
    S = (1.0*t) + 0.5*a*(t**2)    
    
print(f'v={v}, v0=1.0, a={a}, S={S}, t={t}')

```

## 錯誤訊息
<img width="717" alt="error" src="https://user-images.githubusercontent.com/91410424/137629401-6ff70ced-c679-4ab6-a61f-7f90eadb267a.PNG">

## 問題描述
用jupyter測試OK，但丟進Judge顯示Runtime Error，有考慮加速度為0的狀況，但還是不過。

**Comment by jasonchen1125** [comment]
@david31009 

 `a == '' or t == ''` 的情況要分開寫，因為若 `t == ''` 且 `v == -1` ，在 try and except 的邏輯當中程式發現 `a = (v - 1.0) / t` 無法計算就會直接跳過 `t = (v - 1.0) / a` 到 except ，這時候雖然 a 可以計算，但 `t = (2*S)/(v + 1.0)` 卻因為 `v == -1` 無法計算而沒辦法得到 t ，因此我建議分成 `a == ''` 及 `t == ''` 兩種情況，並各寫一個 try and except ，如此就可以避免掉公式被跳過而該公式卻是唯一可以解出我們要的變數的狀況。

建議可以寫成：
```
elif a == '':
    try:
        a = (v - 1.0) / t

    except:
        a = (v**2 - 1.0**2)/(2*S)

elif t == '':     
    try:
        t = (v - 1.0) / a
    except:
        t = (2*S)/(v + 1.0)
```

**Comment by david31009** [comment]
我懂了，謝謝助教
