### ISSUE TITLE
[Homework 01] 直線等加速度

### ISSUE THREAD

**Issue by lily27404** [coding-coworking-club/basic-python-fall-2021#119]
## 提交連結
https://judge.ccclub.io/status/795649262fc7059e8b8a867582440629

## 程式碼

x=input().split(',')

v=x[0]
a=x[1]
s=x[2]
t=x[3]

if x[0]=="":
    v=1+float(x[1])*float(x[3])

elif x[1]=="":
    if float(x[3])!=0 and x[3]!="":
        a=(float(x[0])-1)/float(x[3])
    elif float(x[2])!="0" and x[2]!="":
        a=((float(x[0]))**2-1)/2*float(x[2])

elif x[2]=="":
     s=float(x[3])+float(x[2])*float(x[3])*float(x[3])/2
    
elif x[3]=="":
    if float(x[1])!=0 and x[1]!="":
        t=(float(x[0])-1)/float(x[1])
    elif float(x[0])!=-1 and x[0]!="":
        t=(2*float(x[2]))/(float(x[0])+1) 

v=float(v)
a=float(a)
s=float(s)
t=float(t)

print(f'v={v}, v0=1.0, a={a}, S={s}, t={t}')
```python

```

## 錯誤訊息

<img width="178" alt="runtine error" src="https://user-images.githubusercontent.com/92163022/137631122-94381784-3fde-4282-8fc5-11c85568c3b9.png">
## 問題描述

在jupyter上能跑出答案，但在judge上顯示runtime error
有去看了github上其他人runtime error的原因，也有將分母為0考量進去，但仍不清楚是在哪邊出了錯
不好意思謝謝助教

**Comment by jasonchen1125** [comment]
這裡再檢查一下有個地方錯掉了~算式裡面會有 `x[2]` 嗎?
修正完就可以AC了！

```
elif x[2]=="":
     s=float(x[3])+float(x[2])*float(x[3])*float(x[3])/2
```

**Comment by lily27404** [comment]
天啊真的太感謝助教了!!!!!!謝謝助教突破我的盲點!!
