### ISSUE TITLE
[General] 192102 圈圈叉叉

### ISSUE THREAD

**Issue by dennisc1213** [coding-coworking-club/basic-python-fall-2021#12]
## 程式碼

```
s = str.split(input())

s1 = []
for i in s:
    s1.append(int(i))

win = [[1,2,3], [4,5,6],[7,8,9],[1,4,7],[2,5,8],[3,6,9],[1,5,9],[3,5,7]]


if s1 in win:
    result = "T"
else:
	result = "F"
      
print(result)

```

## 問題描述

1. 請問判斷一直線，是否有更漂亮的寫法呢？
我現在是把所有判斷一直線的可能性寫出來到list win裡面，再去比對。
如果寫5 x 5的會瘋掉！ XD
2. 請問有辦法快速轉換list中所有物件的屬性嗎？ 
用str.split()產生的list 裡面的物件屬性是str, 但常常會用到的是int
我現在是用 for loop 去重新寫到另一個list去

**Comment by waukin** [comment]
1. 可以在思考一下一直線的規則，像是串列中數字的差值會相等，例如：[1, 2, 3], [3, 5, 7], ......
2. 可以使用List comprehension的寫法，之後會學到XD，`s = [int(i) for i in input().split()]` 這樣s就會是一個包含整數的串列了

**Comment by dennisc1213** [comment]
> 1. 可以在思考一下一直線的規則，像是串列中數字的差值會相等，例如：[1, 2, 3], [3, 5, 7], ......
> 
> 2. 可以使用List comprehension的寫法，之後會學到XD，`s = [int(i) for i in input().split()]` 這樣s就會是一個包含整數的串列了

感謝分享！
