### ISSUE TITLE
[Homework 2] 休息一下

### ISSUE THREAD

**Issue by KyleChou123** [coding-coworking-club/basic-python-fall-2021#125]
## 提交連結

https://judge.ccclub.io/status/ad74135b2376f97619b9b1c6967dbfd4

## 程式碼

```python
values = list(input().split()) #輸入值 存到list裡
values = [int(i) for i in values] #型態轉成int

init = values[0] #初始效率
highest = values[1] #最高效率
increase_speed = values[2] #效率提高的速度
fatigue_time = values[3] #進入疲倦的時間點
decrease_speed = values[4] #疲倦時 效率降低的速度

rest = 0 #休息的時間點
progresses = [0] * 10 #每個休息的時間點的效率總和
recent = init #目前的效率
fatigue = False #是否疲倦
progress = 0 # 效率總和

for j in range(1,11): #給不同休息的時間點的值 (j = 1~10)
    rest = j #休息的時間點j帶入rest
    
    for i in range(0,10): #根據休息時間點跑出效率總和 (i = 0~9)
        if i == fatigue_time:
            fatigue = True
        
        if fatigue == True: #如果疲倦了 遞減
            if i == rest:
                recent = init
            else:
                if recent - decrease_speed < 0:
                    if recent > 0:
                        progress = progress + recent / 2
                        recent = 0
                    else:
                        progress = progress
                else:
                    progress = progress + ((recent + recent - decrease_speed) / 2)
                    recent = recent - decrease_speed

        else: #如果還沒疲倦 遞增
            if i == rest:
                recent = init
            else:
                if recent + increase_speed > highest:
                    recent = highest
                    progress = progress + highest
                else:
                    progress = progress + ((recent + recent + increase_speed) / 2)
                    recent = recent + increase_speed 

                
    progresses[j-1] = progress #效率值總和丟到當前休息時間點的格子裡
    progress = 0 #初始化
    recent = init #初始化
    fatigue = False #初始化
    
a = max(progresses) #找出每個休息的時間點的效率總和中最大值
b = progresses.index(a) #找出其index
    
print(f"rt={b+1}, {a}")
```

## 錯誤訊息

Wrong Answer

## 問題描述

1. 目前的寫法測資都對，但是WA，不知道問題出在哪裡

**Comment by hchbiggrass** [comment]
請補上送程式碼的id連結，另外你的提問是後者，因為還沒疲倦所以效率會增加到疲倦為止。

**Comment by KyleChou123** [comment]
> 請補上送程式碼的id連結，另外你的提問是後者，因為還沒疲倦所以效率會增加到疲倦為止。

1. 已補上連結
2. 程式碼已經更新成後者 但還是WA 再麻煩助教看看 謝謝！

**Comment by hchbiggrass** [comment]
你的連結不對喔，連結是單一submit的，網址看起來像是 https://judge.ccclub.io/status/由數字和英文組成的亂碼 ，不過下次再改就好。
你觀察一下程式的輸出結果，在sample input 1:
休息時間=1的時候，總累積進度是380.0
休息時間=2的時候，總累積進度是340.0
休息時間=3的時候，總累積進度是325.0
休息時間=5的時候，總累積進度是425.0
休息時間=6的時候，總累積進度是512.5
休息時間=7的時候，總累積進度是575.0
休息時間=8的時候，總累積進度是600.0
休息時間=10的時候，總累積進度是575.0
試一下你應該就會發現問題出在哪裡了。另外你的註解寫得超好，程式架構視覺上也很乾淨，看得很舒服，請繼續保持。

**Comment by KyleChou123** [comment]
> 你的連結不對喔，連結是單一submit的，網址看起來像是 [https://judge.ccclub.io/status/由數字和英文組成的亂碼](https://judge.ccclub.io/status/%E7%94%B1%E6%95%B8%E5%AD%97%E5%92%8C%E8%8B%B1%E6%96%87%E7%B5%84%E6%88%90%E7%9A%84%E4%BA%82%E7%A2%BC) ，不過下次再改就好。 你觀察一下程式的輸出結果，在sample input 1: 休息時間=1的時候，總累積進度是380.0 休息時間=2的時候，總累積進度是340.0 休息時間=3的時候，總累積進度是325.0 休息時間=5的時候，總累積進度是425.0 休息時間=6的時候，總累積進度是512.5 休息時間=7的時候，總累積進度是575.0 休息時間=8的時候，總累積進度是600.0 休息時間=10的時候，總累積進度是575.0 試一下你應該就會發現問題出在哪裡了。另外你的註解寫得超好，程式架構視覺上也很乾淨，看得很舒服，請繼續保持。

謝謝助教 👍 
我有發現問題了 改過來之後和助教PO的輸出結果一樣 但還是WA QQ
已更新連結和程式碼

**Comment by hchbiggrass** [comment]
有一筆測資你試試看：30 100 30 6 15。
休息時間=1，總累積進度是640.0
休息時間=6，總累積進度是545.0
休息時間=7，總累積進度是637.5

**Comment by KyleChou123** [comment]
> 有一筆測資你試試看：30 100 30 6 15。 休息時間=1，總累積進度是640.0 休息時間=6，總累積進度是545.0 休息時間=7，總累積進度是637.5

非常感謝助教！ 終於AC了！
思考還是太不縝密 很多沒想清楚了地方 😵‍💫
