### ISSUE TITLE
[General] 8-1：乘積最大值

### ISSUE THREAD

**Issue by sihci47** [coding-coworking-club/basic-python-fall-2021#131]
## 提交連結

https://judge.ccclub.io/status/34ae8f0a70c20344f7981a7a0e4be328

## 程式碼

```python
def max_mul():
    for i in range(len(a)):
        if i<int(len(a))-1:
            a[i]=a[i]*a[i+1]
    return max(a)
a=[int(num) for num in input().split()]
print(max_mul(a))

```

## 問題描述
在juypter試過很多資料都可以~ 但judge 沒辦法過 : (
想知道是哪裡寫錯了
<!-- 請盡量完整地敘述你的問題。

**Comment by waukin** [comment]
因為 `max_mul` 這個函數中沒有定義輸入的參數
解決方法是可以在將定義函數的部分給定輸入參數 
將第一行修改成 `def max_mul(a)`

**Comment by sihci47** [comment]
好的 
我剛剛有試了結果變成wrong answer ㄌ
請問我還有什麼地方沒有考慮到嗎~
[https://judge.ccclub.io/status/4d33afbf44ac2821c4b03916138a8e10](url)

**Comment by waukin** [comment]
你有考慮到串列有0的情況嗎
例如說：2 0 1 會預期輸出0，但你的程式碼會輸出1

**Comment by sihci47** [comment]
喔對欸 
我成功寫出來了~
耶 謝謝助教!
