### ISSUE TITLE
[Homework 2] 色碼轉換

### ISSUE THREAD

**Issue by lily27404** [coding-coworking-club/basic-python-fall-2021#132]
## 程式碼
https://judge.ccclub.io/status/62913e6b7ee76148d7ea0941ff9f06cd

def carry(x):
    a1=x[0]//16
    a2=x[0]%16
    a3=x[1]//16
    a4=x[1]%16
    a5=x[2]//16
    a6=x[2]%16
    return [a1,a2,a3,a4,a5,a6]

lst=input().split()
lst=list(map(float,lst))
lst=[int(num) for num in lst]

ans=["0","x"]
for i in lst:
    if 0<i<=255:
        i=i
    elif i <=0:
        i=0
    else:
        i=255
ans+=carry(lst)
        
for index,value in enumerate(ans):
    if value == 10:
        ans[index] ="a"
    elif value == 11:
        ans[index] ="b"
    elif value == 12:
        ans[index] ="c"
    elif value == 13:
        ans[index] ="d"
    elif value == 14:
        ans[index] ="e"
    elif value == 15:
        ans[index] ="f"

ans = ''.join('%s' %id for id in ans)
print(ans)
```python

```

## 問題描述

在jupyter上兩個測資都有得出答案，但在judge上是WA，不太清楚是哪一個環節沒有考慮到

**Comment by jasonchen1125** [comment]
你的以下這段並沒有將原本的 lst 做轉換哦：

```
for i in lst:
    if 0<i<=255:
        i=i
    elif i <=0:
        i=0
    else:
        i=255
```

如果今天題目給定 300 300 300，經過下面這段你的 lst 依然是 300 300 300 而不是 255 255 255，自然放進 carry(lst) 裡面跑出來的16 進位就都不符合題目要求了~ 所以今天如果題目給定都在 0~255之間都還不會有問題，一超出就會出現問題了。

想一下該怎麼做才會換掉lst 裡面的數字，或是我提供一個想法是直接用一個新的 list，後續餵給 function 也可以直接用新的list。

修正完這個問題就可以AC瞜~

**Comment by lily27404** [comment]
原來如此!!真的非常謝謝助教詳細解說!
