### ISSUE TITLE
[Homework 2] 改考卷

### ISSUE THREAD

**Issue by antonykuo0824** [coding-coworking-club/basic-python-fall-2021#137]
## 提交連結

https://judge.ccclub.io/status/eb76eb2367795370c030be1db9f82f3f
## 程式碼

```python
corr_ans = input()
num = int(input())
corr_ans = ''.join(corr_ans.split(' ')) #是一個字串
rate = []
score = []
for i in range(len(corr_ans)):
    rate.append(0)
for i in range(num):
    student = input()
    student = student.split(' ')
    name = student[0]
    student_ans = ''.join(student[1:]) #是一個字串
    lis = []

    for j in range(len(corr_ans)):
        if corr_ans[j] == student_ans[j]:
            lis.append('Correct') #如果正確
            rate[j] += 1/num
    score.append(f'{name} {int(len(lis)/len(corr_ans)*100)}') 
    
for i in range(len(rate)):
    rate[i] = str(round(rate[i]*100,2))+'%'

for i in range(len(score)):
    print(score[i])
print(' '.join(rate))
```

## 錯誤訊息

Wrong Answer
## 問題描述

測資有過，一直WA

**Comment by julie-b05302301** [comment]
這樣寫的話，如果某題沒人回答正確，rate就會維持原本append進去的0，經過`str(round(rate[i]*100,2))+'%'`後會是0%，但應該是要有小數點的。

**Comment by antonykuo0824** [comment]
> 這樣寫的話，如果某題沒人回答正確，rate就會維持原本append進去的0，經過`str(round(rate[i]*100,2))+'%'`後會是0%，但應該是要有小數點的。

助教您好：
我依照您的建議加了這行
```python
for i in range(len(rate)):
    if rate[i] != 0:
        rate[i] = str(round(rate[i]*100,2))+'%'
    else:
        rate[i] = '0.0%'
```
但出來仍是WA
再麻煩助教給予建議了

**Comment by julie-b05302301** [comment]
在計算分數的部分，由於電腦對小數的計算是類似近似值的概念(電腦的數字表示法)，因此會有一些偏移，如果先算`len(lis)/len(corr_ans)`再乘以100，因為`len(lis)/len(corr_ans)`是小數，所以產生的偏移可能影響乘以100後取整數的結果，尤其int是向下取整數，會有小數點被捨去的狀況，因此不建議拿小數再去做計算。
以本題而言，我會建議先乘以100再除以len(corr_ans)，或者用扣分的方式避開小數~
關於電腦對小數的計算可參考：https://sites.google.com/site/nutncsie10412/ge-ren-jian-jie/fu-dian-shu-biao-shi-fa

**Comment by antonykuo0824** [comment]
謝謝助教！
問題已經解決了～
