### ISSUE TITLE
[Homework 2] 直線等加速度

### ISSUE THREAD

**Issue by sihci47** [coding-coworking-club/basic-python-fall-2021#144]
## 提交連結

https://judge.ccclub.io/status/f6267151e0697ca7079e94b5925b2bc8
## 程式碼

```python
n=input().split(",")    #(v,a,S,t)
for i in range(len(n)):
    if n[0]=="":    #解v
        n[0]=1+float(n[1])*float(n[3])
        
    elif n[1]=="":  #解a
        if float(n[2])!=0:     #若S不等於0
            n[1]=(float(n[0])**2-1)/float(n[2])*2
        elif float(n[3])!=0:   #若S等於0但t不等於0
            n[1]=(float(n[1]-1.0)/float(n[3])
                  
    elif n[2]=="": #解S
        n[2]=float(n[3])+(float(n[1]*(float(n[3]**2))))/2
              
    elif n[3]=="":
        if float(n[1])!=0:
            n[3]=(float(n[0])-1)/float(n[1])
        else:
            n[3]=float(n[2])*2/(float(n[0])+1.0)
              
print("v=",float(n[0]),sep="",end=", ")
print("v0=1.0",sep="",end=", ")
print("a=",float(n[1]),sep="",end=", ")
print("S=",float(n[2]),sep="",end=", ")
print("t=",float(n[3]),sep="")
```

## 錯誤訊息

![1634740251515](https://user-images.githubusercontent.com/92390494/138113162-0a0761aa-685b-4b06-82a7-470ee5f2cbd4.jpg)

## 問題描述

在judge 上也出現語法錯誤，在elif n[2]=="": 這邊，想問這樣打有哪裡錯呢? 
我有對齊上面也有打冒號，有什麼東西是我少打的嗎?
elif不是可以一次打很多個嗎?

**Comment by jasonchen1125** [comment]
`elif n[2]=="": `這部分沒有寫錯，主要原因是因為其他部分寫錯導致python判定錯誤
如果你發現運行時出現 `SyntaxError: invalid syntax` 通常是那一行打錯或**附近幾行**打錯

另外我還有發現一些問題與建議，列在下方：

1. 其實不需要寫迴圈，因為你直接用條件判斷式去判斷 n list 裡面的所有位子，其實並沒有用到迴圈。所以所有 if 與 elif 都可以拿掉迴圈靠左。

2. 造成 `SyntaxError: invalid syntax` 的主要原因，就是括號的問題。舉例來說： `(float(n[1]-1.0)` 這樣就會造成錯誤，因為n[1] 是 string ， 1.0 是 float，無法相加其結果也無法轉成 flloat ，這時候就會出錯。應該寫成 `(float(n[1])-1.0)` 才對。總共有三個地方有這樣的問題，你再仔細檢查一下！最後記得要檢查左右括號有沒有對到。

3. `(float(n[0])**2-1)/float(n[2])*2` 這個程式的邏輯變成是先除再乘 2，就會跟原本公式不一樣了，所以應該要把分母部分括號起來：`(float(n[0])**2-1)/(float(n[2])*2)` 。

4. `n[1]=(float(n[1])-1.0)/float(n[3])` 等號右邊不會出現 n[1]。

以上四個問題修正後就可以AC搂~有問題可以再提出

**Comment by sihci47** [comment]
有 ! 我寫出來了~~~
謝謝助教
