### ISSUE TITLE
[Homework 2] 直線加速

### ISSUE THREAD

**Issue by wenrueiTang** [coding-coworking-club/basic-python-fall-2021#146]
## 提交連結
https://judge.ccclub.io/contest/76/problem/01

## 程式碼
v,a,S,t = [i for i in input().split(',')]
v0 = 1.0
if v == '':
    v = v0 + float(a)*float(t)
elif a == '':
    a = (float(v) - v0) / float(t)
elif S == '':
    S = v0*float(t) + float(a)*float(t)*float(t)/2
else:
    t = (float(v)-v0) / float(a)
print(f'v={float(v)}, v0={float(v0)}, a={float(a)}, S={float(S)}, t={float(t)}')

```python

```

## 錯誤訊息
![image](https://user-images.githubusercontent.com/87130646/138194606-978cff4b-8efd-4fb4-aea4-4eb0674db377.png)

## 問題描述
持續顯示runtime error

**Comment by jasonchen1125** [comment]
題目給的數字可能造成某些公式 **分母是0** 的狀況而失效
可以思考看看該如何排除這樣的狀況
a 與 t 還有其他公式，也記得要使用到，可解決其他公式 **分母是0**  的狀況而失效後沒有其他公式算出題目要求數字的問題

提醒您
請注意發文程式碼 **縮排問題** 與 **提交正確連結**，且 **部分乘號** 不見了
發文格式與注意事項請詳閱 [GitHub使用須知](https://www.notion.so/ccclub/GitHub-Issue-5a270fb3e09448e1a6012082d10eb3dc)
有助於我們更快發現哪邊出錯哦~
