### ISSUE TITLE
[Homework 2] 色碼轉換

### ISSUE THREAD

**Issue by wenrueiTang** [coding-coworking-club/basic-python-fall-2021#147]
## 提交連結
https://judge.ccclub.io/contest/76/problem/02

## 程式碼
List = [int(float(i)) for i in input().split(' ')]
for j in range(0,3):
    if List[j] > 255:
        List[j] = '%02x' % 255
    elif j < 0:
        List[j] = '%02x' %  0
    else:
        List[j] = '%02x' % List[j]
a,b,c = [w for w in List]
print(f'0x{a}{b}{c}')
```python

```

## 錯誤訊息
![image](https://user-images.githubusercontent.com/87130646/138195695-d40c660b-3fcc-447f-8767-875acd105604.png)

## 問題描述
無法理解為什麼顯示wrong answer

**Comment by cys939** [comment]
嗨，當你數字為負數（-1 -2 -3）時，會出錯喔，檢查一下你的第五行XD
另外提醒，提問要注意「[GitHub Issue 使用教學](https://www.notion.so/ccclub/GitHub-Issue-5a270fb3e09448e1a6012082d10eb3dc)」，尤其程式碼的地方，才方便助教快速找錯喔：）
