### ISSUE TITLE
[Homework 2] 色碼轉換

### ISSUE THREAD

**Issue by sleeplessrainynight** [coding-coworking-club/basic-python-fall-2021#157]
## 提交連結

https://judge.ccclub.io/contest/76/problem/02

## 程式碼

```python
a = ["0x"]

start = [float(i) for i in input().split()]
num = [int(i) for i in start]

for j in num:
    if 0<j<255:
        j = str(hex(j)[2:])
        a.append(j)
        continue
    if j>255 or j==255:
        j = "ff"
        a.append(j)
        continue
    if j<0 or j == 0:
        j = "00"
        a.append(j)
        continue

b = [str(i) for i in a]
c = ''.join(b)

print(c)
```

## 錯誤訊息

<img width="246" alt="截圖 2021-10-22 上午12 24 24" src="https://user-images.githubusercontent.com/92941365/138318475-5566ad9f-3550-486e-be34-cb07011c1a54.png">

## 問題描述

助教好，這題在Jupyter 上有跑出Sample Output 1 & 2，但Judge 上為Wrong Answer
解題過程：
1.先把傳進來的文字轉換成 float 型態的 list，即start
2.再把start轉成整數型態的num 
3.設a是有0x的list，之後放入其他轉為16進位的值
4.將在num裡的值，根據題目轉換成16進位的值（去掉0x），放入ａ
5. 把a內的值，變成str形式，接在一起輸出

請問要如何調整呢，謝謝！

**Comment by cys939** [comment]
嗨！你少考慮一個因素「當轉換為 16 進位後，數值長度為 1，需要往前補 0」，這個情況不是只有 0 才會遇到，可以試試看「96 32 14」這組測資，也可以參考助教在臉書社團貼的[作業二 Hint](https://ccclub.notion.site/HW2-Hint-fd3da4a313544471be48855a7e4d76aa) 喔～～

**Comment by sleeplessrainynight** [comment]
哈囉助教，調整後AC了，感謝提醒！
