### ISSUE TITLE
[Homework 2] 改考卷

### ISSUE THREAD

**Issue by JessieTse** [coding-coworking-club/basic-python-fall-2021#158]
## 提交連結
https://judge.ccclub.io/status/cea675b9735897d455c944b15fbdae1d

## 程式碼

```right_answer = input() #輸入正確答案
right_answer = list(right_answer)
right_answer = [x for x in right_answer if x!= " "]
qnumber = len(right_answer) #每道題分數
acrate = [0] * qnumber #預備填正確率的串列
n = int(input()) #輸入學生人數
k = 1/n*100 #每個學生對每道題能貢獻的正確率
for i in range(n):
    stu_answer = input() #依次輸入每個同學的答卷
    result = []
    score = 0
    stu_answer = stu_answer.split()
    name = str(stu_answer[0])
    result.append(name) #切分名字
    answer = stu_answer[1:] #切分答案
    answer = "".join(answer)
    answer = list(answer)
    for i in range(len(answer)): #比對答案
        if str(answer[i]) == str(right_answer[i]):
            score += 100/qnumber #算分
            acrate[i] += k #算正確率
    result.append(str(int(score))) #分數累加
    result = " ".join(result)
    print(result) #印出分數
acrate = [str(round(x, 2)) + "%" for x in acrate] #正確率格式調整
acrate = " ".join(acrate)
print(acrate)



```

## 錯誤訊息
Wrong Answer

## 問題描述
在jupyter notebook測試，兩筆測資都正確，但在judge系統過不了。

**Comment by julie-b05302301** [comment]
首先你第一行想表達的應該是`right_answer = list(input())`？
如果某題沒人回答正確，acrate就會維持原本設定的0，經過`str(round(x, 2)) + "%" for x in acrate`後會是0%，但應該是要有小數點的。
可參考 [Issue#137](https://github.com/coding-coworking-club/basic-python-fall-2021/issues/137)

**Comment by JessieTse** [comment]
> 首先你第一行想表達的應該是`right_answer = list(input())`？ 如果某題沒人回答正確，acrate就會維持原本設定的0，經過`str(round(x, 2)) + "%" for x in acrate`後會是0%，但應該是要有小數點的。 可參考 [Issue#137](https://github.com/coding-coworking-club/basic-python-fall-2021/issues/137)

感謝回答！我試試看。第一行原本 right_answer = input() ，貼過來的時候不小心刪掉了..

**Comment by julie-b05302301** [comment]
如果問題已解決，記得close issue呦

**Comment by JessieTse** [comment]
> 如果問題已解決，記得close issue呦

剛剛解決了，感謝！用了扣分法
（抱歉提問之後一直沒時間重新測，我現在可以close issue了～
