### ISSUE TITLE
[Week 2] ISBN檢查

### ISSUE THREAD

**Issue by zxc346270** [coding-coworking-club/basic-python-fall-2021#16]
## 提交連結

https://judge.ccclub.io/status/8b6d6123e631ae1c939e805726148d68
## 程式碼

```python
a=input()
sum= int(a[0]) + int(a[1])*3 + int(a[2]) + int(a[3])*3 + int(a[4]) + int(a[5])*3 + int(a[6]) + int(a[7])*3 + int(a[8]) + int(a[9])*3 + int(a[10]) + int(a[11])*3
b="True"
c = sum%10
if a[0:3] != "978" : 
    b="False"
if a[3:6] != "986" and a[3:6] != "957" :
    b="False"
if (10 - c != a[-1]) and (c == 0 and a[-1] != 0):
    b="False"
print(b)

```

## 問題描述

在Jupyter上用sample的數字能顯示出正確的True
也認為把該有的情況都考慮進去了
想請問是哪裡有寫錯嗎

**Comment by hchbiggrass** [comment]
至少有兩個不對的地方，一個是檢查碼為0的情況，一個是布林值不用引號框起來

**Comment by dennisc1213** [comment]
> 至少有兩個不對的地方，一個是檢查碼為0的情況，一個是布林值不用引號框起來

檢查碼=0在最後一個if 裡面有喔！
助教說Judge上，True/False用String or Boolean 都可以～
所以這兩個地方應該沒關係才對

**Comment by dennisc1213** [comment]
最後一個if, 兩個條件的關係用"and"，好像永遠不可能成立齁～

**Comment by zxc346270** [comment]
> 最後一個if, 兩個條件的關係用"and"，好像永遠不可能成立齁～

我是想說 (最後一碼不等於檢查碼) 且 (檢查碼=0時最後一碼不等於0) 時才會是false
