### ISSUE TITLE
[Week 5] 數字組合最大值排序

### ISSUE THREAD

**Issue by secondbase56** [coding-coworking-club/basic-python-fall-2021#161]
## 提交連結

https://judge.ccclub.io/contest/64/problem/03
## 程式碼

```python
def f(x):
    b = [int(i) for i in x]
    c = []
    num = 0
    while num < len(x):
        num += 1
        c.append(max(b))
        b.remove(max(b))
    d = ""
    for j in c:
        d += str(j)
    return d

a = input().split(" ")
print(sorted(a, key=f))
```

## 問題描述

請教一下 昨天的練習數字組合這題 jupyter跑得出來但judge不行 請問是哪裡打錯了
![messageImage_1634889979151](https://user-images.githubusercontent.com/91279588/138417486-12a1a2ae-94bc-4c6d-a36f-1185f77f0acd.jpg)
![messageImage_1634889949477](https://user-images.githubusercontent.com/91279588/138417512-5076c445-a5ae-4de0-8bcd-a3ca74ea402a.jpg)

**Comment by happywillie** [comment]
你可以試試看以下測資：
19 218 1007

另外，建議可以改善程式碼的變數命名，增加程式碼的易讀性～（儘量不要用a b c）
