### ISSUE TITLE
[Homework 2] 改考卷

### ISSUE THREAD

**Issue by Ashleylee2159** [coding-coworking-club/basic-python-fall-2021#163]
## 程式碼

cor = input().split(" ")
cor = ''.join(cor)
length = len(cor)

n = int(input())

correct_lst = [0]*length
ans_lst = []

for i in range(n):
    score = 0
    st = input().split(" ")
    name = st[0]
    st.pop(0)
    st = ''.join(st)
    ans_lst.append(name)
    
    for j in range(len(st)):
        if st[j] == cor[j]:
            score += 1
            correct_lst[j] += 1
    ans_lst.append(int(score*(100/length)))

          
          
for i in range(0,len(ans_lst),2):
    print(ans_lst[i],ans_lst[i+1])
    

for i in range(length):
    rate = str(round(correct_lst[i]/n,4)*100)
    print(rate+"%",end = " ")
                   
                   
    
                   
                   
    
```python

```

## 錯誤訊息

![1634906159801](https://user-images.githubusercontent.com/91714712/138454669-7bfa433e-0aa0-4a0c-a2c7-6f90a5ad4124.jpg)

## 問題描述

測資正確但wrong answer，正確率0會print 0.0%、非零時也會印到小數點後二位。
複製程式碼時看得到縮排(錯誤訊息附圖)，preview時會跑位

**Comment by julie-b05302301** [comment]
請修正［程式碼提交格式並附上提交連結］，細節請參考[github 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)
你中間那段(如下)的格式是正確的，其他部分不正確所以會影響縮排。
```
for j in range(len(st)):
    if st[j] == cor[j]:
        score += 1
        correct_lst[j] += 1
ans_lst.append(int(score*(100/length)))
```
