### ISSUE TITLE
[General] 8-1 乘積最大值 

### ISSUE THREAD

**Issue by chiehlinjo** [coding-coworking-club/basic-python-fall-2021#165]
## 提交連結
https://judge.ccclub.io/status/1ee43d4b20ae167fda4558d1538934bd

## 程式碼

```python
def max_mul(num):
    cross_order=[ _ for _ in range(len(num))]
    if 0 in num:
        return 0
    else:
        for i in range(len(num)):
            cross_order[i]=num[i]*num[i-1]
            max_value = max(cross_order)
        return (max(cross_order))
s=[int(_) for _ in input().split()]
print(max_mul(s))
```

## 錯誤訊息
wrong answer

## 問題描述
JUPYTER 上都有跑出來，但在批改系統上不能通過，想麻煩助教幫忙看看是否有我沒看見的盲點，謝謝。

**Comment by waukin** [comment]
你的運算邏輯是s這個串列中只要有0
透過 `max_mul` 函式的運算就會回傳0
這邊的邏輯有點怪怪的
因為題目敘述是要求「連續兩個相鄰乘積」的最大值
例如：[2, 0, 1, 2] 預期會得到2，但你的程式碼會輸出0

**Comment by chiehlinjo** [comment]
了解! 謝謝助教!!! 這點改完果然就通過了><
