### ISSUE TITLE
[Homework 2] 直線等加速度

### ISSUE THREAD

**Issue by Bagu917** [coding-coworking-club/basic-python-fall-2021#167]
## 提交連結

https://judge.ccclub.io/contest/76/problem/01

## 程式碼

```python
#直線等加速度

#切開input
n=input().split(",") 
#分別定義五個參數
v=n[0]
v0=float(1)
a=n[1]
s=n[2]
t=n[3]


#討論各種空缺的情況
if v=="" and s=="":
    v=v=v0+float(a)*float(t)
    s=v0*float(t)+0.5*float(a)*(float(t)**2)
elif t=="" and a=="":
    t=s*float(s)/(float(v)+v0)
    a=((float(v)**2)-v0**2)/(2*float(s))
elif v=="":
    v=v0+float(a)*float(t)
elif s=="":
    s=v0*float(t)+0.5*float(a)*(float(t)**2)
elif t=="" and float(a)!=0 and v!="":
    t=(float(v)-v0)/float(a)
elif t=="" and v!="" and s!="" and (float(v)+v0)!=0:
    t=s*float(s)/(float(v)+v0)
elif a=="" and v!="" and float(t)!=0:
    a=(float(v)-v0)/float(t)
elif a=="" and s!="" and v!="" and float(s)!=0:
    a=((float(v)**2)-v0**2)/(2*float(s))

print("v="+str(float(v))+", v0=1.0, a="+str(float(a))+", S="+str(float(s))+", t="+str(float(t)))

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/92529929/138475127-5aed1cc5-a5ea-4643-b126-7e8be7a2f78d.png)

## 問題描述

是不是有可能同時缺少不只一個參數?但若要能解出每個參數，缺少不只一個參數的情況應該只有兩種
1)同時缺少v、S
2)同時缺少t、a
所以針對輸入應該只有6種情況
1)同時缺少v、S
2)同時缺少t、a
3)缺少v
4)缺少a
5)缺少S
6)缺少t
不確定是不是還有沒考慮到的情況導致runtime error

**Comment by jasonchen1125** [comment]
嗨，看過你的程式碼後有看到幾個問題，我列在下面：

1.有個條件判斷式沒有排除分母為0的情況，我有看到後面幾個有，但 `elif t=="" and a=="":` 這個漏掉了
2. t的公式 `t=s*float(s)/(float(v)+v0)` 應該是 `t=2*float(s)/(float(v)+v0)`，有兩個地方有這個錯誤，再仔細檢查一下

修正完就可以AC摟
