### ISSUE TITLE
[Week 5] 數字組合最大值排序

### ISSUE THREAD

**Issue by cynnancy** [coding-coworking-club/basic-python-fall-2021#168]
## 提交連結
https://judge.ccclub.io/status/b6a055ba9d8e6b24630297dfbaf14bc2

## 程式碼

```python

n = input().split()   
def rule(num): #定義分配函數
    num_list = [ ] #建立空串列放重新排列的數字
    for i in range(len(num)):
        num_list.append(''.join(sorted(list(num[i]), reverse = True))) #把輸入值的每個數字排列成最大值
        num_list.sort(reverse = True) #將排成最大值的數字們照大小排好
    return list (num_list) 
print(sorted (n, key = rule))

```

## 問題描述

在jupyter notebook上輸入測資都正確，
利用trace也都是跟者我的邏輯走，
輸出的答案也都是正確的，
但在judge系統輸入則會出現WA。

**Comment by happywillie** [comment]
跟 #153 的問題有點像，可以思考函式究竟回傳了什麼型態的資料，不同的資料型態比較方式也略有不同。
也可以試試看測資：19 218 1007
正確來說應該輸出：['19', '218', '1007']

**Comment by cynnancy** [comment]
瞭解！謝謝助教～～
也成功AC了！
