### ISSUE TITLE
[Homework 1] 直角三角形

### ISSUE THREAD

**Issue by aq200aq** [coding-coworking-club/basic-python-fall-2021#17]
## 提交連結

https://judge.ccclub.io/status/8c8887f53680f4751f97698a0131121d

## 程式碼

c = str(input())
i = str(input())
j = i.split(' ')
y = int(j[0])
z = int(j[1])
M = 'False'

if int(c) > y and int(c) > z:
    for a in range(y, z+1):
        for b in range(y, z+1):
            if int(c)**2 == int(a)**2 + int(b)**2:
                M = 'True'
    print(M)
elif int(c) < z or int(c) > z:
    M = 'False'
    print(M)
else:
    M = 'False'
    print(M)

```python

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/25953994/135719681-66be80ac-21b6-48b6-8df7-34dd4f2804e9.png)

## 問題描述

我的想法是：
定義第一串輸入為 c
定義第二串輸入為 i
將 i 以空格分，變為串列 j
定義串列 j 的 index 0 為 y
定義串列 j 的 index 1 為 z
定義 M 為字串 False

先判定第三邊 c 是否為最長邊：
若否，則定義 M 為 False 並 print M；
若是，則執行以下迴圈：
定義 a 與 b 在 y~z 間對照，若直角三角形公式成立，則定義 M 為 True 並 print M

請問是否是邏輯上有缺失？或是程式碼的錯誤呢？
再麻煩解答了，感謝

**Comment by dennisc1213** [comment]
Input
13
12 5

跑的結果應該會怪怪的唷

**Comment by lazyYC** [comment]
@aq200aq 你好，以下幾個小建議：

```
c = str(input())
i = str(input())
```
input() 本身預設就是以字串儲存的，所以不需要經過 str() 轉換

```
j = i.split(' ')
y = int(j[0])
z = int(j[1])
M = 'False'
```
這種不是很複雜的情況可以寫在同一行，不然變數會很亂
另外變數也可以這樣設（但不一定要這樣寫啦）：
a, b = 2, 3

```
if int(c) > y and int(c) > z:
```
題目有提到 c 是長邊，所以不需要特別判斷是否 c > y & z
另外不確定是不是你貼 code 過來格式跑掉
因為你的所有 code 都沒有縮排

```
for a in range(y, z+1):
for b in range(y, z+1):
if int(c)**2 == int(a)**2 + int(b)**2:
M = 'True'
print(M)
elif int(c) < z or int(c) > z:
M = 'False'
print(M)
else:
M = 'False'
print(M)
```
1. 同樣是縮排問題，另外感覺整段的邏輯架構都怪怪的XD 
2. 還有 y & z 不一定誰大誰小，可以想一下怎麼解決
3. 一開始assign c 的時候就用 int() 的話，就不需要每次都 int(c) ，同樣的 a, b 已經不需要

**Comment by lazyYC** [comment]
突然發現我講錯，想更正一下
我前面講到**不需要特別判斷是否 c > y & z** 是錯的，題目給的 y & z 範圍有可能超過 c
