### ISSUE TITLE
[Homework 04] 省錢小作戰

### ISSUE THREAD

**Issue by lily27404** [coding-coworking-club/basic-python-fall-2021#175]
## 提交連結

https://judge.ccclub.io/status/ae56ea096cb0344b2cde258216fdd0ee

## 程式碼

```python

```
def best_discount(lst):       #定義函式，預設輸入一個len=5的串列，其中index=4的地方放的是串列             
    money = []                #設一空串列，將放入最後價格
    for i in range(len(lst[4])):     
        s = lst[4][i]
        price_rule = int(s[(s.index("滿")+1):s.index("打")])   #滿多少錢
        discount = (s[(s.index("打")+1):s.index("折")])        #打幾折
        if len(discount) == 1:                              #打折的數字確保為兩位數
            discount = discount + "0"
            discount = int(discount)                      
        else:
            discount = int(discount)
        price_original = int(lst[1])         #原價
        rebate = float((lst[2])[:(lst[2]).index("%")])              #回饋金
        
        if "運費" in lst[3]:
            fare = float(lst[3][((lst[3]).index("費")+1):])               #有運費
        else:   #免運
            fare = 0
        
        if price_original >= price_rule:     #有符合條件的話
            money.append(((price_original*discount/100)+ fare)*(100 - rebate)/100)
        else:
            money.append((price_original+ fare)*(100 - rebate)/100)
    return min(money)              #找到折扣方案最好的

shop_lst = []
for j in range(4):
    x = input().split()
    shop_lst.append(x)     #四個商店的優惠

price_lst = []                          #之後放入四個商店的最小金額
store = ["S","C","P","M"]               #商店名稱

for k in range(len(shop_lst)):
    if shop_lst[k] == ["0"]:             #若無存貨
        store.remove(store[k])           #同步將商店刪掉
        
    elif shop_lst[k][1] == "0":          #若價錢為零
        price_lst.append(0)
        
    else:                                #有存貨且價錢不為零
        if "%" in shop_lst[k][2]:                 #有回饋金
            if len(shop_lst[k]) == 5:                       #有折扣優惠
                shop_lst[k].insert(4,shop_lst[k][4].split())
                price_lst.append(best_discount(shop_lst[k]))
            else:
                shop_lst[k].append(["滿0打100折"])         #無折扣優惠
                price_lst.append(best_discount(shop_lst[k]))
        elif "運" in shop_lst[k][2]:      #無回饋金
            shop_lst[k].insert(2,"0%")
            if len(shop_lst[k]) == 5:                       #有折扣優惠
                shop_lst[k].insert(4,shop_lst[k][4].split())
                price_lst.append(best_discount(shop_lst[k]))
            else:
                shop_lst[k].append(["滿0打100折"])         #無折扣優惠
                price_lst.append(best_discount(shop_lst[k]))

ans = min(price_lst)     #最低價格
ind = price_lst.index(ans)
ans = round(ans)
print(store[ind] + "商店" + " " + str(ans))

## 錯誤訊息

<img width="178" alt="runtine error" src="https://user-images.githubusercontent.com/92163022/138562532-4b7f7b6c-1448-4a6f-860c-be1ab13e900b.png">

## 問題描述

在jupyter上兩個測資都有成功，但在judge上是rountime error
有試了其他不同的數字進去，但也都有通過，也有考量貨量和價格為零的狀況，
但還是找不出來是哪裡有問題

**Comment by lova999** [comment]
你在移除不要的商店時
store的index一直在改變歐
像是原先
[S,C,P,M] -> 0,1,2,3
但你移除C之後
[S,P,M] -> 0,1,2
P 就從index 2 變成 1了
但你的k還是一直在走

**Comment by lily27404** [comment]
了解，謝謝助教
我現在把　無存貨的狀況　設為加上＂ｎｏｎｅ＂，再在最後排除掉，不過在ｊｕｄｇｅ上是ＷＡ
想請問這樣是哪裡又沒考量到呢？

def best_discount(lst):       #定義函式，預設輸入一個len=5的串列，其中index=4的地方放的是串列             
    money = []                #設一空串列，將放入最後價格
    for i in range(len(lst[4])):     
        s = lst[4][i]
        price_rule=int(s[(s.index("滿")+1):s.index("打")])   #滿多少錢
        discount=(s[(s.index("打")+1):s.index("折")])        #打幾折
        if len(discount) == 1:                              #打折的數字確保為兩位數
            discount = discount + "0"
            discount = int(discount)                      
        else:
            discount = int(discount)
        price_original =int(lst[1])         #原價
        rebate = float((lst[2])[:(lst[2]).index("%")])              #回饋金
        
        if "運費" in lst[3]:
            fare = float(lst[3][((lst[3]).index("費")+1):])               #有運費
        else:   #免運
            fare=0
        
        if price_original >=price_rule:     #有符合條件的話
            money.append(((price_original*discount/100)+ fare)*(100 - rebate)/100)
        else:
            money.append((price_original+ fare)*(100 - rebate)/100)
    return min(money)              #找到折扣方案最好的

shop_lst = []
for j in range(4):
    x = input().split()
    shop_lst.append(x)     #四個商店的優惠

price_lst = []                          #之後放入四個商店的最小金額
store = ["S","C","P","M"]               #商店名稱

for k in range(len(shop_lst)):
    if shop_lst[k] == ["0"]:             #若無存貨
        price_lst.append("none")
        
    elif shop_lst[k][1] == "0":          #若價錢為零
        price_lst.append(0)
        
    else:                                #有存貨且價錢不為零
        if "%" in shop_lst[k][2]:                 #有回饋金
            if len(shop_lst[k]) == 5:                       #有折扣優惠
                shop_lst[k].insert(4,shop_lst[k][4].split())
                price_lst.append(best_discount(shop_lst[k]))
            else:
                shop_lst[k].append(["滿0打100折"])         #無折扣優惠
                price_lst.append(best_discount(shop_lst[k]))
        elif "運" in shop_lst[k][2]:      #無回饋金
            shop_lst[k].insert(2,"0%")
            if len(shop_lst[k]) == 5:                       #有折扣優惠
                shop_lst[k].insert(4,shop_lst[k][4].split())
                price_lst.append(best_discount(shop_lst[k]))
            else:
                shop_lst[k].append(["滿0打100折"])         #無折扣優惠
                price_lst.append(best_discount(shop_lst[k]))


while "none" in price_lst:             #把無存貨去掉
    index_1 = price_lst.index("none")
    price_lst.remove("none")
    del store[index_1]
    
ans = min(price_lst)     #最低價格
ind = price_lst.index(ans)
ans = round(ans)
print(store[ind]+"商店"+" "+str(ans))
