### ISSUE TITLE
[Homework 2] 省錢小作戰

### ISSUE THREAD

**Issue by chiehrulin** [coding-coworking-club/basic-python-fall-2021#176]
## 提交連結
https://judge.ccclub.io/status/97bc66a473c9158d71daa20d70ed2333

## 程式碼

```python
******(將考慮售價為0的code貼在這，因留言區的格式會跑掉)

s = input()
c = input()
p = input()
m = input() 

s = s.replace(","," ")
c = c.replace(","," ")
p = p.replace(","," ")
m = m.replace(","," ")
slst = [i for i in s.split(" ")]
clst = [i for i in c.split(" ")]
plst = [i for i in p.split(" ")]
mlst = [i for i in m.split(" ")]


if slst[0] == "0" :
    slst = ["0","-1","0","0"]
elif "%" not in slst[2]:
    slst.insert(2,"0")
if clst[0] == "0" :
    clst = ["0","-1","0","0"]
elif "%" not in clst[2]:
    clst.insert(2,"0")
if plst[0] == "0" :
    plst = ["0","-1","0","0"]
elif "%" not in plst[2]:
    plst.insert(2,"0")
if mlst[0] == "0" :
    mlst = ["0","-1","0","0"]
elif "%" not in mlst[2]:
    mlst.insert(2,"0")


def savemoney (x):
    if x[0] == "0" :
        return 10000000
    else:
        for j in range (len(x)):
            if x[j] == "免運" :
                x[j] = 0
            elif "運費" in x[j] :
                fe = x[j].find("費")
                x[j] = x[j][fe+1:]
                x[j] = int(x[j])
            elif "滿" in x[j] :
                da = x[j].find("打")
                zhe = x[j].find("折")
                x[j] = x[j][1:da] + "," + x[j][da+1:zhe]
            elif "%" in x[j] :
                percent = x[j].find("%")
                x[j] = x[j][:percent]
                x[j] = float(x[j])
                x[j] = x[j] * 0.01
            else:
                x[j] = int(x[j])
        max = 0 
        if len(x) == 4:
            condition = round((x[1]*(1-x[2]) + x[3]) )
            if condition > max :
                max = condition 
        elif len(x) == 5:
            count1 = x[4].find(",")
            man = int(x[4][:count1])
            discount = int(x[4][count1+1:])
            if x[1] >= man:
                condition =  round((x[1] * discount/100 + x[3]) * (1-x[2]))
                if condition > max :
                    max = condition 
            else:
                condition = round(x[1]*(1-x[2]) + x[3])
                if condition > max :
                    max = condition 
        elif len(x) == 6:
            count2 = x[4].find(",")
            man1 = int(x[4][:count2])
            discount1 = int(x[4][count2+1:])
            count3 = x[5].find(",")
            man2 = int(x[5][:count3])
            discount2 = int(x[5][count3+1:])
            if man1 > man2 and x[1] >= man1 :
                condition = round((x[1] * discount1/100 + x[3]) * (1-x[2]))
                if condition > max :
                    max = condition 
            elif man2 > man1 and x[1] >= man2 :
                condition = round((x[1] * discount2/100 + x[3]) * (1-x[2]))
                if condition > max :
                    max = condition 
            else:
                condition = round(x[1]*(1-x[2]) + x[3])
                if condition > max :
                    max = condition 
        elif len(x) == 7:
            count4 = x[4].find(",")
            man3 = int(x[4][:count4])
            discount3 = int(x[4][count4+1:])
            count5 = x[5].find(",")
            man4 = int(x[5][:count5])
            discount4 = int(x[5][count5+1:])
            count6 = x[6].find(",")
            man5 = int(x[6][:count6])
            discount5 = int(x[6][count6+1:])
            if man3 > man4 and man3 > man5 and x[1] >= man3 :
                condition = round((x[1] * discount3/100 + x[3]) * (1-x[2]))
                if condition > max :
                    max = condition 
            elif man4 > man5 and man4 > man3 and x[1] >= man4 :
                condition = round((x[1] * discount4/100 + x[3]) * (1-x[2]))
                if condition > max :
                    max = condition 
            elif man5 > man3 and man5 > man4 and x[1] >= man5:
                condition = round((x[1] * discount5/100 + x[3]) * (1-x[2]))
                if condition > max :
                    max = condition 
            else:
                condition = round(x[1]*(1-x[2]) + x[3])
                if condition > max :
                    max = condition 
            return condition 



lst = []
lst.append(savemoney(slst))
lst.append(savemoney(clst))
lst.append(savemoney(plst))
lst.append(savemoney(mlst))

print(lst)

if min(lst) == lst[0]:
    print("S商店",lst[0],sep=" ")
elif min(lst) == lst[1]:
    print("C商店",lst[1],sep=" ")
elif min(lst) == lst[2]:
    print("P商店",lst[2],sep=" ")
elif min(lst) == lst[3]:
    print("M商店",lst[3],sep=" ")

        

#########################(原本的)################################################################
s = input()
c = input()
p = input()
m = input() 

s = s.replace(","," ")           #把多個折扣方案都拆出來
c = c.replace(","," ")
p = p.replace(","," ")
m = m.replace(","," ")
slst = [i for i in s.split(" ")]
clst = [i for i in c.split(" ")]
plst = [i for i in p.split(" ")]
mlst = [i for i in m.split(" ")]


if slst[0] == "0" :          #如果貨量是0，先把每個都設成0，後面好做處理
    slst = ["0","0","0","0"]
elif "%" not in slst[2]:     #如果沒有信用卡回饋金也補上0
    slst.insert(2,"0")
if clst[0] == "0" :
    clst = ["0","0","0","0"]
elif "%" not in clst[2]:
    clst.insert(2,"0")
if plst[0] == "0" :
    plst = ["0","0","0","0"]
elif "%" not in plst[2]:
    plst.insert(2,"0")
if mlst[0] == "0" :
    mlst = ["0","0","0","0"]
elif "%" not in mlst[2]:
    mlst.insert(2,"0")


def savemoney (x):    #先處理list裡面的內容，處理掉中文字跟%符號
    for j in range (len(x)):
        if x[j] == "免運" : 
            x[j] = 0
        elif "運費" in x[j] :
            fe = x[j].find("費")
            x[j] = x[j][fe+1:]
            x[j] = int(x[j])
        elif "滿" in x[j] :
            da = x[j].find("打")
            zhe = x[j].find("折")
            x[j] = x[j][1:da] + "," + x[j][da+1:zhe]
        elif "%" in x[j] :
            percent = x[j].find("%")
            x[j] = x[j][:percent]
            x[j] = float(x[j])
            x[j] = x[j] * 0.01
        else:
            x[j] = int(x[j])

    if len(x) == 4:    #開始計算折扣的部分，用list裡面的長度去判斷，長度為 4~7(先前處理貨量跟信用卡回饋金=0的原因)
        condition = round((x[1]*(1-x[2]) + x[3]) )
    elif len(x) == 5:  #如果貨量達到滿(變數man)xxx的標準，就用xxx後面的折數去算
        count1 = x[4].find(",")
        man = int(x[4][:count1])
        discount = int(x[4][count1+1:])
        if x[1] >= man:
            condition =  round((x[1] * discount/100 + x[3]) * (1-x[2]))
        else:
            condition = round(x[1]*(1-x[2]) + x[3])
    elif len(x) == 6:
        count2 = x[4].find(",")
        man1 = int(x[4][:count2])
        discount1 = int(x[4][count2+1:])
        count3 = x[5].find(",")
        man2 = int(x[5][:count3])
        discount2 = int(x[5][count3+1:])
        if man1 > man2 and x[1] >= man1 :
            condition = round((x[1] * discount1/100 + x[3]) * (1-x[2]))
        elif man2 > man1 and x[1] >= man2 :
            condition = round((x[1] * discount2/100 + x[3]) * (1-x[2]))
        else:
            condition = round(x[1]*(1-x[2]) + x[3])
    elif len(x) == 7:
        count4 = x[4].find(",")
        man3 = int(x[4][:count4])
        discount3 = int(x[4][count4+1:])
        count5 = x[5].find(",")
        man4 = int(x[5][:count5])
        discount4 = int(x[5][count5+1:])
        count6 = x[6].find(",")
        man5 = int(x[6][:count6])
        discount5 = int(x[6][count6+1:])
        if man3 > man4 and man3 > man5 and x[1] >= man3 :
            condition = round((x[1] * discount3/100 + x[3]) * (1-x[2]))
        elif man4 > man5 and man4 > man3 and x[1] >= man4 :
            condition = round((x[1] * discount4/100 + x[3]) * (1-x[2]))
        elif man5 > man3 and man5 > man4 and x[1] >= man5:
            condition = round((x[1] * discount5/100 + x[3]) * (1-x[2]))
        else:
            condition = round(x[1]*(1-x[2]) + x[3])
    return condition   #回傳最後價錢

lst = []   #建立list把方才的價錢丟進去
lst.append(savemoney(slst))
lst.append(savemoney(clst))
lst.append(savemoney(plst))
lst.append(savemoney(mlst)) 

for ans in range (len(lst)):   #如果貨量為0，就讓他加list中最大值，避免答案印出它
    if lst[ans] == 0 :
        lst[ans] += max(lst)

if min(lst) == lst[0]:    #找到最小值，印出來
    print("S商店",lst[0],sep=" ")
elif min(lst) == lst[1]:
    print("C商店",lst[1],sep=" ")
elif min(lst) == lst[2]:
    print("P商店",lst[2],sep=" ")
elif min(lst) == lst[3]:
    print("M商店",lst[3],sep=" ")

        
```

## 問題描述
測資都對，但結果是wrong answer ..
是否是要考慮價錢為0的情況，但有點不知道條件要加在哪裡><

**Comment by lova999** [comment]
你好
連結是你交出去之後
顯示WA的紐再點進去的連結
麻煩幫我更新一下
謝謝
然後售價也可能為0

**Comment by chiehrulin** [comment]
> 你好 連結是你交出去之後 顯示WA的紐再點進去的連結 麻煩幫我更新一下 謝謝 然後售價也可能為0

已更新。
試著考慮售價為０的情況，在def一開始判斷貨量是否為0，避開未考慮到售價也可能是0的情況，但不知哪裡有問題... 整個答案都錯了。
****因留言的格式會跑掉，已複製一個在上面程式碼的位置，麻煩助教查看了，謝謝!


s = input()
c = input()
p = input()
m = input() 

s = s.replace(","," ")
c = c.replace(","," ")
p = p.replace(","," ")
m = m.replace(","," ")
slst = [i for i in s.split(" ")]
clst = [i for i in c.split(" ")]
plst = [i for i in p.split(" ")]
mlst = [i for i in m.split(" ")]


if slst[0] == "0" :
    slst = ["0","-1","0","0"]            #更改售價，避免跟售價為0的情況重複
elif "%" not in slst[2]:
    slst.insert(2,"0")
if clst[0] == "0" :
    clst = ["0","-1","0","0"]
elif "%" not in clst[2]:
    clst.insert(2,"0")
if plst[0] == "0" :
    plst = ["0","-1","0","0"]
elif "%" not in plst[2]:
    plst.insert(2,"0")
if mlst[0] == "0" :
    mlst = ["0","-1","0","0"]
elif "%" not in mlst[2]:
    mlst.insert(2,"0")


def savemoney (x):
    if x[0] != "0" :        #改了這裡，下判斷，售價為0的話，也能return售價為0的情況
        for j in range (len(x)):
            if x[j] == "免運" :
                x[j] = 0
            elif "運費" in x[j] :
                fe = x[j].find("費")
                x[j] = x[j][fe+1:]
                x[j] = int(x[j])
            elif "滿" in x[j] :
                da = x[j].find("打")
                zhe = x[j].find("折")
                x[j] = x[j][1:da] + "," + x[j][da+1:zhe]
            elif "%" in x[j] :
                percent = x[j].find("%")
                x[j] = x[j][:percent]
                x[j] = float(x[j])
                x[j] = x[j] * 0.01
            else:
                x[j] = int(x[j])
        max = 0 
        if len(x) == 4:
            condition = round((x[1]*(1-x[2]) + x[3]) )
            if condition > max :
                max = condition 
        elif len(x) == 5:
            count1 = x[4].find(",")
            man = int(x[4][:count1])
            discount = int(x[4][count1+1:])
            if x[1] >= man:
                condition =  round((x[1] * discount/100 + x[3]) * (1-x[2]))
                if condition > max :
                    max = condition 
            else:
                condition = round(x[1]*(1-x[2]) + x[3])
                if condition > max :
                    max = condition 
        elif len(x) == 6:
            count2 = x[4].find(",")
            man1 = int(x[4][:count2])
            discount1 = int(x[4][count2+1:])
            count3 = x[5].find(",")
            man2 = int(x[5][:count3])
            discount2 = int(x[5][count3+1:])
            if man1 > man2 and x[1] >= man1 :
                condition = round((x[1] * discount1/100 + x[3]) * (1-x[2]))
                if condition > max :
                    max = condition 
            elif man2 > man1 and x[1] >= man2 :
                condition = round((x[1] * discount2/100 + x[3]) * (1-x[2]))
                if condition > max :
                    max = condition 
            else:
                condition = round(x[1]*(1-x[2]) + x[3])
                if condition > max :
                    max = condition 
        elif len(x) == 7:
            count4 = x[4].find(",")
            man3 = int(x[4][:count4])
            discount3 = int(x[4][count4+1:])
            count5 = x[5].find(",")
            man4 = int(x[5][:count5])
            discount4 = int(x[5][count5+1:])
            count6 = x[6].find(",")
            man5 = int(x[6][:count6])
            discount5 = int(x[6][count6+1:])
            if man3 > man4 and man3 > man5 and x[1] >= man3 :
                condition = round((x[1] * discount3/100 + x[3]) * (1-x[2]))
                if condition > max :
                    max = condition 
            elif man4 > man5 and man4 > man3 and x[1] >= man4 :
                condition = round((x[1] * discount4/100 + x[3]) * (1-x[2]))
                if condition > max :
                    max = condition 
            elif man5 > man3 and man5 > man4 and x[1] >= man5:
                condition = round((x[1] * discount5/100 + x[3]) * (1-x[2]))
                if condition > max :
                    max = condition 
            else:
                condition = round(x[1]*(1-x[2]) + x[3])
                if condition > max :
                    max = condition 
            return condition 
        else:  #如果庫量為0，就return一個最大值，這樣答案就不會是這間商店
            return max



lst = []
lst.append(savemoney(slst))
lst.append(savemoney(clst))
lst.append(savemoney(plst))
lst.append(savemoney(mlst))


if min(lst) == lst[0]:
    print("S商店",lst[0],sep=" ")
elif min(lst) == lst[1]:
    print("C商店",lst[1],sep=" ")
elif min(lst) == lst[2]:
    print("P商店",lst[2],sep=" ")
elif min(lst) == lst[3]:
    print("M商店",lst[3],sep=" ")
