### ISSUE TITLE
[Homework 2] 改考卷 

### ISSUE THREAD

**Issue by HansHiroshima** [coding-coworking-club/basic-python-fall-2021#180]
## 提交連結

https://judge.ccclub.io/status/588ce2f46cd93211b6a134b307ac3057
## 程式碼

```python
lst = input().split()
key = ''.join(lst)

rate = []
for i in range(len(key)):
    rate.append(0)
    
num = int(input())  
for i in range(num):
    sheet = input().split()
    ans = ''.join(sheet[1:])
    correct = 0
    for j in range(len(ans)):
        if ans[j] == key[j]:
            correct += 1
            rate[j] += 1
    print(sheet[0], int(100 * correct / len(ans)))

for i in range(len(rate)):
    print(100 * round(rate[i] / num, 4), '%', sep = '', end = ' ')
```

## 錯誤訊息

Wrong Answer
## 問題描述

公開測資都過了，但不知為何最後一行改成 print(round(100 * rate[i] / num, 2), '%', sep = '', end = ' ') 才能 AC，有在 Stackoverflow 上找到這篇文但看完還是不太懂 round 在什麼情況下會無法完美奇進偶捨，謝謝助教！

https://stackoverflow.com/questions/56820/round-doesnt-seem-to-be-rounding-properly

**Comment by julie-b05302301** [comment]
我覺得這應該和電腦對小數的計算有關，由於電腦對小數的計算是類似近似值的概念(電腦的數字表示法)，因此會有一些偏移
可以試試下面這段比較區別
```
print(round(20 / 45, 4))
print(round(20 / 45, 4)*100)
print(round(100 * 20 / 45, 2))
```
關於電腦對小數的計算可參考：https://sites.google.com/site/nutncsie10412/ge-ren-jian-jie/fu-dian-shu-biao-shi-fa

**Comment by HansHiroshima** [comment]
看完連結後，我還是不太懂為什麼把 * 100 一併放入 round 函數就可以解決這個問題，或者說，在什麼情況下 round 會無法準確地奇進偶捨呢？

**Comment by julie-b05302301** [comment]
計算完再捨入就是準的，捨入後再計算就有可能發生誤差。以上面的例子來說，就是第一個print出來的0.4444只是電腦讓我們看到的值，實際上它記錄的數字是有偏移的(真正儲存的數值是能表示的二進位分數中，最接近精準數值的數)，電腦拿它記錄的值再乘以100，就不會是剛好的44.44
官方說明文件(有比較事前捨入和事後捨入)：https://docs.python.org/zh-tw/3/tutorial/floatingpoint.html

**Comment by HansHiroshima** [comment]
懂了，非常清楚詳盡的文件，感謝助教，謝謝！
