### ISSUE TITLE
[General] 小明爬樓梯

### ISSUE THREAD

**Issue by HansHiroshima** [coding-coworking-club/basic-python-fall-2021#181]
## 提交連結

https://judge.ccclub.io/status/e79fc75609cbe4e3740163844f54a45a
## 程式碼

```python
def factorial(num):
    fac = 1
    for i in range(2, num + 1):
        fac *= i
    return fac 
    
n = int(input())

combi = 0
amount = n // 2

if n <= 0:
    combi = 0
elif n % 2 == 0:
    for i in range(amount + 1):
        combi += int(factorial(amount + i) / factorial(amount - i) / factorial(i * 2))
elif n % 2 == 1:
    for i in range(amount + 1):
        combi += int(factorial(amount + i + 1) / factorial(amount - i) / factorial(i * 2 + 1))
print(combi)
```

## 錯誤訊息

Wrong Answer
## 問題描述

使用排列組合的方式求解，amount 為走法中最多一步二階的個數。
公開測資都過了，不太清楚是卡在哪個隱藏測資。
麻煩助教了！

**Comment by waukin** [comment]
你有幾個測資是沒有通過的
例如：
1. input: 100 expected output: 573147844013817084101
2. input: 37 expected output: 39088169
3. input: 43 expected output: 701408733
4. input: 59 expected output: 1548008755920

**Comment by HansHiroshima** [comment]
```python
def factorial(num):
    fac = 1
    for i in range(2, num + 1):
        fac *= i
    return fac 
    
n = int(input())

combi = 0
amount = n // 2

if n <= 0:
    combi = 0
elif n % 2 == 0:
    for i in range(amount + 1):
        combi += int(factorial(amount + i) / factorial(amount - i) / factorial(i * 2))
elif n % 2 == 1:
    for i in range(11, amount + 1):
        f24 = factorial(amount + i + 1)
        f1 = factorial(amount - i)
        f23 = factorial(i * 2 + 1)
        print(f24, f1, f23)
        print(int(f24 / f1 / f23))
        combi += int(f24 / f1 / f23)
        print(combi)
        #combi += int(factorial(amount + i + 1) / factorial(amount - i) / factorial(i * 2 + 1))
print(combi)
```

謝謝助教，由於您提供的測資較大，我發現 25 應該是不正確的階梯數中最小的，正確答案是 121393，而我的答案則是 121392，再依序用不同的一步一階、一步二階組合方式排列上樓，我發現 bug 出在當一步二階只有一次，其餘 23 階階梯皆為一步一階的情形下， 24! / 23! / 1! 應為 24 種排列方式，但得到的答案卻是 23 ，想請問這是什麼原因？（上方程式碼為盡可能不更動原本程式碼情況下，這種上樓組合的排列方式）非常謝謝助教的幫忙！

**Comment by waukin** [comment]
這是Python3除法精準度的問題
當 i = 11時
你可以試著把 `f24 / f1 / f23` 印出來看看
輸出會是 `23.999999999999996`
上面的浮點數透過 `int()` 轉換就會變成 `23`
可能可以透過 `decimal` 函式庫去做計算取得更精準的結果

找到幾篇文章供你參考
1. https://stackoverflow.com/questions/40808511/doing-accurate-floating-point-division-in-python-3
2. https://stackoverflow.com/questions/588004/is-floating-point-math-broken

**Comment by HansHiroshima** [comment]
了解了，非常感謝助教！
