### ISSUE TITLE
[General] 5-1：翻箱倒櫃

### ISSUE THREAD

**Issue by linyuzz** [coding-coworking-club/basic-python-fall-2021#19]
## 提交連結

https://judge.ccclub.io/status/eba7a33f61b902736be461aba38e87d6

## 程式碼

```python

lst1 = input()
lst2 = input()
s = input()
print(s in (lst1.split() or lst2.split()))

```

## 問題描述

輸入sample在jupyter notebook試跑都是正確的，有點找不出錯誤在哪

**Comment by jasonchen1125** [comment]
你的條件寫法在Python應該只會看第一筆輸入有沒有s字串在裡面
or的部分可以拆開寫試試看
