### ISSUE TITLE
[Week #] problem_title

### ISSUE THREAD

**Issue by Bally566888** [coding-coworking-club/basic-python-fall-2021#2]
## 程式碼
s1=print("pine"+"apple")
s2=print("Python"+"Class")
print(s1+s2)

```python

```

## 問題描述

有點不太清楚這題要求我們呈現的結果，抱歉還是新手，麻煩了，謝謝。
以上是我寫的

**Comment by Bally566888** [comment]
[week1] 1-1輸出兩次
有點不太清楚這題要求我們呈現的結果，抱歉還是新手，麻煩了，謝謝。
以下是我寫的:
s1=print("pine"+"apple")
s2=print("Python"+"Class")
print(s1+s2)

**Comment by huaitzu** [comment]
同學你好，請參照學員須知內的「[GitHub Issue 使用教學](https://ccclub.notion.site/GitHub-Issue-5a270fb3e09448e1a6012082d10eb3dc)」進行提問，以便助教們協助你喔～
