### ISSUE TITLE
[Homework #] 色碼轉換

### ISSUE THREAD

**Issue by LeoLiu22** [coding-coworking-club/basic-python-fall-2021#208]
## 提交連結

import math
a = [float(a) for a in input().split(" ")]

color = 0
secnum = 0
thirdnum = 0

if a[0] >=255 :
    color += 255
elif a[0] <= 0 :
    color += 0
else :
    color += a[0]
h = math.floor(color)
colorcode = hex(h)

if len(colorcode) < 4 :
    colorcode += "0"

if a[1] >=255 :
    secnum += 255
elif a[1] <= 0 :
    secnum += 0
else :
    secnum += a[1]
i = math.floor(secnum)
secnumcode = hex(i)

if len(secnumcode) < 4 :
    secnumcode += "0"
secnumcode1 = secnumcode[2:4]

if a[2] >= 255 :
    thirdnum += 255
elif a[2] <= 0 :
    thirdnum += 0
else :
    thirdnum += a[2]
j = math.floor(thirdnum)
thirdnumcode = hex(j)
** 用 math.floor 是可能會輸入 23.54? 所以才用無條件捨去 但四捨五入也試過也不行 **
if len(thirdnumcode) < 4 :
    thirdnumcode += "0"
thirdnumcode1 = thirdnumcode[2:4]

print(colorcode+secnumcode1+thirdnumcode1)

```python

```

## 問題描述
我有自行測試過  [1.2 , 3.4 , 4.5] (實際輸入是沒有逗點的 以空格分開)
我想說可能會這樣做所以有import math for 四捨五入
也嘗試過用 無條件捨去 
也用過 不做任何修改直接把 float 轉為 int for Hex語法
但自己測試也應該都沒有問題
還是我自己有忽略了一些部分
還請助教協助 謝謝助教

**Comment by cys939** [comment]
嗨，請參考學員須知的「[GitHub Issue 使用教學](https://www.notion.so/ccclub/GitHub-Issue-5a270fb3e09448e1a6012082d10eb3dc)」，補上你的提交連結、修改中間內容，或是截圖你的 code ，方便助教幫你找錯～
