### ISSUE TITLE
[Homework 2] 色碼轉換

### ISSUE THREAD

**Issue by RayNCCU** [coding-coworking-club/basic-python-fall-2021#209]
https://judge.ccclub.io/status/b9eb86599de014b7c599f1e20d881fc5

rgb = [int(float(i)) for i in input().split(" ")]
color_code = []
for num in rgb:
    if num > 255:
        num = 255
        num = hex(num)
        color_code.append(num)
    if num<0:
        num = 0
        num = hex(num)
        color_code.append(num)
    else:
        num = hex(num)
        color_code.append(num)
for i in range(len(color_code)):
    if len(color_code[i]) < 4:
        color_code[i] = str(color_code[i])+"0"
        color_code[i] = color_code[i][3]+color_code[i][2]
    else:
        color_code[i] = str(color_code[i][2])+str(color_code[i][3])
print("0x" + color_code[0]+color_code[1]+color_code[2])

```python

```

## 測資皆對，謝謝

Runtime Error

**Comment by cys939** [comment]
嗨，你寫 if- if 的話是兩個都會跑喔，當前面有大於 255 的數時，你 num 就會轉為 str 了，下一行的 if num<0 會報錯，可以想一下怎麼調整，也給你一個測資試試看：「256 57 254」；另外，下次提問要注意格式喔，請參考學員須知中「[GitHub Issue 使用教學](https://www.notion.so/ccclub/GitHub-Issue-5a270fb3e09448e1a6012082d10eb3dc)」
