### ISSUE TITLE
[General] 綜合1-2：一奇多偶

### ISSUE THREAD

**Issue by KyleChou123** [coding-coworking-club/basic-python-fall-2021#21]
## 提交連結

https://judge.ccclub.io/problem/180033

## 程式碼

```python
l1 = input().split()
    
ans = 0
t = [0] * len(l1)
    
for i in range(len(l1)):
    t[i] = l1.count(l1[i])

    
for i in range(len(t)):
    if t[i] % 2 != 0:
        ans = l1[i]
            
print(ans)

```

## 錯誤訊息

Time Limit Exceeded
Time: 2100ms Memory: 10MB Lang: Python3 Author: a13a5as1s@gmail.com

## 問題描述

1. 此題 time limit 1000MS OJ上跑2100MS 我用 VS CODE 查執行時間沒有超過 想問一下是為什麼？ 
2. 有什麼辦法可以解決 time limit exceeded

**Comment by Yating2021** [comment]
有一樣的問題

Time Limit Exceeded
Time: 2001ms Memory: 10MB Lang: Python3

**Comment by chuhao** [comment]
我今天也提出相同的問題
助教的回覆如下

也許可以使用字典的資料格式去處理會比較方便
字典的key和其對應的value分別是數字、出現的次數
假設有一個串列 [1, 2, 3, 2, 1, 1, 1, 3, 3, 3, 3]
產生的字典會是
dict = { 1: 4, 2: 2, 3: 5 }
再去判斷 dict 這個字典哪一個數字出現的次數為奇數

請參考
