### ISSUE TITLE
[Homework 1-3] ooxx

### ISSUE THREAD

**Issue by organicguava** [coding-coworking-club/basic-python-fall-2021#23]
## 提交連結
https://judge.ccclub.io/status/79c0a3f23e0abd114e6d67d6b937f43d

## 程式碼

```python
num=input()
lst=[]
for n in range(len(num)):
    lst.append(int(num[n])) #[1,4,7]

t1=['(',' ',' ',' ',')',sep=","]
t2=['(',' ',' ',' ',')',sep=","]
t3=['(',' ',' ',' ',')',sep=","]
for a in range(len(lst)):
    if int(lst[a])==1:
        t1[1]='O'
    if int(lst[a])==2:
        t1[2]='O'
    if int(lst[a])==3:
        t1[3]='O'
    if int(lst[a])==4:
        t2[1]='O'
    if int(lst[a])==5:
        t2[2]='O'
    if int(lst[a])==6:
        t2[3]='O'
    if int(lst[a])==7:
        t3[1]='O'
    if int(lst[a])==8:
        t3[2]='O'
    if int(lst[a])==9:
        t3[3]='O'

print(t1,end="\n")
print(t2,end="\n")
print(t3)
```

## 問題描述

不知道要如何表示九宮格，我將九宮格拆成3個list，但出現syntax error

**Comment by dennisc1213** [comment]
如果出現syntax error，那在本機端的Error message就會告訴你哪邊有問題啦～
你現在遇到的情形是程式看不懂 ` sep ="," `

**Comment by organicguava** [comment]
@dennisc1213 想請問一下sep的寫法是哪裡錯了嗎 回去看了課程還是不知道@@
上網查了類似的錯誤，都是發生在使用python三以下的環境，但我用的是3

**Comment by lazyYC** [comment]
@organicguava 你好，以下提供幾個小建議：
1. sep 這個參數你應該只有在 print() 這個函式看過吧😂每個函式支援的參數不同喔，而且 [] 本身不是一個函式。
2. 由於在print的時候要避開印出 ','，這邊建議可以使用join這個函式來輸出
3. 可能有更簡潔的寫法，由於每個數字對應的位置在九宮格上是固定的，可以思考一下印出數字時的規律（例如印出3 & 6後需要換行）。
