### ISSUE TITLE
[Homework 2] 改考卷

### ISSUE THREAD

**Issue by physkevin** [coding-coworking-club/basic-python-fall-2021#233]
## 提交連結

https://judge.ccclub.io/status/e46b46b0009e1def8882496df1a09f2f

## 程式碼

```python
#change the format of the correct answer to string
answer = ''.join(input().split(' ')) 

#student number
s_num = int(input())

#restore all the names
names = []

#restore all the scores
scores = [] 

#restore the number of students who have got the right ans for each problem
correct_ans_num = []  

for i in range(s_num):
    score = 0
    
    #input: student name, their answer
    s_ans_lis = input().split() 
    
    #substract their names to a new variable "s_name", and then delete them from the list
    s_name = s_ans_lis[0]
    s_ans_lis.pop(0)
    
    #now the answer of the student is remained in the list, and I change the format to string
    s_ans = ''.join(s_ans_lis)
    
    for j in range(len(s_ans)):
        #here I wanna count how many students have done right for each question
        #Since the correct_ans_num list is empty at first, I use append when i = 0
        if i == 0:
            correct_ans_num.append(int(s_ans[j] == answer[j]))
        elif i != 0:
            correct_ans_num[j] += int(s_ans[j] == answer[j])
        
        #Secondly, I wanna calculate each student's score
        if s_ans[j] == answer[j]:
            score += int(100/len(answer))
    
    #and then I append the corresponding name and score into their lists respectively
    names.append(s_name)
    scores.append(score)
              
#finally, I print the result
for k in range(len(names)):
    print (names[k], scores[k])
for w in range(len(answer)):
    print (str(round(correct_ans_num[w]/s_num, 4)*100) + '%' , end = ' ')
```

## 問題描述

我試了兩個Sample Input出來的結果都是正確的，也有注意取到小數點下第二位，都和Sample Output一模一樣，但最後結果是Wrong Answer，真的不知道為什麼，懇請助教大大指點迷津@@

**Comment by julie-b05302301** [comment]
測測下列這組測資：
44444 22222
42
小明 22424 44241
小華 11212 44424
泱泱 13411 43221
小美 44312 21343
小迪 43242 24143
姿怡 32331 22141
國國 12221 33211
小晴 34442 24224
安安 11423 31234
詩雅 22241 41424
柏靈 24433 22143
亞恩 23432 11144
孟純 21143 14422
宜蓁 41333 22121
潔心 33323 33424
子瑄 43111 41221
采潔 33332 14122
留佳 33213 14223
婉淩 33412 11112
佳霓 14341 12412
語晴 34233 42222
麻由 23134 21342
品涵 11431 33313
林倢 22413 42331
佳俐 24224 22314
伊柔 21314 41444
云珏 43233 34334
逸嘉 14324 41231
法法 41414 42334
妤葳 33432 13343
瑞婷 14413 43411
彤薰 21314 21223
曉晴 24112 44334
于馨 21211 21431
羽翎 32311 14312
易沄 11342 12131
美玲 44131 41412
佳郁 44443 11123
硯晨 24223 44224
騏卉 23312 24344
子筑 44333 34424
亭莉 23343 31112

應輸出：
小明 30
小華 10
泱泱 30
小美 30
小迪 30
姿怡 20
國國 10
小晴 60
安安 20
詩雅 20
柏靈 40
亞恩 10
孟純 30
宜蓁 40
潔心 10
子瑄 30
采潔 20
留佳 20
婉淩 20
佳霓 40
語晴 50
麻由 30
品涵 10
林倢 20
佳俐 40
伊柔 10
云珏 10
逸嘉 30
法法 40
妤葳 10
瑞婷 20
彤薰 40
曉晴 10
于馨 10
羽翎 10
易沄 20
美玲 30
佳郁 50
硯晨 30
騏卉 10
子筑 30
亭莉 20
21.43% 30.95% 30.95% 19.05% 16.67% 26.19% 21.43% 26.19% 35.71% 21.43%
