### ISSUE TITLE
[Homework 3] 幾A幾B

### ISSUE THREAD

**Issue by hsunAlfred** [coding-coworking-club/basic-python-fall-2021#236]
## 提交連結

https://judge.ccclub.io/status/9ef2a91cdb25cb687c207142ff71c515

## 程式碼

```python
def xAyB():
    ans, guess = input(), input()
    ans_guess = tuple(zip(ans, guess))
    not_corr = [set(), set()]
    x = 0
    for i in ans_guess:
        if i[0] == i[1]:
            x += 1
        else:
            not_corr[0].add(i[0])
            not_corr[1].add(i[1])

    if len(ans) == len(guess):
        y = len(not_corr[0] & not_corr[1])
    elif len(ans) > len(guess):
        temp = set(ans[len(guess):])
        y = len((not_corr[0] | temp) & not_corr[1])
    elif len(ans) < len(guess):
        temp = set(guess[len(ans):])
        y = len(not_corr[0] & (not_corr[1] | temp))

    print(f'{x}A{y}B')


xAyB()
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/78075403/139385375-678ceab6-8cf9-4ee5-9619-1f1e6471ec70.png)

## 問題描述
我先透過zip把 **出題者的答案** 跟 **答題者的回答** 依照每個位數合併，然後逐一比對，如果相符x就+1；
不相符時存到not_corr這個list裡面，not_corr中有兩個set，透過set的特性先將重複的元素過濾一遍，最後再透過交集後集合的長度求得y(為了避免 **出題者的答案** 跟 **答題者的回答**  長度不同在做zip的時候長的部分被截掉，所以還有判斷是調整)

judge上的測資執行後有相同的結果，但是judge顯示wrong answer

**Comment by happywillie** [comment]
錯誤的概念跟 #235 有點像～可以參考看看那邊的回覆，有問題再跟我說！

**Comment by hsunAlfred** [comment]
AC了 謝謝~
本來懶得另外處理y，結果就在那邊出錯了QQ
