### ISSUE TITLE
[General] problem_180103字串加密

### ISSUE THREAD

**Issue by LiYiJie321** [coding-coworking-club/basic-python-fall-2021#24]
## 提交連結

https://judge.ccclub.io/status/c8b658b17e02671a4b99ef1921974f4a

## 程式碼

```python
s = ord(input())
N = str(s).split()
n = 0
for i in range(len(N)) :
    I = int(N[i])
    n += 1
print(chr(I+n), end="\t")
```

## 錯誤訊息

![擷取](https://user-images.githubusercontent.com/91873933/135816565-67318d59-df3c-4811-9ce9-9c6101613359.PNG)

## 問題描述

可以正確顯示輸入一個字母的結果，但要如何讓程式可以輸入三個字母 ?
ord似乎只能一次輸入一個字母

**Comment by dennisc1213** [comment]
既然ord一次只能轉換一個字母，何不先把字串拆開成獨立字母後，再一個一個轉換呢？

**Comment by LiYiJie321** [comment]
> 既然ord一次只能轉換一個字母，何不先把字串拆開成獨立字母後，再一個一個轉換呢？

我嘗試在迴圈轉換，但語法不知道該怎麼寫才正確?

![擷取1](https://user-images.githubusercontent.com/91873933/135823072-3ec1e35c-4347-4171-81a3-d5a203f26f64.PNG)

**Comment by LiYiJie321** [comment]
已解決，謝謝
