### ISSUE TITLE
[Homework 2] 改考卷

### ISSUE THREAD

**Issue by YFK2120** [coding-coworking-club/basic-python-fall-2021#240]
## 提交連結

https://judge.ccclub.io/status/94631ede1c8643a066a3b8aef254860a

## 程式碼

correct_ans = input().split(' ')
x = len(''.join(correct_ans)) # 全部共有 x 題
ans = []
for i in correct_ans:
    ans.extend(list(i))  # 把正確解答的答案整合為一個list
    
person = int(input()) # 學生人數
student = []
student_new = [] # 暫時用，之後會成為空list
student_ans = []
for i in range (person):
    student.append([str(a) for a in input().split(' ')]) # 在student的list中，創建子list
    for j in student[i][1:]:
        student_new.extend(list(j))
    student_ans.append(student_new)  # 把每個人的答案改為list，放在student_ans
    student_new = []

count_score = 0
for i in range(len(student_ans)):
    for j in range(len(student_ans[i])):
        if student_ans[i][j] == ans[j]:
           count_score = count_score + 1
        else:
            pass
    print(f'{student[i][0]} {int(count_score/x*100)}')
    count_score = 0
        
count = 0
correct_num = [0]*x     # 建有x個0的list
for i in range(len(student)):
    for j in range(len(student_ans[i])):
        if student_ans[i][j] == ans[j]:
           correct_num[j] = correct_num[j] + 1
        else:
            pass

correct_rate = []
for i in range(len(correct_num)):
    correct_rate.append(str(round((correct_num[i]/person)*100, 2)) + '%')

print(' '.join(correct_rate))
```python

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/73774348/139430149-22dc0a24-06ae-4362-98c1-19b220710b80.png)

## 問題描述

可在在其他環境下執行，但在Judge上則為WA，再請助教協助指導，謝謝

**Comment by julie-b05302301** [comment]
請參考[Issue#137](https://github.com/coding-coworking-club/basic-python-fall-2021/issues/137)
