### ISSUE TITLE
[Homework 2] 色碼轉換

### ISSUE THREAD

**Issue by RobertLin1011** [coding-coworking-club/basic-python-fall-2021#265]
## 提交連結

https://judge.ccclub.io/contest/76/problem/02
## 程式碼

```python
lst = [int(float(num)) for num in input().split(" ")]

color_code = []

for i in range(len(lst)):
    if lst[i] >= 255:
        lst[i] = 255
        color_code.append(hex(lst[i]))
        print(color_code)
    elif lst[i] <= 0:
        lst[i] = 0
        color_code.append(hex(lst[i]))
    else:
        color_code.append(hex(lst[i]))

for j in range(len(color_code)):
    if len(color_code[j]) == 3:
        color_code.insert(j, "0")

str_lst = "".join(color_code)
str_lst = str_lst.replace("0x", "")
print("0x"+str_lst)


```

## 錯誤訊息

Wrong Answer
## 問題描述

我這邊感覺是17、18行 if len(color_code[j]) == 3: 和 color_code.insert(j, "0") 這兩段設錯，測資一能過，測資二會變成0x0000b38，比正解0x000b38多一個0，我這樣寫應該是加兩個0就好，但程式會多+1次，不太清楚為什麼，麻煩助教給方向了，謝謝。

**Comment by cys939** [comment]
嗨，雖然作業二已截止，但還是跟你說一下問題～
你用 insert 補零的方式加入 color_code，他會在該位前面補零，但 index 就被改變，加上你是用 range（長度）去跑迴圈，這樣他最多跑三次就結束了，但補零的位置不會是正確的，可能全部都補在最前面

建議你可用 Trace code 去看實際跑的過程，也給你一個測資「12 13 14」，答案應該是「0x0c0d0e」但你的是「0x000cde」，如果想練習，可以從 Problems 找到這題再試試看喔～

**Comment by RobertLin1011** [comment]
有我我後想到insert會改變index順序，後來先改用兩次replace的語法就完成這題了，感謝助教用心回覆!
