### ISSUE TITLE
[Homework 3] 分配工作

### ISSUE THREAD

**Issue by FlyTori** [coding-coworking-club/basic-python-fall-2021#266]
## 程式碼

```python

```

## 問題描述
想請問一下問題描述：
小明企圖找出可以最小化工作成本的分配方式（其實也確實有最佳化的演算法），但小明因為工作太忙了，還沒有認真研究要怎麼分配，所以想了一個折衷的貪婪演算法：每次配對時，在目前尚未配對的員工與工作中，找出一個成本Ci,j最小的員工i與工作j做配對，若平手則找i + j較小的，若還是平手則找i較小的，重複進行此流程直到所有員工與工作配對完畢。

呈上，配對的順序是：
1. 已有工作的員工不納入考慮
2. 找該工作中，成本最小的員工
3. 如果平手，找員工編號I ＋工作編號J 較小的員工
4. 如果還是平手，找 員工編號I 較小的員工

但每次都是同一個工作的各員工成本進行比較，那J都會是相同的，用 I+Ｊ和只用Ｉ找員工，不是一樣嗎？

**Comment by dennisc1213** [comment]
2. 找該工作中，成本最小的員工
這邊我的理解是"找所有可以被選擇的工作'中，成本最小的員工/工作組合

例如有
5,1,20
9,20,20
10,20,20

依我的理解會是1,9,20
依你的理解可能會是5,20,20  (看到你 #267 提問的code，應該會這樣跑沒錯)

**Comment by FlyTori** [comment]
謝謝提示，我寫出來了！！
