### ISSUE TITLE
[General] 5-1：翻箱倒櫃

### ISSUE THREAD

**Issue by ce9sa14hess** [coding-coworking-club/basic-python-fall-2021#27]
## 提交連結

https://judge.ccclub.io/status/21f55ffa656738452c54d6ed8dfdc4f8

## 程式碼

```python
lst1=input()
lst2=input()
x=input()
lst1=lst1.split(" ")
lst2=lst2.split(" ")
x in lst1 or x in lst2
```

## 問題描述

在Jupiter notebook是跑都可以，但在judge是WA

以下是我的想法：
先設3個input （lst1、lst2以及x）
lst1及lst2分別以lst1.split(" ")及lst2.split(" ")來分開字串（以空白鍵為分開基準），成為list，並回指定給自己，
找x是否出現在lst1或lst2，

以Judge的sample為例，在Jupiter notebook皆會直接出現True，但在judge是WA

**Comment by waukin** [comment]
你的想法大致上沒有問題！
不過最後一行需要修改成 `print(x in lst1 or x in lst2)`
Judge系統才能讀取程式的輸出值唷！

**Comment by ce9sa14hess** [comment]
謝謝！
