### ISSUE TITLE
[Homework 3] 幾A幾B

### ISSUE THREAD

**Issue by joyshiang** [coding-coworking-club/basic-python-fall-2021#271]
## 程式碼

```python
ans = list(input())
guess = list(input())

A = 0
B = 0

for i in range(len(guess)):
    if ans[i] == guess[i]:
        A += 1           
    elif ans[i] in guess:
        B += 1

print(str(A) + 'A'+ str(B) + 'B')
```

## 問題描述

三組測資都跑得出來，但是Judge顯示WA，想請問是有那裡沒有考慮到嗎?另外想問一定要像提示說的要用dictionary才解的出來嗎?

**Comment by happywillie** [comment]
可以參考  #243 ，有類似的狀況~

另外，github發文要記得附提交連結喔，也要詳細說明解題思路，其他人會比較好抓到bug，可以參考[github 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036) ~
