### ISSUE TITLE
[Homework 3] 快樂農場

### ISSUE THREAD

**Issue by DrNemoWu** [coding-coworking-club/basic-python-fall-2021#275]
## 提交連結

https://judge.ccclub.io/status/ce61ba900dd2044afb816883fb814b73

## 程式碼

```python
farm = []
while True:
    x = input()
    x1 = x.split(' ')
    farm.append(x1)
    if x == '':
        break  
farm.remove([''])
#print(farm)
for i in range(len(farm)):
    farm[i].insert(0,'0')
    farm[i].insert(len(farm[i]),'0')
empty = []
for i in range(len(farm[0])):
    empty.append('0')
farm.insert(0,empty)
farm.insert(len(farm),empty)
#print(farm)
count_list = []
for i in range(1,len(farm) - 1):
    for j in range(1,len(farm[i]) - 1):
        count = 4
        if farm[i][j] == '1':
            if farm[i - 1][j] == '1': #上
                count = count - 1
            if farm[i + 1][j] == '1': #下
                count = count - 1
            if farm[i][j - 1] == '1': #左
                count = count - 1
            if farm[i][j + 1] == '1': #右
                count = count - 1
            count_list.append(count)
#print(count_list)
print(sum(count_list))

```

## 錯誤訊息

RunTime Error
## 問題描述

助教好！非常感謝助教撥冗閱讀這篇貼文，我主要有兩個問題點：
1. 我是利用 input = '' 來當成是結束輸入的條件，不知道這樣寫正不正確？因為題目也沒有詳細說明，但這樣會造成輸入的測資和輸出的結果間多了一個空行，不知道這樣會不會影響。
2. 我主要的問題是想問，我的程式碼出現了RunTime Error，但我在交之前已經試過很多種的測資和一些比較極端的測資，也都能給出正確答案，由於錯誤是RunTime Error，應該遇到一些測資時會出現錯誤，但我一直試不出來QAQ。
3. 我的解題思路主要是利用計算每一個1的上、下、左、右位置有沒有1，如果有，就把圍欄數（count)減1，預設count是4，也就是四面都有圍籬，我在開始判斷每一個1之前，我將輸入的資料最外面包了一層0，如下圖：
 
<img width="127" alt="Screen Shot 2021-11-03 at 00 00 57" src="https://user-images.githubusercontent.com/93602582/139893914-1b605404-9534-4d73-93ee-c690441bc3dd.png">
會這樣做的原因是我希望所有input的資料都能有上下左右，不用再特別分出第一行，最後一行，每行第一個和最後一個去做計算（因為不是每個位置的上下左右都有人），運行的結果，就我目前測試過得測資來看，應該都能給出正確解答。但不知道是不是有哪個環節沒處理好，才會出現RunTime Error。我已經盡量將我的思路說出來了，非常感謝願意看看的人！

**Comment by dennisc1213** [comment]
我不是助教，但是我的解題思路跟你幾乎一模一樣 XD
1. 你如果在x=input()後面，就先做if x ==''的判斷，就不會多一行了！
2. 關於RunTime Error ，一開始接收輸入的方法，在這邊可能無法用input()。我用sys.stdin.readline().strip()可以AC。

下面這個連結有說明sys.stdin.readline() 跟input()的差異，給你參考：
[https://www.geeksforgeeks.org/difference-between-input-and-sys-stdin-readline/](url)

**Comment by DrNemoWu** [comment]
太感謝你了！我馬上試試看！

**Comment by DrNemoWu** [comment]
我剛剛用jupyter寫sys.stdin.readline()的讀輸入法時，遇到一個問題，
我寫完程式，要跑時，我沒辦法輸入東西耶？我是搞錯什麼了嗎？真的很不好意思

**Comment by dennisc1213** [comment]
你有先import sys 嗎？

> 我剛剛用jupyter寫sys.stdin.readline()的讀輸入法時，遇到一個問題，
> 我寫完程式，要跑時，我沒辦法輸入東西耶？我是搞錯什麼了嗎？真的很不好意思

**Comment by DrNemoWu** [comment]
有的，剛剛上網查好像有說在jupyter notebook中用sys.stdin.readline()會有一點問題，無法顯示輸入提示，請問您也適用jupyter notebook寫的嗎～

**Comment by DrNemoWu** [comment]
> 你有先import sys 嗎？
> 
> > 我剛剛用jupyter寫sys.stdin.readline()的讀輸入法時，遇到一個問題，
> > 我寫完程式，要跑時，我沒辦法輸入東西耶？我是搞錯什麼了嗎？真的很不好意思

真的非常感謝dennisc1213大大，我剛剛把程式丟到VScode做修改並測試，把input改成sys.stdin.readline()就AC了！太好了！

**Comment by dennisc1213** [comment]
太好了～～

我是用 Thonny 跟Pyto
沒想到是Jupyter的問題呀!
希望助教們下次可以說明一下這題為什麼要用stdin 不能用input()

**Comment by DrNemoWu** [comment]
> 太好了～～
> 
> 我是用 Thonny 跟Pyto 沒想到是Jupyter的問題呀! 希望助教們下次可以說明一下這題為什麼要用stdin 不能用input()

對啊....

**Comment by dennisc1213** [comment]
hey~
我看到閱讀清單裡面有講到不定行輸入，還是可以用input()來做！！！
跟你分享
https://ccclub.notion.site/01817380bbba41e6abf882a569073626
