### ISSUE TITLE
[Homework 3] 快樂農場

### ISSUE THREAD

**Issue by minminLu** [coding-coworking-club/basic-python-fall-2021#290]
## 提交連結

https://judge.ccclub.io/status/47952aaf600fa847112e74c9c06ef5d2

## 程式碼
```python
#快樂農場
#不定行輸入 
farm_list = []
while True:
    try:
        farm = [int(i) for i in input().split(" ")]
        farm_list.append(farm)
    except:
        break
# farm_list = [[0,1,0,0], farm_list[0]
#             [1,1,1,0],  farm_list[1]
#             [0,1,0,0],  farm_list[2]
#             [1,1,0,0]]  farm_list[3]      

#多加外圍 
for i in range(len(farm_list)):
    farm_list[i].insert(0, 0)
    farm_list[i].insert(len(farm_list[i]), 0)
    
temp = farm_list[0][:]    
for idx, elem in enumerate(temp):
    if elem == 1:
        elem = 0
    
farm_list.insert(0, temp)        
farm_list.insert(len(farm_list) + 1, temp)

ans = 0 
#計算柵欄數量
for i in range(1, len(farm_list) - 1):
    for j in range(1, len(farm_list[i]) - 1):
        count = 4
        if farm_list[i][j] == 1:  
            #上下左右有1
            if farm_list[i][j-1] == 1:
                count -= 1
            if farm_list[i][j+1] == 1:
                count -= 1
            if farm_list[i-1][j] == 1:
                count -= 1
            if farm_list[i+1][j] == 1:  
                count -= 1
            ans += count
print(ans)

```

## 錯誤訊息

![擷取](https://user-images.githubusercontent.com/64120193/140678628-8d86c3eb-2ba7-4806-aa5d-1acd6c26fa8b.JPG)

## 問題描述

測資有過，但為runtime error，不知道是哪裡出了問題，再麻煩助教解答疑惑!

**Comment by SleeperShark** [comment]
抱歉我沒有很懂你的邏輯是啥@@
我這邊貼一組你沒過的 測資 ，你試試看你的邏輯帶入這個題目有沒有問題。
```
0 0 0 0 0
0 1 1 1 0
0 1 1 1 0
0 0 0 0 0
```
你如果還想不通的話再來討論解這題的邏輯。

**Comment by minminLu** [comment]
好的，謝謝助教，我有寫出來了，但有問題想問! 解題的想法是
(1)一開始是觀察到如果在1的外圍放四面柵欄(count=4)，如果上下左右有1個1就扣掉1，有2個1就扣掉2，以此類推，加總起來會是答案。因此寫了迴圈逐一去檢查偵測到1的話是否上下左右有1，如果有就逐一扣掉(註解:計算柵欄數量) p.s用了助教的測資發現這個部分的寫法有問題所以有再去改善

(2)但因為會有1在邊界的問題，所以想說要在外圍再多加上一圈0避免掉此問題(註解:多加外圍)
在多加外圍的地方有問題想問，一開始的寫法是想說複製farm_list裡index=0的串列，如果有1的話我就轉成0，再插入到farm_list裡，但這個寫法會有問題，我用比較極端的測資輸入[[1,1,1,1], [1,1,1,1]]出來的結果會是
[[0, 0, 0, 1, 1, 0], [0, 1, 1, 1, 1, 0], 
[0, 1, 1, 1, 1, 0], [0, 0, 0, 1, 1, 0]]
而不是我預期的
[[0, 0, 0, 0, 0, 0], [0, 1, 1, 1, 1, 0], 
[0, 1, 1, 1, 1, 0], [0, 0, 0, 0, 0, 0]]
但我不知道原因是什麼QQ 

最後有用了其他方法解決，但還是想請助教解答上述的疑惑，謝謝助教!

**Comment by SleeperShark** [comment]
``其實你只要自己print一下，就會知道問題是啥了。
我直接照抄你的temp公式，結果如下:

```python
farm_list = [ [1, 1, 1, 1],
                    [1, 1, 1, 1] ]

temp = farm_list[0][:]    
for i in temp:
    if temp[int(i)] == 1: 
        temp[i] = 0

print(temp)
# [0, 0, 1, 1]
```
由此可知，你在temp迴圈處理的時候就發生問題。

再來看你的迴圈，你的想法很簡單，就是逐個檢查temp裡的elem，如果是 1 的話就設為 0。
但是你搞錯你迴圈裡取出來的東西 i 到底是甚麼。

一般來說我們在跑 list 物件迴圈時的兩個辦法，一是用range遞增的方式逐一取出 idx :
```python
for idx in range(0, len(lst)):
    if lst[idx] == n:
        # do something
```

再不然就是直接取出 list 的元素
```python
for elem in list:
    if elem ==n:
        # do something
```
打到這裡你應該懂了，你把 i 的身分搞混了，你以為你是根據 index 取出元素，實際上 i 本身就是元素了。

因此建議如果要迴圈 list 物件時，可以用 enumerate 這個函數，同時把 index 跟 elem 取出來

```python
for idx, elem in enumerate( lst ):
    # do something
```
這樣不管你是要對 idx 操作還是 elem 操作都可以，一舉兩得啦~

**Comment by minminLu** [comment]
助教謝謝! 我有將這個部分改成以下程式碼，但還是沒辦法順利將元素轉換成0，想說還是要把原因問清楚! 我有把上面的程式碼更新了，再麻煩助教指點，謝謝!    
temp = farm_list[0][:]    
for idx, elem in enumerate(temp):
    if elem == 1:
        elem = 0

**Comment by SleeperShark** [comment]
```python
for idx, elem in enumerate(temp):
    if elem == 1:
        elem = 0
```
在這組迴圈裡面，你要先知道你取出來的elem是什麼。
如果今天你取出來的東西是一個 "物件" 層級的東西，那 迴圈式 會幫你把這個物件的記憶體位置抓出來、丟給elem這個新變數，如果你改變elem，會同時改變 原本那個物件的值；

但如果你今天取出來的東西是基本資料型態，如boolean, interger, float等，那 **_迴圈式 只會把這個值複製，把這個值丟給新變數elem儲存_**。
此時elem變數與原本list裡面的元素本身就沒有瓜葛了，你把elem改掉也不干原本元素的事情。
這個概念牽扯到電腦如何儲存記憶體，也就是pointer的概念，你有興趣可以自己估狗一下。
至於你要怎麼做才能改掉list裡的元素值? 只能透過用index來抓取元素真正儲存的位置了。
```python
l1 = [0, 0, 0, 0]
for idx, elem in enumerate(l1):
    if elem == 0:
        l1[idx] = 1
    
print(l1)
# [1, 1, 1, 1]
```

至於我前面說的 物件層級 的elem，你可以參考下面這個例子想一下
```python
l1 = [[3], [1], [2], [1]]
for idx, elem in enumerate(l1):
    if elem[0] == 1:
        elem[0] = 9
    
print(l1)
# [[3], [9], [2], [9]]
```
這個例子裡，抓取的 elem 都是List，屬於物件層級，elem儲存的就是裡面元素的儲存記憶體位置，這時你直接對 elem 進行操作，就會影響那個元素實際儲存的位置，所以會被改動。

**Comment by minminLu** [comment]
好的~謝謝助教
