### ISSUE TITLE
[Homework 3] 分配工作

### ISSUE THREAD

**Issue by garykhtw** [coding-coworking-club/basic-python-fall-2021#291]
## 提交連結

https://judge.ccclub.io/contest/80/problem/03

## 程式碼

```python

```

## 問題描述

請問助教，為何input-2測資答案是(1, 2, 0)，而不是(1, 0, 2)。依照若平手則找i + j較小的，若還是平手則找i。

**Comment by jennifer090** [comment]
不是依照員工順序來選喔，是直接挑cij最小的
sample 2
3
7,6,7
6,7,6
2,2,2
-----------------------------------------
先找出第一個成本最小的(標粗字)
3
7,6,7
6,7,6
**2**,2,2
所以第0項工作給了第3位工人
3
X,**6**,7
X,7,6
X,2,2
再來第1項工作給了第1位工人
3
X,X,7
X,X,6
X,X,2
最後剩下第2位工人只剩下第2項工作
所以工人      1 2 3
分到的工作   1 2 0
