### ISSUE TITLE
[Homework 3] 合法數獨

### ISSUE THREAD

**Issue by joyshiang** [coding-coworking-club/basic-python-fall-2021#299]
## 提交連結
dda5e1974e9f

## 程式碼

```python
dictionary = {x: input().split(',') for x in range(1, 10)}  #把input變成key為1-10、Value為每行input的list的字典。
check = 0  
for i in range(1,10): #檢查橫向
    for j in range(9):
        if dictionary[i].count(j) > 1:
            print('False')
            check += 1
          
def ckeck_vertical(k, line):  #檢查直向的涵式:把值得數字append到一個新的list
    ckeck_vertical1 = []
    for j in range(1,10):
        ckeck_vertical1.append(dictionary[j][line])
    answer = ckeck_vertical1.count(k)
    return answer

for d in range(1, 10): #檢查直向:檢查涵式中每個新的list有無重複的數字1-9
    for h in range(1, 10):
        if ckeck_vertical(d, h) > 1:
            check += 1
 
def ckeck_left(dict, k): 檢查左邊上中下九宮格的涵式:把值得數字append到一個新的list
    ckeck_left = []
    for i in range(0, 7, 3):
        ckeck_left.append(dictionary[i][0])
        ckeck_left.append(dictionary[i+1][1])
        ckeck_left.append(dictionary[i+2][2])
    answer = ckeck_left.count(k)
    return answer

for k in range(1, 10):#檢查左邊上中下九宮格:檢查涵式中每個新的list有無重複的數字1-9
    if ckeck_left(dictionary, k) > 1:
        check += 1

def ckeck_middle(k): 檢查中間上中下九宮格的涵式:把值得數字append到一個新的list
    ckeck_middle = []
    for i in range(0, 7, 3):
        ckeck_middle.append(dictionary[i][3])
        ckeck_middle.append(dictionary[i+1][4])
        ckeck_middle.append(dictionary[i+2][5])
    return ckeck_middle.count(k)

for k in range(1, 10):#檢查中間上中下九宮格:檢查涵式中每個新的list有無重複的數字1-9
    if ckeck_middle(k) > 1:
        check += 1
        
def ckeck_right(k): 檢查右邊上中下九宮格的涵式:把值得數字append到一個新的list
    ckeck_right = []
    for i in range(0, 7, 3):
        ckeck_right.append(dictionary[i][6])
        ckeck_right.append(dictionary[i+1][7])
        ckeck_right.append(dictionary[i+2][8])
    return ckeck_right.count(k)

for k in range(1, 10):#檢查右邊上中下九宮格:檢查涵式中每個新的list有無重複的數字1-9
    if ckeck_right(k) > 1:
        check += 1
       
if check == 0 :       
    print('True')
```

## 錯誤訊息
![image](https://user-images.githubusercontent.com/91731774/141104930-0dae9701-fd88-4142-838f-e345cc808734.png)
以上圖片為執行第9-19行時出現的訊息。
![image](https://user-images.githubusercontent.com/91731774/141104963-c8111233-b684-41c6-908b-58418964b796.png)
以上圖片為執行九宮格檢查時(也就是第92-32, 34-44, 46-56行)時出現的訊息。

*圖片的行數不準，文字的行數才是對到Judge上的行數。

## 問題描述
思路都有標在程式碼內，我覺得我知道要怎麼解題的邏輯，只是不了解要用甚麼樣的語法詮釋我的邏輯。

**Comment by TJ72** [comment]
1. `check_vertical` 函式會噴 index out of range 的錯誤訊息，是因為在第 17 行的迴圈，妳想從第 1 行判斷到第 9 行，判斷每一行的合法性；但在原本存數獨資料的字典裡，它每一行資料(串列)的 index 是從 0-8。
2. 判斷九宮的函式噴的錯誤訊息，是因為妳存資料的字典 key(每一列的 index) 是用 1-9 來存，但函式中妳的迴圈想從第 0 列開始判斷，才會噴 key 不在字典裡的錯誤訊息。

我的建議：
- 可以在讀數獨的時候先存成 2-dimensional list，在後續做判斷會直覺一點～
- 如果把數獨資料存成 2D list 的話，在檢查行、列、九宮的時候就會有一些規律，可以方便一點；e.g. 左上的那一宮 (row // 3, col // 3) 都會是 (0, 0) 之類的。
- (optional)這題的 tag 會有字典，是因為在判斷行、列和九宮的合法性時，可以透過字典會比較容易幫助判斷；可能可以先設計出三個字典，分別只存每一列、每一行和每一宮的數字；然後因為數獨中的每一個格子都有對應的列、行和宮的位置，妳再跑一次數獨中每一個格子，判斷每一個格子的三個條件是不是合法就可以了。

**Comment by joyshiang** [comment]
謝謝助教!1,2的問題已解決了~但是出現WA，第二個測資出來的是應該要是False，卻跑出True。我了解您在建議中提到的把資料讀成2D list的作法，但是想了解我這樣的解法那裡有沒有考慮到的><以上附的是提交連結:70f404071593

**Comment by TJ72** [comment]
我剛發現了一個問題：妳在讀資料的時候，沒有把數獨裡的數字轉成 integer ，在後面用 `list.count(element)` 判斷合法性時，因為 element 丟的都是 integer，所以 count 出來的次數永遠都會是 0。

1. 檢查 1-9 列(橫向)是否合法時，迴圈跑的 index 好像不太對
2. 在檢查九宮的函式中，妳想分左、中、右，同時檢查上、中、下三個宮的合法性，但我覺得用妳的方法好像沒辦法做到
3. 檢查九宮的合法性，九宮的位置應該不太對(可以 print 出來看一下位置是不是自己要取的)

目前我看到的問題應該就差不多上面那 4 點，如果還有其他問題歡迎再繼續留言討論，加油！
（btw 提交連結貼整串網址比較好XD）

**Comment by joyshiang** [comment]
謝謝助教!!!

https://judge.ccclub.io/status/e323ade8c750f763e0993a5acddad083

這是我改好後的程式碼。改變的地方有:
1. 把input變成2D list
2. 把數獨裡的數字轉成 integer 
3. 檢查橫向的 index 
4. 檢查九宮格的方式(但應該是最土法煉鋼型的檢查法><)

改完後兩個測資都有跑出正確output，但是Judge顯示WA。想請問哪裡沒有考慮到~

**Comment by TJ72** [comment]
妳差一點點就可以 AC 了！其實程式碼的邏輯都是對的，要稍微檢查一下最後的輸出，建議可以把檢查橫列的輸出一起統一用變數 `check` 控制就可以了。

**Comment by joyshiang** [comment]
謝謝助教!寫出來了~~~(灑花轉圈圈
