### ISSUE TITLE
[Homework 4-2] 及格分數

### ISSUE THREAD

**Issue by organicguava** [coding-coworking-club/basic-python-fall-2021#3]
## 提交連結
https://judge.ccclub.io/status?myself=1&page=1#:~:text=17%3A57%3A40-,b6bf46134d13,-Wrong%20Answer

## 程式碼

```python
n=int(input())
if n<0 or n>100:
    print('Error')
elif 0=<n<60:
    print('Fail')
else:
    print('Pass')

```

## 問題描述
不知道哪裡有問題

**Comment by ChangLynn** [comment]
第四行 elif  0<=n<60 才對

**Comment by lazyYC** [comment]
@organicguava 還是小提醒一下，problem 的題目不是用 homework 標籤唷
