### ISSUE TITLE
[Homework 3] 合法數獨

### ISSUE THREAD

**Issue by lzydaphne** [coding-coworking-club/basic-python-fall-2021#300]
## 提交連結

https://pasteio.com/xVXO3WY4VKsQ

## 程式碼

```python
nums=[]
# 計算每個數字的數量
constRow = [0,0,0,0,0,0,0,0,0,0]
constCol = [0,0,0,0,0,0,0,0,0,0]
const = [0,0,0,0,0,0,0,0,0,0]
#用來檢查宮的中心+四周元素
dx=[-1,-1,-1,0,0,0,1,1,1]
dy=[-1,0,1,-1,0,1,-1,0,1]


for i in range(9):
    temp = input()
    temp =  temp.split(',')
    for j in range(9):
      temp[j] = int(temp[j]) 
    nums.append(temp)

flag=0

# 檢查橫列
checkR=0
for j in range(9):
  constRow = [ 0 for n in range(10)]
  if flag != 0:
    break
  for k in range(9):
    if checkR==0:
      constRow[ nums[j][k] ] +=1
      if constRow[ nums[j][k] ] > 1 & nums[j][k]!=0:
        checkR=1
    if checkR==1:
      flag = 1
      break


# 檢查直行
checkC=0
for k in range(9):
  if flag != 0:
    break
  constCol = [ 0 for n in range(10)]

  for j in range(9):  
    if checkC==0:
      constCol[ nums[j][k] ] +=1
    if constCol[ nums[j][k] ] > 1 & nums[j][k]!=0:
      checkC=1
    if checkC==1:
      flag = 1
      break

# 檢查宮周圍
checkArea=0
for i in range(1,8,3):
  if flag!=0:
      break
  for j in range(1,8,3):
    # 每次換宮都會重新記錄
    const = [ 0 for n in range(10)]
    if flag!=0:
      break
    for b in range(9):
      if checkArea==0:
        const [ nums[ i+dx[b] ][ j+dy[b] ] ]+=1       
        if (const [ nums[ i+dx[b] ][ j+dy[b] ] ] > 1) & (nums[ i+dx[b] ][ j+dy[b] ]!=0):
          checkArea= 1      
          if checkArea==1:
            flag = 1
            break


if flag ==0 :
  print("True")
else: 
  print("False")
```

## 錯誤訊息
wa

## 問題描述

先簡單介紹解題的主要邏輯
1.先檢查橫列
2.在檢查直行
3.最後檢查宮的四周
三個檢查的方法，都是先用其他list紀錄出現過的數字次數
一旦除了0以外的數字出現超過1次以上，就會有flag標記為1，並跳出迴圈，最後print出false

測資都過了但是一直得到wa，希望助教幫忙看看哪裡沒考慮周到

**Comment by TJ72** [comment]
如果我沒有理解錯的話，妳在檢查直行、橫列和九宮的判斷中，是用`constCol`、`constRow`和`const`三個 10 個元素的串列儲存數字出現的次數，但看起來妳好像連數字 0 也有加入合法性的討論；但這題不用考慮數字 0 是否重複，只需要根據題目的 3 個規則，判斷數字 1-9 是否有重複就可以了。

**Comment by lzydaphne** [comment]
您好，先感謝助教的回覆~

會考慮到數字 0 是否重複，是因為我的檢查方法會順便記錄到數字0出現的次數，
所以在寫條件時，會特別寫成 **「如果某個數字出現的次數超過1次，且此數字不等於0」**的樣子，就會判斷數字 1-9 是否有重複
如檢查橫列時:  `if constRow[ nums[j][k] ] > 1 & nums[j][k]!=0:`
檢查九宮時:`if (const [ nums[ i+dx[b] ][ j+dy[b] ] ] > 1) & (nums[ i+dx[b] ][ j+dy[b] ]!=0):`
所以照理來說應該是不會影響其他數字的判斷的，但不知道哪裡有問題，
再麻煩助教了，謝謝!

**Comment by TJ72** [comment]
喔喔～抱歉我沒有看到後面那個條件～

那看起來妳的 code 應該沒什麼問題，我印象沒錯的話， `&` 只有用在 set 和 dataframe，條件還是要用 `and` 才可以，我剛試著改這部分就可以 AC 了。

**Comment by lzydaphne** [comment]
> 喔喔～抱歉我沒有看到後面那個條件～
> 
> 那看起來妳的 code 應該沒什麼問題，我印象沒錯的話， `&` 只有用在 set 和 dataframe，條件還是要用 `and` 才可以，我剛試著改這部分就可以 AC 了。

了解!!!謝謝助教，已經通過了~
