### ISSUE TITLE
[Homework 3] 分配工作

### ISSUE THREAD

**Issue by garykhtw** [coding-coworking-club/basic-python-fall-2021#305]
## 提交連結

https://judge.ccclub.io/contest/80/problem/03

## 程式碼

```python

def cal(min_work, remove_data_list): #用finciton找出每個工作最低成本的員工
    min_work_num= [] #剩下尚未被選取的工作
    residul_list = [] #剩下尚未被選取工作的index
    for i in range( len(min_work) ):
        if i in remove_data_list:
            continue
        else:
            min_work_num.append (min_work[i])
            residul_list.append ( i )

    for i in range( len(min_work) ):
        if min_work[i] == min(min_work_num) and min_work [i] in min_work_num and  i in residul_list: 
            # 如果該工作的最低成本值有在尚未被選取的工作表中，且index也在表中，則輸出該index
            return i
            break

    
staff_num = int(input()) #有幾位員工
data_list = [] #輸入數據整理成一個list
for i in range(staff_num): #有幾個員工，輸入幾次input數值
    data_list += [int(num) for num in input().split(",")] 

add = 0
for i in range (staff_num): #將data_list，整理成同一工作下，不同員工的效率list
    initial = 0 + add
    globals () ['work_' + str(i)] = []
    for j in range (staff_num):
        globals () ['work_' + str(i)].append ( data_list [initial] ) #例如 work_0 = [7,6,6]
        initial += staff_num
    add += 1

    
remove_list = [] #哪個工作被幾號員工拿走後，會記錄成一個表
final_list = [] # 最後整理成一個表格 (員工編號，第幾項工作)
total_cost = 0 #總成本

for i in range (staff_num):
    globals () ['min_work_' + str(i)] = cal( globals() ['work_' + str(i)], remove_list )
    remove_list.append (globals () ['min_work_' + str(i)])
    total_cost += globals() ['work_' + str(i)][globals () ['min_work_' + str(i)]]
    final_list.append ((globals () ['min_work_' + str(i)],i)) #(第幾人，第幾項工作)
    final_list_sort = sorted (final_list) # 以員工編號排列
    
for i in range (staff_num):
    if i < (staff_num-1): #到最後一位員工之前，都有逗號隔開
        print (final_list_sort[i][1], end = ",")
    else:
        print (final_list_sort[i][1]) #最後一位員工直接印出
print (total_cost) #在第二行印出總成本


## 錯誤訊息

<!-- 若有錯誤訊息請提供截圖，若無則請留空。 -->
Wrong Answer

## 問題描述

<!-- 請盡量完整地敘述你的問題。 -->

測資都成功，我輸入自己設定的測驗資料，出來也是對的，請問助教，想知道是哪個環節錯誤了? 勞煩助教了。
如果上面聯結有問題，附上colab地址：
https://colab.research.google.com/drive/133sO-FceXHAPmIqAL3OLszFM9TaY7Wkp?usp=sharing

**Comment by jennifer090** [comment]
你可以試試看這筆
10
39,64,44,15,37,24,35,8,62,15
38,46,79,80,79,63,34,43,31,8
49,59,67,73,17,66,2,50,72,59
40,56,31,45,65,2,50,43,10,49
8,7,63,37,73,30,42,40,79,8
4,15,29,25,20,54,1,54,34,19
46,75,61,77,39,19,48,62,73,6
10,66,42,15,1,69,50,11,5,53
60,21,31,52,49,42,36,12,8,36
61,50,47,46,13,74,42,51,13,10

答案應該要是
7,0,2,5,1,6,9,4,8,3
184

ps 連結的格式盡量要貼對對助教來說會比較輕鬆喔 ，方法詳見 -學員需知 >> "GitHub Issue 使用教學"

**Comment by garykhtw** [comment]
助教你好，有個疑問，輸入你給的10項工作這題，第一件工作最低成本，要選第六個人(4)?。
目前用我寫的跑出來答案如下，這樣不是成本更低嗎?
3,9,6,2,1,0,5,4,7,8
112

**Comment by jennifer090** [comment]
題目有說，這是一個**折衷**的貪婪演算法，因此按照題目的規則去計算其實不是最佳解，只是近似最佳解而已。
然後你你寫的方法應該也不是最佳解，因為在其他筆測資中，你程式算出總成本會大於測資的總成本，因此還是要回歸題意解題才能AC 喔。
你可以試試看這個
10
7,36,18,31,39,24,25,40,35,17
11,13,16,1,38,23,28,15,32,2
1,22,29,24,32,22,6,35,35,26
23,4,33,10,26,11,38,31,30,23
11,36,14,1,21,25,14,13,21,13
7,27,14,34,10,28,32,7,25,40
28,3,24,7,40,4,23,39,29,3
11,19,4,18,28,18,10,35,18,10
2,17,31,4,24,4,21,32,30,9
25,8,40,21,19,20,37,25,25,17

正確應該是
6,3,0,8,9,7,1,2,5,4
107
你程式算出的總成本是 109

**Comment by garykhtw** [comment]
助教你好，用我的程式跑出來是109，序列是**9**,3,0,8,**6**,**4**,1,2,5,**7** (系統是 6,3,0,8,9,7,1,2,5,4)。
我用excel，列出兩者的差異，發現我的程式是依照第一份工作給最低成本，依此累推。所以我第五工作是給第六人，跟judge的第九人不同。也造成總成本不同。

那題目整體思考應該是往隨機挑個工作，然後找當下最低成本員工的方式嗎?

**Comment by jennifer090** [comment]
你把你自己的做法分析得很好!題目的解法的確與你原先想的是不同的
是要直接找**剩下的工作與工人中成本最小**的，而非從第一份工作來找最低成本


以一個簡單的例子來說明提意，假設題目為
3
7,3,2
3,2,1
3,4,7

首先先找出成本最小，成本最小的是1
3
7,3,2
3,2,1
3,4,7
所以第1位工人已經拿到工作了，除此之外第2份工作也不能做了

RESULT (打叉代表已經不能選了，看都不用看了):
3
7,3,X
X,X,X
3,4,X

再來繼續找出剩餘個工作與工人中成本最小的，目前看起來是3，但是3有兩個要選哪一個?
依照題目的規定，若成本平手則選i+j 最小，如果還是平手則選i 較小，所以最後選的是
7,**3,**X
X,X,X
3,4,X
因此第0位工人拿到的是第1份工作

RESULT

X,X,X
X,X,X
3,X,X

最後一個第2位工人就沒得選拉，只剩下第0份工作

所以答案會是
1,2,0
7

但是如果是按照工作順序來選的話就會變成
1,0,2
13
首先我先從第一份工作的成本中挑最小[7,3,3]，所以是第1位員工獲得第0份工作
再來是第二份工作[3,X,4] 因為第一位已經挑過了，所以我不能選，剩下的人中第0位員工似乎成本最低，所以我給他第1份工作，而第2位員工剩下第2份工作..到這邊應該可以看出來，這兩種做法最後取出來的順序及成本會不同吧，希望有回答到你的問題～

**Comment by garykhtw** [comment]
助教你好，我重新寫一個程式，我把兩個10員工的測驗跑一次，都吻合答案。但目前反而出現runtime error，請問runtime error代表我的程式全部是錯的嗎?

目前新的code，思考模式如下:將全部資料輸入成一維list。在排列一維list。最小成本值以enumerate 找出list中，最小值的全部index。index // 員工數 是 第幾號員工， index % 員工數 是第幾份工作。找出來後就加入標記的list中，下一輪的值，如果index在標記list中則跳過。依次跑全部100個成本值。

**Comment by garykhtw** [comment]
助教你好，我重新寫一個程式，我把兩個10員工的測驗跑一次，都吻合答案。但目前反而出現runtime error，請問runtime error代表我的程式全部是錯的嗎?

目前新的code，思考模式如下:將全部資料輸入成一維list。在排列一維list。最小成本值以enumerate 找出list中，最小值的全部index。index // 員工數 是 第幾號員工， index % 員工數 是第幾份工作。找出來後就加入標記的list中，下一輪的值，如果index在標記list中則跳過。依次跑全部100個成本值。

**Comment by garykhtw** [comment]
我找出問題了，目前用新的code就可以了，感謝助教協助理解。
