### ISSUE TITLE
[Homework 3] 分配工作

### ISSUE THREAD

**Issue by hongmingcomtw** [coding-coworking-club/basic-python-fall-2021#306]
## 提交連結

https://judge.ccclub.io/status/bd5aa6fb1851b0d47aa66bdab5419c5e

## 程式碼

  dim=int(input())
  Cij =  [""] * dim
  ans = [999] * dim
  for i in range(dim):
      Cij[i] = input().split(",")
  temp_i = 9999999999999
  temp_j = 9999999999999
  remove_i = []
  remove_j = []
  Cost = 0
  for t in range(dim): #最小值判斷次數與員工數相同
      All_num = []
      smallest = 9999999999999
  
      for i in range(dim):  #找觀察數中最小值minimum
          for j in range(dim):
              if i not in remove_i and j not in remove_j: 
                  All_num.append(Cij[i][j])
          All_num = list(map(int,All_num))
      minimum = min(All_num)
      
      for i in range(dim):  #找minimum的位置 且 符合 i+j 最小 & i+j 相同時看 i 小者
          for j in range(dim):
              if int(Cij[i][j]) == minimum and i not in remove_i and j not in remove_j:
                  s = i + j
                  if s < smallest or (s == smallest and i < temp_i):
                      smallest = s
                      temp_i = i
                      temp_j = j
      remove_i.append(temp_i)      #儲存已排除的i
      remove_j.append(temp_j)      #儲存已排除的j
      ans[temp_i] = temp_j
      Cost += int(Cij[temp_i][temp_j])
  print(ans)
  print(Cost)

## 錯誤訊息

WA

## 問題描述

測資沒問題，但WA..

想法是依小明的演算法找所有數字中最小值，找到後排除該行該列再繼續找剩下數字中最小值，持續判斷dim次(dim = 員工數)，想請問是不是哪裏沒想對？麻煩助教了！

**Comment by jennifer090** [comment]
提問的格式不對喔，正確格式請詳見-學員需知裡的 "GitHub Issue 使用教學"
