### ISSUE TITLE
[Homework 3]分配工作

### ISSUE THREAD

**Issue by secondbase56** [coding-coworking-club/basic-python-fall-2021#310]
## 提交連結

https://judge.ccclub.io/status/c3a089ae7966c498ed6c5619f6d2d966
## 程式碼

```python
job = int(input())      #紀錄總工作數
cost_dict = {}      #紀錄每位員工的順序與成本，存成字典
num = 0
while num < job:
    cost = [int(i) for i in input().split(",")]
    cost_dict.update({num:cost})
    num += 1

    
lc_list = []      #lowestcost的list
staff_dict = {}
for i in range(job):
    everycost = []      #把每個工作的成本存成第一位，順序存成第二位
    for j in cost_dict:      #j是cost_dict的key值
        everycost.append([cost_dict[j][i],j])
    lc = min(everycost)      #lc = lowestcost
    lc_list.append(lc[0])
    
    staff = min(everycost)[1]      #staff用來存取成本最低的員工
    staff_dict.update({staff:i})      #把最低成本工作的員工存成key，順序存成value
    del cost_dict[staff]


ans = []      #紀錄每位員工工作順序
for k in sorted(staff_dict):      #把staff_dict按照員工排序
    ans.append(str(staff_dict[k]))
ans = ",".join(ans)
print(ans)
print(sum(lc_list))
![messageImage_1636969201060](https://user-images.githubusercontent.com/91279588/141759490-d4bf9c23-ab49-41a5-8b5d-e1264353142f.jpg)
```

## 問題描述

助教你好，我的程式碼在JN上可以執行，但在judge上顯示WA，請問是不是有其他測資沒注意

**Comment by jennifer090** [comment]
如果我沒理解錯的話，你是依照工作順序再來才是成本在選工作及員工的，建議你可以參考 #291，他跟你類似但他是依照員工順序再來才看成本，題目的意思是先直接找**cij最小的**。如果我有理解錯或你看291還是不太理解的話再麻煩回覆我～

**Comment by secondbase56** [comment]
助教不好意思我看了#305的10行例題，有點不懂例題的邏輯，像是第0個工作第1位員工成本是38，但第5為員工成本只有4，為什麼不是選第5位員工，照例題的答案成本就不會是最低了QQ

**Comment by secondbase56** [comment]
![image](https://user-images.githubusercontent.com/91279588/141884154-f75094f1-2031-4633-b454-56de2bb6cabf.png)
這是我的答案

**Comment by jennifer090** [comment]
首先，題目有說，這是一個折衷的貪婪演算法，因此按照題目的規則去計算其實不是最佳解，只是近似最佳解而已。
至於題意的部分，以一個簡單的例子來說明，假設題目為
3
7,3,2
3,2,1
3,4,7

首先先找出成本最小，成本最小的是1
3
7,3,2
3,2,**1**
3,4,7
所以第1位工人已經拿到工作了，除此之外第2份工作也不能做了

RESULT (打叉代表已經不能選了，看都不用看了):
3
7,3,X
X,X,X
3,4,X

再來繼續找出剩餘個工作與工人中成本最小的，目前看起來是3，但是3有兩個要選哪一個?
依照題目的規定，若成本平手則選i+j 最小，如果還是平手則選i 較小，所以最後選的是
7,**3,**X
X,X,X
3,4,X
因此第0位工人拿到的是第1份工作

RESULT

X,X,X
X,X,X
3,X,X

最後一個第2位工人就沒得選拉，只剩下第0份工作

所以答案會是
1,2,0
7

`但是如果是按照工作順序來選的話就會變成`
1,0,2
13
首先我先從第一份工作的成本中挑最小[7,**3**,3]，所以是第1位員工獲得第0份工作
再來是第二份工作[3,X,4] 因為第一位已經挑過了，所以我不能選，剩下的人中第0位員工似乎成本最低，所以我給他第1份工作，而第2位員工剩下第2份工作..到這邊應該可以看出來，這兩種做法最後取出來的順序及成本會不同吧，希望有回答到你的問題～
