### ISSUE TITLE
[General] 天數相差

### ISSUE THREAD

**Issue by minminLu** [coding-coworking-club/basic-python-fall-2021#314]
## 提交連結
https://judge.ccclub.io/status/61982a90c3d31fd8468d08871d37fbb4

## 程式碼

```python
import datetime
d1 = datetime.datetime.strptime(input(), '%Y %m %d')
d2 = datetime.datetime.strptime(input(), '%Y %m %d')
diff = d2 - d1
print(abs(diff.days))
```

## 錯誤訊息

![擷取](https://user-images.githubusercontent.com/64120193/141891492-7841de84-cbd1-43b8-8642-fdf1f2eed7be.JPG)

## 問題描述

測資皆對，但不知道問題是在哪裡，再麻煩助教指點謝謝!

**Comment by waukin** [comment]
你的寫法如果當輸入西元日期 < 1000年會出錯
例如：輸入 999 1 1
會發生 `ValueError: time data '999 1 1' does not match format '%Y %m %d'`

**Comment by minminLu** [comment]
好的，謝謝助教，我有修正成以下程式碼，想說如果西元不滿四位數用0填滿到四位數，但是是Wrong answer，不知道是什麼情況沒考慮到，再麻煩助教指點，謝謝!
```
import datetime
d1_lst = input().split()
d2_lst = input().split()
 
d1_lst[0] = d1_lst[0].zfill(4)
d2_lst[0] = d2_lst[0].zfill(4)

d1_str = " ".join(d1_lst)
d2_str = " ".join(d2_lst)

d1 = datetime.datetime.strptime(d1_str, '%Y %m %d')
d2 = datetime.datetime.strptime(d2_str, '%Y %m %d')
diff = d2 - d1
print(abs(diff.days))
```

**Comment by waukin** [comment]
咦？
我用你更新後的程式碼可以順利 `Accepted` 
妳要不要重新提交答案試試看
或是你可以把提交連接附上來
我再幫你檢查哪裡發生問題

**Comment by minminLu** [comment]
🤣對! 重新提交之後ac了! 謝謝助教
