### ISSUE TITLE
[Homework 3] 分配工作

### ISSUE THREAD

**Issue by Angela-Chu** [coding-coworking-club/basic-python-fall-2021#318]
## 提交連結
https://judge.ccclub.io/status/e7b6cd21d0f66757573c8fd958922b42

## 程式碼

```python
# 輸入總共的員工數
total_man = int(input())

person = [False] * total_man  # 總共有n個員工，目前都還未認領工作，先預設為False
answer = [0] * total_man  #答案清單，預設空位有n個
total_cost = 0 # 紀錄總成本

job_detail = [] # 儲存紀錄每人做每件工作的成本
for k in range(total_man): 
    job_detail.append(list(map(int,input().split(",")))) 
    
for j in range(total_man): # 依序檢查每一項工作應分配給誰
    min_cost = 100 ** 100 # 預設該項工作的最低成本為一個很大的數值
    person_chosen = 0 # 預設要做該項工作的人為第0人
    for i in range(total_man): # 依序檢查每一位員工做該項工作的成本
        if person[i] is False: # 若該員工尚未認領工作就檢查他的成本是否低於目前這項工作的最低成本
            if job_detail[i][j] < min_cost: 
                min_cost = job_detail[i][j]  # 若該員工所需花費的成本低於目前這項工作的最低成本，更新最低成本。這邊不考慮相等的情況，因為若相等就直接選較小的員工編號，不用重複考慮
                person_chosen = i # 將該員工先記錄為此項工作的認領者
            else:  # 若該員工已經認領工作，直接跳到下一個員工
                continue
    total_cost += min_cost # 將該項工作的成本與其他工作的成本加起來
    person[person_chosen] = True  # 將獲得工作的員工改為True
    answer[person_chosen] = j # 將答案清單更新
# 以上的迴圈因為每一次都是檢查同一項工作( j 會相同)，因此沒有額外檢查 i + j 的大小， 再加上都是從較小的員工編號開始檢查， 因此不需要再比較 i 的大小

# 列印出答案            
for job in range(len(answer)):
    if job == len(answer) - 1:
        print(answer[job])
    else:
        print(answer[job], end = ",")
print(total_cost)
```

## 錯誤訊息
Wrong Answer
Time: 68ms  Memory: 8MB  Lang: Python3  Author: angelachu1598753@gmail.com

## 問題描述

有參考了 #305 的解釋，但在助教提供的額外兩個測資中，
第一個我的答案也是:
3,9,6,2,1,0,5,4,7,8
112
第二個我的答案也是:
9,3,0,8,6,4,1,2,5,7
109

想請問助教在第一個測資中:
10
39,64,44,15,37,24,35,8,62,15
38,46,79,80,79,63,34,43,31,8
49,59,67,73,17,66,2,50,72,59
40,56,31,45,65,2,50,43,10,49
8,7,63,37,73,30,42,40,79,8
4,15,29,25,20,54,1,54,34,19
46,75,61,77,39,19,48,62,73,6
10,66,42,15,1,69,50,11,5,53
60,21,31,52,49,42,36,12,8,36
61,50,47,46,13,74,42,51,13,10

正解:
7,0,2,5,1,6,9,4,8,3
184

若依照先選成本最小的來看，第0個工作為什麼不是分配給第6位員工，而是分配給第2位員工?

以及在第二個測資中:
10
7,36,18,31,39,24,25,40,35,17
11,13,16,1,38,23,28,15,32,2
1,22,29,24,32,22,6,35,35,26
23,4,33,10,26,11,38,31,30,23
11,36,14,1,21,25,14,13,21,13
7,27,14,34,10,28,32,7,25,40
28,3,24,7,40,4,23,39,29,3
11,19,4,18,28,18,10,35,18,10
2,17,31,4,24,4,21,32,30,9
25,8,40,21,19,20,37,25,25,17

正解:
6,3,0,8,9,7,1,2,5,4
107

若依照先選成本最小的來看，第4個工作為什麼不是分配給第6位員工，而是分配給第10位員工? 
7,36,18,31,39,24,25,40,35,17
11,13,16,**X**,38,23,28,15,32,2
**X**,22,29,24,32,22,6,35,35,26
23,4,33,10,26,11,38,31,30,23
11,36,14,1,21,25,14,13,21,13
7,27,14,34,**_10_**,28,32,7,25,40
28,**X**,24,7,40,4,23,39,29,3
11,19,**X**,18,28,18,10,35,18,10
2,17,31,4,24,4,21,32,30,9
25,8,40,21,**_19_**,20,37,25,25,17

### 以下為我的想法的過程:
**先找出第一個成本最小的(標粗字)**
7,36,18,31,39,24,25,40,35,17
11,13,16,1,38,23,28,15,32,2
**1**,22,29,24,32,22,6,35,35,26
23,4,33,10,26,11,38,31,30,23
11,36,14,1,21,25,14,13,21,13
7,27,14,34,10,28,32,7,25,40
28,3,24,7,40,4,23,39,29,3
11,19,4,18,28,18,10,35,18,10
2,17,31,4,24,4,21,32,30,9
25,8,40,21,19,20,37,25,25,17
**所以第0項工作給了第3位工人**

7,36,18,31,39,24,25,40,35,17
11,13,16,1,38,23,28,15,32,2
**X**,22,29,24,32,22,6,35,35,26
23,4,33,10,26,11,38,31,30,23
11,36,14,1,21,25,14,13,21,13
7,27,14,34,10,28,32,7,25,40
28,**3**,24,7,40,4,23,39,29,3
11,19,4,18,28,18,10,35,18,10
2,17,31,4,24,4,21,32,30,9
25,8,40,21,19,20,37,25,25,17
**再來第1項工作給了第7位工人**

7,36,18,31,39,24,25,40,35,17
11,13,16,1,38,23,28,15,32,2
**X**,22,29,24,32,22,6,35,35,26
23,4,33,10,26,11,38,31,30,23
11,36,14,1,21,25,14,13,21,13
7,27,14,34,10,28,32,7,25,40
28,**X**,24,7,40,4,23,39,29,3
11,19,**4**,18,28,18,10,35,18,10
2,17,31,4,24,4,21,32,30,9
25,8,40,21,19,20,37,25,25,17
**再來第2項工作給了第8位工人**

7,36,18,31,39,24,25,40,35,17
11,13,16,**1**,38,23,28,15,32,2
**X**,22,29,24,32,22,6,35,35,26
23,4,33,10,26,11,38,31,30,23
11,36,14,1,21,25,14,13,21,13
7,27,14,34,10,28,32,7,25,40
28,**X**,24,7,40,4,23,39,29,3
11,19,**X**,18,28,18,10,35,18,10
2,17,31,4,24,4,21,32,30,9
25,8,40,21,19,20,37,25,25,17
**再來第3項工作給了第2位工人**

7,36,18,31,39,24,25,40,35,17
11,13,16,**X**,38,23,28,15,32,2
**X**,22,29,24,32,22,6,35,35,26
23,4,33,10,26,11,38,31,30,23
11,36,14,1,21,25,14,13,21,13
7,27,14,34,**_10_**,28,32,7,25,40
28,**X**,24,7,40,4,23,39,29,3
11,19,**X**,18,28,18,10,35,18,10
2,17,31,4,24,4,21,32,30,9
25,8,40,21,**_19_**,20,37,25,25,17
**再來第4項工作給了第6位工人**
**這邊想請問為什麼正解是要將第4項工作給了第10位工人?**

**Comment by jennifer090** [comment]
你可以先參考 #310 一下～
