### ISSUE TITLE
[Homework #2] 又是喵球

### ISSUE THREAD

**Issue by ny88154** [coding-coworking-club/basic-python-fall-2021#32]
## 提交連結
https://judge.ccclub.io/contest/71/problem/05

## 程式碼

問題版:
```
s1=input()
s2=s1.upper()
s3=s1.lower()

for i in range(len(s1)):
    if ord(str(s2[i]))>=ord("N"):
        s2[i]=str(s3[i])
        
print(s2)

```

解決版:
```
s1=input()
s2=list(s1.upper())
s3=list(s1.lower())

for i in range(len(s1)):
    if ord(str(s2[i]))>=ord("N"):
        s2[i]=s3[i]
s=""
print(s.join(s2))
```

## 錯誤訊息
TypeError: 'str' object does not support item assignment

## 問題描述

想了解為什麼 s2[i]可以使用>>>表示已經被認定為串列?
但是要置換的時候 為何會出現錯誤訊息

**Comment by r05521230** [comment]
請先將程式碼的部分用適當的格式顯示(可參照學員須知內GitHub Issue 使用教學)
容易閱讀的格式可以幫助大家了解你的程式喔~

**Comment by lazyYC** [comment]
@ny88154 
string 跟 list 都可以使用 [] 作slicing，第一個做法的情況它還是 string 不是 list
