### ISSUE TITLE
[General] 有關list使用remove的問題

### ISSUE THREAD

**Issue by secondbase56** [coding-coworking-club/basic-python-fall-2021#323]
## 程式碼

a = [[7, [0, 0]], [6, [0, 1]], [7, [0, 2]], [6, [1, 0]], [7, [1, 1]], [6, [1, 2]], [2, [2, 0]], [2, [2, 1]], [2, [2, 2]]]
for i in a:
    if i[1][0] == 2:
        a.remove(i)
for i in a:
    if i[1][1] == 0:
        a.remove(i)
print(a)
```python

```

## 問題描述

助教你好，a是我隨意設的list有點像矩陣的概念，a_list的每個元素又是個list，其中第二碼為ij座標，我想利用for迴圈分別把i=2以及j=0的list移除。最後答案a_list應該要只剩下[[6, [0, 1]], [7, [0, 2]], [7, [1, 1]], [6, [1, 2]]]，但我算出來的結果是[[6, [0, 1]], [7, [0, 2]], [7, [1, 1]], [6, [1, 2]], [2, [2, 1]]]，[2, [2, 1]]這項無法移除，請問我哪邊出錯了。
<img width="724" alt="擷取" src="https://user-images.githubusercontent.com/91279588/142252140-9a6bb22a-7f15-49df-8c28-a9722f88fc42.PNG">

**Comment by SleeperShark** [comment]
這個跟for elem in list這項遞迴式究竟如何取list的裡面的值有關係。
其實他跟for idx in range(len(list)) 一樣，透過遞增的idx一個一個把值取出來，只是讓你偷懶、這部分偷偷由電腦代勞了。
我們來看他取值的過程:
```python
a = [[7,[0, 0]],    # 0
     [6, [0, 1]],   # 1
     [7, [0, 2]],   # 2
     [6, [1, 0]],   # 3
     [7, [1, 1]],   # 4
     [6, [1, 2]],   # 5
     [2, [2, 0]],   # 6
     [2, [2, 1]],   # 7
     [2, [2, 2]]]   # 8

for i in a:
    
    if i[1][0] == 2:
        print(i)
        print(a.index(i))
        a.remove(i)

'''
這是print出來的結果:
[2, [2, 0]]
6
[2, [2, 2]]
7
'''
```
首先，第一個被抓到的是 [2, [2, 0]],   # 6 這一項，所以我們看到他print出他的index、然後被刪除。
再來，他抓到的第二個是[2, [2, 2]]  #7 ......!!!!
奇怪，index 7 不是應該是[2, [2, 1]], ，上面那個是index 8 的元素啊!

其實背後的邏輯是醬子的:
當你把index 6 刪掉以後，整個list會變短，原本的idx 7 變成 idx 6，原本的idx 8 變idx 7；
但for elem in lst這個式子的規則，是每走一個迴圈，會遞增一次 idx，所以取完 6 以後，他理所當然下一個去取 7。
至於 **新的idx 6**  (也就是[2, [2, 1]],)這項，就直接被他忽略啦~

你可以用兩種方式確保所有的elem都被刪除:
1. 用while 迴圈，自己訂遞增的規則:
```python
idx = 0
while idx < len(a):
    if a[idx][1][0] == 2:
        a.remove(a[idx])
        # 如果刪掉元素，就不遞增idx
    # 沒刪元素，才遞增idx
    idx += 1
```

2. 用for迴圈，但從屁股開始看，就不會有刪掉元素後、影響到下一個元素讀取的情形
```python
for idx in range(len(a)-1, -1,-1):
    # 透過 8 ->  7 -> 6 這樣的順序, 即使刪除 8 也不影響 7 的讀取
    if a[idx][1][0] == 2:
        a.remove(a[idx])
```

大概4醬啦~

**Comment by secondbase56** [comment]
非常感謝助教
