### ISSUE TITLE
[Homework 3] 幾A幾B

### ISSUE THREAD

**Issue by Caesar0618** [coding-coworking-club/basic-python-fall-2021#326]
## 提交連結

https://judge.ccclub.io/status/71bc6d7464e89393df5e8bb48f0f9fed

## 程式碼

```python
ans = list(input()) #阿緯的正解
test = list(input()) #同學的回答

#首先先計算A(正解)的個數
A_count = 0
for i in range(len(ans)):
    if ans[i] == test[i]:
        A_count += 1

#建立正解字典，紀錄正解中每種數字的數量
ans_dict = {}
for num_ans in ans:
    count = ans.count(num_ans)
    ans_dict[num_ans] = count
print(ans_dict)
#計算A+B的總合個數
A_B_count = 0
test_dict = {}
for num_test in test:
    if num_test in ans_dict: #回答的數字有出現在正解字典，而且數量還有剩
        A_B_count += 1 #A+B總和增加、字典中該數字的數量改變
        test_dict[num_test] = test.count(num_test)
    elif num_test not in ans_dict:
        test_dict[num_test] = test.count(num_test)
print(A_B_count)
print(test_dict)

#計算B的個數
for n1, x1 in ans_dict.items():
    for n2, x2 in test_dict.items():
        if ans_dict[n1] == test_dict[n2]:
            B_count = A_B_count - A_count #計算出B的數量  
        elif test_dict[n2] > ans_dict[n1]:
            B_count = A_B_count - (test_dict[n2] - ans_dict[n1])
        elif ans_dict[n1] > test_dict[n2]:
            B_count = 0
print(B_count)
print(x2 - x1)
#印出答案
print(f"{A_count}A{B_count}B")
```

## 錯誤訊息

WA

## 問題描述

我利用題目上的測資都沒問題，可一直是Wrong Answer

**Comment by happywillie** [comment]
有幾個問題要解決：

1. 你的程式碼裡面有很多測試用的print，記得要把他們拿掉，不然你怎麼樣寫都會是WA

2. `A_B_count`的計算並不正確，可以試試（2221/1112）這組測資，正確的`A_B_count`是 2，但你現在算出來是 4。問題點應該在於，`if num_test in ans_dict: `的判斷式裡，你還沒有檢核數量是否有剩的問題。另外，如果`num_test`有在`ans_dict`裡面，而`ans_dict[num_test]`的數量也還有剩，除了`A_B_count += 1`以外，`ans_dict[num_test]` 的數量也要減少，才能避免重複計算的問題。

3. 因為`A_B_count = A_count + B_count `，如果你能正確計算`A_count`以及`A_B_count`，基本上就能得知`B_count`是多少了。（現在你`B_count`的計算有點太複雜）

**Comment by Caesar0618** [comment]
請問檢核數量是否有剩的問題，是表示ans_dict[num_test] 會多於test.count(num_test)的值嗎?

**Comment by happywillie** [comment]
不太是這個意思耶～以字典的解題方法來說，其實應該不會用到`test_dict`，也就沒有`test.count(num_test)`的問題了。

我舉個例子好了～以（1000/1111）的測資來說，`ans_dict[1] = 1`（數字1只有1個），所以當程式如果跑進` if num_test in ans_dict:`的判斷式時，除了`A_B_count += 1 `，也要進行`ans_dict[1] -= 1` 讓 `ans_dict[1]`變成0（數字1完全不剩了）。

所以說「檢核數量是否有剩」，指的是在判斷式裡，再加入`ans_dict[num_test] != 0`的條件式，避免`A_B_count`被重複計算。

**Comment by Caesar0618** [comment]
謝謝助教，我懂你的意思了，感謝!
