### ISSUE TITLE
[Week 7] 午餐吃什麼

### ISSUE THREAD

**Issue by 40743203S** [coding-coworking-club/basic-python-fall-2021#329]
## 提交連結

https://judge.ccclub.io/status/f7bae703bf25179521af55c377e0cff6
## 程式碼

```python
import random
random.seed(942)
n = int(input())
meals = {}
if n > 0:
    for i in range(n):
        shop, *food = input().split()  # 第一項訂為店家，其餘為食物
        meals[shop] = food            # 用字典裝起來
    shop = random.choice(list(meals))
    food = random.choice(meals[shop])
    print(shop, food)
#     print(random.choice(list(meals)), random.choice(meals[shop]))
else:
    print("吃空氣")
```

## 問題描述

助教我是AC的，但想請問助教註解的這行(倒數第三行) "print(random.choice(list(meals)), random.choice(meals[shop]))"  印出的結果和上面有使用assign的三行一樣，但卻不是AC，請問這兩者的差別在哪裡，謝謝助教！

**Comment by siddwang827** [comment]
如果你不用賦值的方法重設變數shop，直接省略9-11行，
你的food都會是從meals中最後一個shop裡面挑選的food哦，
後面的食物並沒有被前面的餐廳限定

**Comment by 40743203S** [comment]
意思是雖然在這題測資有過，但換其他隨機種子就不一定一樣了嗎？
(我以為只要符合題目上的隨機種子就可以了

**Comment by RayZhao0310** [comment]
你shop最後的值會變成「最後一間店家」，所以要取random.choice(meals[shop])的時候只會在最後一家餐廳的菜單取，就不符合題意了。

比如說如果有三家餐廳，依序是Subway、丹丹、麥當勞，for迴圈跑完會讓shop是麥當勞。
random.choice(list(meals))會取到丹丹, random.choice(meals[shop])卻會在麥當勞取。

**Comment by 40743203S** [comment]
了解！！  辛苦兩位助教了，十分感謝！
