### ISSUE TITLE
[General] pip3 失敗

### ISSUE THREAD

**Issue by sihci47** [coding-coworking-club/basic-python-fall-2021#334]
## 程式碼

```python

```

## 錯誤訊息

![1637307149810](https://user-images.githubusercontent.com/92390494/142583227-053ab12a-9949-4d23-af5d-8fe32c33fa93.jpg)

## 問題描述

我有下載新版的python，但是不知道為甚麼用command line 時會出現python27，現在電腦裡面好像有兩個python...，現在打pip3會出現NameError ，請問現在應該要怎麼辦呢?

**Comment by SleeperShark** [comment]
你這個是python 的執行檔，不是command line，請在cmd執行。
如果有pip3 的話，在執行介面打pip3會出現說明
![image](https://user-images.githubusercontent.com/88277367/142652392-5ce13c55-b900-441c-aebf-ec192010534c.png)

在windows的開始搜尋處打cmd就找的到，是蘋果的話google一下apple cmd應該也有說明，去試試看吧!

**Comment by sihci47** [comment]
有我看到了 ! 謝謝助教~
