### ISSUE TITLE
[Week 7] 字母麥片

### ISSUE THREAD

**Issue by shannon-chou** [coding-coworking-club/basic-python-fall-2021#336]
## 提交連結

https://judge.ccclub.io/status/b8a4c8ac01535cb644614befed7783f2

## 程式碼

```python
alph = [str(n) for n in input().split(",")]
ans = []

for i in alph:
    if alph.count(i) == 1:
        ans.append(i)

print(",".join(ans))
```

## 錯誤訊息

Time Limit Exceeded

## 問題描述

Jupyter上正確
Judge上TLE

**Comment by HansHiroshima** [comment]
應該是因為用 for 太花時間了，改用 dict 試試看

**Comment by TJ72** [comment]
謝謝同學的回答，這邊再稍微詳述一下 TLE 的原因和可能的解決方法。

TLE 的原因：
1. 在第一行 `alph = [str(n) for n in input().split(",")]`，其實 input().split() 本身就會將分割好的元素用字串的形式存在串列中，所以其實可以不用 list comprehension 再將元素轉成 str，這樣可能在執行程式碼時可以稍微有效率一些。
2. 真正造成 TLE 的原因在 for-loop 找沒有重複麥片的過程，假設我們在第一行輸入的字母有 n 個的話，我們在迴圈中每次拿出 n 個中的其中一個，並用 `list.count(element)` 這個方法來找字母在串列中出現的次數；但其實每次 call `list.count(element)` 也是要遍歷一次串列，回傳那個字母出現的次數。所以當你跑完整個 for-loop 時，最壞的情況下你跑了 n^2 次的串列了！

可能的解決方法：
在 dictionary 或 set 中取用、刪改資料是非常有效率的，可以想想怎麼用 dictionary or set 增進程式的效率。
