### ISSUE TITLE
[week 7] 01 小華的抽籤程式

### ISSUE THREAD

**Issue by coolpig0422** [coding-coworking-club/basic-python-fall-2021#338]
## 提交連結

https://judge.ccclub.io/status/84424e7615659dedfa1afaa3dcf4ab6c

## 程式碼

#小華的抽籤程式
import random
a = random.randint(1, 1000000000)
b = random.randint(1, 1000000000)
c = random.randint(1, 10000)
s1 = [int(i) for i in input().split()]
r0 = s1[0]
for i in range(s1[1]):
    ri = ((a * r0) + b) % c
    r0 = ri
    print(ri)

```

## 錯誤訊息

<!-- 若有錯誤訊息請提供截圖，若無則請留空。 -->

## 問題描述

<!-- 請盡量完整地敘述你的問題。 -->


Wrong Answer
無法確認跟測資的答案相比是不是吻合
想不出來是錯在哪裡，謝謝

**Comment by waukin** [comment]
題目敘述有要求需要給定抽獎的隨機種子
可以在程式碼的開始定義 `random.seed(r0)` 
如此一來，和測資的答案應該就會相符了

**Comment by coolpig0422** [comment]
可以AC了，謝謝謝助教
