### ISSUE TITLE
[Week 7] 小華的抽籤程式

### ISSUE THREAD

**Issue by panda44967** [coding-coworking-club/basic-python-fall-2021#339]
## 提交連結

https://judge.ccclub.io/contest/66/problem/01
## 程式碼

```python
import random
r0, people = [int(i) for i in input().split()] #int(i) for i in input().split()
random.seed(r0) # random.seed()
a=random.randint(1, 1000000000)
b=random.randint(1, 1000000000)
c=random.randint(1, 10000)
for i in range(0,people):
    r=(a*r0+b)%c
    r0=r
    print(r)
```

## 問題描述

1. 想請問第二行[int(i) for i in input().split( )] ，最外面不加[ ] 差異在哪呢?
發現要加[ ] 才會AC，但不懂差在哪裡
而且 r0, people= input().split() 也OK 但最外面也不用加[ ]呀?
2. random.seed(r0) # random.seed() 加不加r0 在括號裡的差異在哪呢? 
謝謝~~

**Comment by siddwang827** [comment]
1. 這個是list comprehension 的標準語法，之前上課有教過哦，不熟悉可以自行google一下使用方法。
2. 如果random.seed()括號中指定種子，每次的random產生的值就會是假隨機，受指定的種子影響，反之不指定，則產生的值將會是隨機數(每次執行都不同)，可以自己測試看看以下程式碼看output變化。
```
random.seed()
a = random.randint(1, 100)
print(a)

random.seed(2)
b = random.randint(1, 100)
print(b)
```

**Comment by panda44967** [comment]
好喔 我再研究一下 謝謝解說:)
