### ISSUE TITLE
[Homework 4] 文句處理

### ISSUE THREAD

**Issue by KyleChou123** [coding-coworking-club/basic-python-fall-2021#344]
## 提交連結

https://judge.ccclub.io/status/7b57fc3de76e9716b894a7da98b24642

## 程式碼

```python
keywords = input().split() #讀取關鍵字
keywords.sort(reverse = True, key = len) #關鍵字由長到短排序 

end = False #不定行輸入 
contents = []
while end == False:
    tmp = input()
    if tmp == "end":
        end = True
    else:
        contents.append(tmp) 

for i in range(len(contents)): #輸入的資料 一個一個讀進for迴圈中
    position_of_processed_data = [] #紀錄處理過的資料的位置範圍 (為了不讓已經加過括號的資料再次被加上括號)
    
    for keyword in keywords: #關鍵字 一個一個讀進for迴圈中

        position = 0 #關鍵字在資料中的位置
        length_of_keyword = 0 #關鍵字的長度
        position = contents[i].find(keyword,position) #使用find函式找出關鍵字的位置 存入position 

        while position != -1: #當find函式回傳-1(找不到更多關鍵字)時 while停止運作

            length_of_keyword = len(keyword) #找出關鍵字長度

            flag = False #如果關鍵字的位置在過去處理過的資料的位置範圍時 跳過加括號的處理
            for j in range(len(position_of_processed_data)):
                if position > position_of_processed_data[j][0] and position < position_of_processed_data[j][1]:
                    flag = True #

            if flag == True:
                pass

            else:
                contents[i] = list(contents[i]) #將資料轉為列表
                contents[i].insert(position,"「") #在關鍵字位置的開頭插入括號
                contents[i].insert(position + length_of_keyword + 1, "」") #在關鍵字位置的結尾插入括號
                contents[i] = "".join(contents[i]) #將資料轉回字串

                position_of_processed_data.append([position, position + length_of_keyword + 1]) #紀錄處理過的資料的位置範圍

            position = position + length_of_keyword #為了讓find函式繼續運作 更新position
            position = contents[i].find(keyword,position) #尋找下一個關鍵字
    print(contents[i])
```

## 問題描述

judge的3個測資 和自己設計的測資都沒問題
judge給WA 想麻煩助教幫忙看一下問題出在哪 謝謝

**Comment by david31009** [comment]
我不是助教~~~
但我剛剛測試了我自己設計的測資，如果關鍵字是加在另一個較長的關鍵字後面，會有問題~~
希望對你有幫助

輸入
apple applepen pen pineapple pineapplepen cute
I have an cute apple app in pineapplepen ohhh
my pineapple pen is cute and I want an applepen yess
you are so cute but you need an apple and a cute applepen AC
end

輸出
I have an 「cute」 「apple」 app in 「pineapple「pen」」 ohhh
my 「pineapple」 「pen」 is 「cute」 and I want an 「apple「pen」」 yess
you are so 「cute」 but you need an 「apple」 and a 「cute」 「apple「pen」」 AC

應為
I have an 「cute」 「apple」 app in 「pineapplepen」 ohhh
my 「pineapple」 「pen」 is 「cute」 and I want an 「applepen」 yess
you are so 「cute」 but you need an 「apple」 and a 「cute」 「applepen」 AC

**Comment by SleeperShark** [comment]
上面那個同學講得沒錯歐，你的code會有kw重複取括號的狀況。
我想問題可能在這裡:
```python
position_of_processed_data.append([position, position + length_of_keyword + 1])
```
你以為你這樣就有紀錄到每次括號的地點了，但是有一個問題是，如果今天第一個kw 在 index 20這個地方打了一組括號，第二個kw在index 10 這裡打了一組括號，這樣的話index 10 這邊就多差了兩組character(「+」)，你後面整個句子的index都會被往後移動，就失去你原本紀錄 index 20 的意義了。

推薦你一個動態搜索括號的想法: 
```python
while True:
    w_index = []
    for word in word_list:
        w_index.append(word, sentence.find(word))
        # 用這個list紀錄每個word出現的index

    # 選出index最前面的
    index_most_front, word = #?? 要怎麼取讓你自己思考一下
    new_sentence += sentence[: index_most_front] + '「' +  word +  '」'

    # 讓sentence從新的紀錄點開始
    sentence = sentence[index_most_front+len(word):]
    # 要記得設一個條件式，在甚麼情況下代表搜尋到盡頭了
```
    
透過這個寫法，你每找到一次kw，就把這一段加到new_sentence 上，舊的sentence則把這一段去掉、重新搜索kw，如此一來就不會有重複取到單字的狀況了。
先醬吧，有問題的話再說囉~

**Comment by KyleChou123** [comment]
> 



> 我不是助教~~~ 但我剛剛測試了我自己設計的測資，如果關鍵字是加在另一個較長的關鍵字後面，會有問題~~ 希望對你有幫助
> 
> 輸入 apple applepen pen pineapple pineapplepen cute I have an cute apple app in pineapplepen ohhh my pineapple pen is cute and I want an applepen yess you are so cute but you need an apple and a cute applepen AC end
> 
> 輸出 I have an 「cute」 「apple」 app in 「pineapple「pen」」 ohhh my 「pineapple」 「pen」 is 「cute」 and I want an 「apple「pen」」 yess you are so 「cute」 but you need an 「apple」 and a 「cute」 「apple「pen」」 AC
> 
> 應為 I have an 「cute」 「apple」 app in 「pineapplepen」 ohhh my 「pineapple」 「pen」 is 「cute」 and I want an 「applepen」 yess you are so 「cute」 but you need an 「apple」 and a 「cute」 「applepen」 AC

感謝同學設計的測資，還有幫忙找bug，改過之後AC了~謝謝！

**Comment by KyleChou123** [comment]
> 上面那個同學講得沒錯歐，你的code會有kw重複取括號的狀況。 我想問題可能在這裡:
> 
> ```python
> position_of_processed_data.append([position, position + length_of_keyword + 1])
> ```
> 
> 你以為你這樣就有紀錄到每次括號的地點了，但是有一個問題是，如果今天第一個kw 在 index 20這個地方打了一組括號，第二個kw在index 10 這裡打了一組括號，這樣的話index 10 這邊就多差了兩組character(「+」)，你後面整個句子的index都會被往後移動，就失去你原本紀錄 index 20 的意義了。
> 
> 推薦你一個動態搜索括號的想法:
> 
> ```python
> while True:
>     w_index = []
>     for word in word_list:
>         w_index.append(word, sentence.find(word))
>         # 用這個list紀錄每個word出現的index
> 
>     # 選出index最前面的
>     index_most_front, word = #?? 要怎麼取讓你自己思考一下
>     new_sentence += sentence[: index_most_front] + '「' +  word +  '」'
> 
>     # 讓sentence從新的紀錄點開始
>     sentence = sentence[index_most_front+len(word):]
>     # 要記得設一個條件式，在甚麼情況下代表搜尋到盡頭了
> ```
> 
> 透過這個寫法，你每找到一次kw，就把這一段加到new_sentence 上，舊的sentence則把這一段去掉、重新搜索kw，如此一來就不會有重複取到單字的狀況了。 先醬吧，有問題的話再說囉~

感謝助教指出我的問題，更改之後已經AC了~謝謝！
