### ISSUE TITLE
[General] Python beautifulsoup 使用失敗

### ISSUE THREAD

**Issue by kcAllenlin** [coding-coworking-club/basic-python-fall-2021#347]
## 程式碼

```python

```

## 錯誤訊息

![螢幕擷取畫面 2021-11-21 232359](https://user-images.githubusercontent.com/91825222/142768084-8cf9f8aa-da34-4ce2-8ade-2a89c7ce3ccd.png)

## 問題描述

我已將 requests 跟 beautifulsoup 都下載完成，但要使用beautifulsoup時會出現ModuleNotFoundError: No module named 'bs4'
想請教該如何解決此問題

**Comment by SleeperShark** [comment]
這可能跟你電腦裡有兩套python版本，你拿來下載bs4的版本跟你在運行.py檔時使用的python是不同版本的，在import模組時使用的資料夾不一樣造成的問題。
講起來有點囉嗦，畢竟每個人下載的IDE不一樣，你先看看下面連結的講解來操作，如果還是不行的話再說。
https://www.itread01.com/content/1542601567.html
