### ISSUE TITLE
5-1翻箱倒櫃

### ISSUE THREAD

**Issue by Joanuser** [coding-coworking-club/basic-python-fall-2021#35]
## 程式碼

```python

```

## 錯誤訊息

![擷取](https://user-images.githubusercontent.com/91591520/136149703-21eca8a4-4174-49fc-997c-20386a29e69c.PNG)

**Comment by huaitzu** [comment]
同學你好，請參照學員須知內的「[GitHub Issue 使用教學](https://ccclub.notion.site/GitHub-Issue-5a270fb3e09448e1a6012082d10eb3dc)」進行提問，以便助教們協助你喔～
