### ISSUE TITLE
[General] Python BeautifulSoup 以及 Requests 使用失敗

### ISSUE THREAD

**Issue by Angela-Chu** [coding-coworking-club/basic-python-fall-2021#350]
## 程式碼

```python
import requests
from bs4 import BeautifulSoup

re = requests.get("https://www.google.com/")
soup = BeautifulSoup(re.text, "html.parser")
print(soup.title)
```

## 錯誤訊息

Traceback (most recent call last):
  File "C:\Users\88693\Desktop\ccClub_Python_Code\ccClub\ccClub_web_crawl_1.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
## 問題描述

**一開始是用pip3 install beautifulsoup4 以及 pip3 install requests 安裝modules，但在嘗試執行以上程式碼時，一直出現ModuleNotFoundError**

**有在cmd中執行pip list，是有找到requests 和 beautifulsoup4**

**另外也有在cmd中執行pip show requests 和 pip show beautifulsoup4 ，會出現以下資訊:**
C:\Users\88693>pip show requests
Name: requests
Version: 2.26.0
Summary: Python HTTP for Humans.
Home-page: https://requests.readthedocs.io
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: c:\anaconda\lib\site-packages
Requires: certifi, charset-normalizer, idna, urllib3
Required-by: anaconda-client, anaconda-project, conda, conda-build, conda-repo-cli, jupyterlab-server, Sphinx

C:\Users\88693>pip show beautifulsoup4
Name: beautifulsoup4
Version: 4.10.0
Summary: Screen-scraping library
Home-page: http://www.crummy.com/software/BeautifulSoup/bs4/
Author: Leonard Richardson
Author-email: leonardr@segfault.org
License: MIT
Location: c:\anaconda\lib\site-packages
Requires: soupsieve
Required-by: conda-build

**再次執行pip3 install beautifulsoup4 以及 pip3 install requests時則會出現:**
C:\Users\88693>pip3 install requests
Requirement already satisfied: requests in c:\anaconda\lib\site-packages (2.26.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\anaconda\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\anaconda\lib\site-packages (from requests) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\anaconda\lib\site-packages (from requests) (1.26.6)

C:\Users\88693>pip3 install beautifulsoup4
Requirement already satisfied: beautifulsoup4 in c:\anaconda\lib\site-packages (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\anaconda\lib\site-packages (from beautifulsoup4) (2.2.1)

**也有參考 #347 時，想說可能是有兩套python，但試圖在python 2 安裝，用pip install beautifulsoup4 和 pip install requests時直接出現Error:**
ERROR: Could not find a version that satisfies the requirement BeautifulSoup (from versions: 3.2.0, 3.2.1, 3.2.2)
ERROR: No matching distribution found for BeautifulSoup

**另外 #347 提到可以直接在pycharm執行程式碼，但我是用notepad++ 以及cmd來執行程式，想請問以這樣的狀況要怎麼解決呢? 以及是否是因為我也有裝anaconda而產生錯誤?  謝謝助教!**

**Comment by SleeperShark** [comment]
兩套python指的是Anaconda裡自備的一套跟你可能在電腦裡還有一套自己下載的python，不是python3 跟python2的意思。

你可以看到cmd回復你說這兩個套件在這裡:  c:\anaconda\lib\site-packages，是Anaconda的directory。
這樣的話理論上你在jupyter notebook上是可以運行的，想先問你上面那串程式碼是在note上運行嗎?

**Comment by Angela-Chu** [comment]
在Jupyter Notebook 上面可以，但是因為平常習慣用notepad++ 以及cmd來執行程式，所以想請教一下說有沒有方法可以讓cmd也可以執行? 謝謝助教!

**Comment by SleeperShark** [comment]
首先你要知道，python import的模組其實也是.py檔案，所以你只要把目標檔案放到他搜索路徑(directory，也就是資料夾)，就可以import該模組。

你已有的套件在c:\anaconda\lib\site-packages裡，至於你cmd內的python，他模組路徑在哪裡?
在cmd裡運行python後，查看sys.path的內容:
![image](https://user-images.githubusercontent.com/88277367/142980781-2ebe157d-0096-49e6-8bce-0c39fa059204.png)

他就會顯示在你import模組時，他會去上述這些資料夾去搜索模組。
所以你把 c:\anaconda\lib\site-packages 裡面的目標.py檔案(ex: requests.py)複製到那些資料夾裡的 "其中一個"，理論上他就抓地到了。
為了方便管理，建議你就放在 Python\Python38\lib\site-packages 這個資料夾。
先試試看這樣能不能吧。

**Comment by Angela-Chu** [comment]
<img width="1128" alt="2021-11-24" src="https://user-images.githubusercontent.com/91383706/143060652-8e775419-ad97-46a3-a49a-66ca79232605.png">

已經把requests 相關的檔案都放到上述中其中一個資料夾(C:\anaconda\Lib\site-packages\win32\lib)，有試過把request的一整個資料夾複製過去，也有試過把requests 資料夾裡面的每一個.py檔案都複製過去，可是兩種方式都還是出現ModuleNotFoundError，想請問以這樣的狀況要怎麼解決呢? 或是助教會建議就直接改成在jupyter notebook上執行呢?

**Comment by SleeperShark** [comment]
嗯......你在幫我測兩件事:
目前要先確定你在運行cmd上的python到底是誰，你隨便寫一個.py檔案，裡面的內容就一樣把sys.path print出來，實驗看看是不是在cmd上執行 python的時候使用的是不同的python執行程式。

再來是你試一下在cmd執行python，直接import requests看看他會有什麼反應，如果不行的話他也會顯示module not found error，有的話他會沒反應。

**Comment by Angela-Chu** [comment]
<img width="1128" alt="2021-11-24 (1)" src="https://user-images.githubusercontent.com/91383706/143080061-023f562d-62d8-42c9-8a71-9eb4ae45cee8.png">

目前的結果為這樣子~

**但是我把requests 和 bs4 兩個檔案夾移到C:\Users\88693\AppData\Local\Programs\Python\Python39，之後再次嘗試執行以下程式碼**
```python
import requests
from bs4 import BeautifulSoup

re = requests.get("https://www.google.com/")
soup = BeautifulSoup(re.text, "html.parser")
print(soup.title)
```
這次會出現:
C:\Users\88693>C:\Users\88693\Desktop\ccClub_Python_Code\ccClub\ccClub_web_crawl_1.py
Traceback (most recent call last):
  File "C:\Users\88693\Desktop\ccClub_Python_Code\ccClub\ccClub_web_crawl_1.py", line 1, in <module>
    import requests
  File "C:\Users\88693\AppData\Local\Programs\Python\Python39\requests\__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'

**若只執行BeautifulSoup的部分**
```python
from bs4 import BeautifulSoup
```
則會出現:
C:\Users\88693>C:\Users\88693\Desktop\ccClub_Python_Code\ccClub\ccClub_web_crawl_1.py
C:\Users\88693\AppData\Local\Programs\Python\Python39\bs4\element.py:15: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
  warnings.warn(

麻煩助教解惑了QQ 謝謝!

**Comment by SleeperShark** [comment]
你幫我是兩件事:
1. 先把兩個module放到 lib/site-packages 這個資料夾，在嘗試運行一次檔案看看。

2. 如果這還是不行，刪掉你原本複製的module，去找你另一組python的pip在哪裡。
在cmd輸入dir /s *pip.exe *:
```
C:\Users\Martin Yu>dir /s *pip.exe*
 磁碟區 C 中的磁碟沒有標籤。
 磁碟區序號:  8E1A-FC71

 C:\Users\Martin Yu\AppData\Local\Programs\Python\Python38\Scripts 的目錄

2021/09/24  下午 05:30           106,381 pip.exe
               1 個檔案         106,381 位元組

 C:\Users\Martin Yu\PycharmProjects\My first\venv\Scripts 的目錄

2019/09/13  下午 02:49            74,752 pip.exe
               1 個檔案          74,752 位元組
```
他會顯示你的電腦裡叫pip.exe的檔案在哪裡，理論上你應該會有兩個，一個在anaconda的資料夾，一個在Local\Program\python的資料夾裡(從我的例子來看，應該是Scripts資料夾)。
你切換到那個資料夾以後，輸入 .\pip install requests，就可以指示電腦運行當前資料夾的pip.exe檔案，不會運行到anaconda的那一組。
輸入時記得斜線反斜線不要搞混了，windows系統是用 \ 。

**Comment by Angela-Chu** [comment]
<img width="1113" alt="2021-11-24 (3)" src="https://user-images.githubusercontent.com/91383706/143237494-62192579-6293-499b-830d-65f92ad2958a.png">

<img width="1068" alt="2021-11-24 (5)" src="https://user-images.githubusercontent.com/91383706/143239380-e33c30b5-07c9-480a-8e10-0b212adf7295.png">

電腦中顯示只有一個pip.exe 檔案，但把路徑切換到C:\Users\88693\AppData\Local\Programs\Python\Python39\Scripts 之後就可以順利運行了。不過還是出現UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
  warnings.warn(

想請問這個warning 需要理會嗎? 以及之後若想要安裝其他module，也都要手動將檔案夾從anaconda的資料夾，複製到Local\Program\python的資料夾裡嗎? 謝謝助教~~~

**Comment by SleeperShark** [comment]
你目前的 beautifulSoup 也是用這個方法install的嗎?

如果不是的話，刪掉你用複製過去的，像安裝requests一樣重新Install BeautifulSoup 一次再試試看。
如果已經是再這個folder安裝的，試試看pip install soupsieve 這個module看有什麼反映。

**Comment by Angela-Chu** [comment]
成功了! 超級感謝助教~~~
