### ISSUE TITLE
[Homework 4] 小仔解密碼

### ISSUE THREAD

**Issue by afudog91** [coding-coworking-club/basic-python-fall-2021#352]
## 提交連結

https://judge.ccclub.io/status/30836c9db7d9c6af14762dae06b21193
## 程式碼

```python
chr_num = {" " : " "}
for n in range(26):
    chr_num[chr(n + 97)] = n + 1
    chr_num[chr(n + 65)] = n + 1

article = input()
clean_article = ""
for ch in article:
    if ch not in chr_num.keys():
        continue
    else:
        clean_article += ch
word_lst = clean_article.split()

def odd_even(word):
    count_odd = 0
    count_even = 0
    for i in word:
        if word.index(i) % 2 != 0:
            count_even += ord(i)
        else:
            count_odd += ord(i)
    return (int(str(count_odd)[-2:]) , int(str(count_even)[-2:])*(-1) )

sort_lst = sorted(word_lst, key = odd_even)
last_3_word = sort_lst[-3]
count = 1
for j in last_3_word:
    count *= chr_num[j]

if len(str(count)) == 1:
    ans = "000"+str(count)
elif len(str(count)) == 2:
    ans = "00"+str(count)
elif len(str(count)) == 3:
    ans = "0"+str(count)
else:
    ans = str(count)[:4]
print(ans)
```

## 問題描述

思考方式:
1. 先創造一個 dict, 裡面裝  字母: 對應的編號(a -> 1, z->26, 大小寫皆相同) & " ":" " 
2. 分析英文文章，留下純英文字的字串，再把字串切開包進一個 list
3. 根據題意 設計 sort 的 key function :odd_even，(不確定是不是這裡出問題...)
4. 最後依照題意抓倒數第三個字，字母依序相乘，然後補"0"

題目的兩個sample input 測資都正確，但judge 是 Wrong Answer...
是否有甚麼極限狀況未考慮到?
請助教大大解惑 提示@@

**Comment by siddwang827** [comment]
你的問題應該釋出在
```python
def odd_even(word):
    count_odd = 0
    count_even = 0
    for i in word:
        if word.index(i) % 2 != 0:
            count_even += ord(i)
        else:
            count_odd += ord(i)
    return (int(str(count_odd)[-2:]) , int(str(count_even)[-2:])*(-1) )
```
這個函式裡面
你是利用word.index()這個方法來回傳該字母在word裡的index值，接著在判斷這個值是奇數或偶數，
但你可能沒考慮到如果這個word裡面有重複的字母，那他會回傳什麼index值呢？
如果你知道答案應該就能想到該怎麼避免這種情況了~

**Comment by afudog91** [comment]
謝謝助教 
成功 AC 了 好感動

**Comment by siddwang827** [comment]
恭喜恭喜~~
這題的需求其實是一個很好的機會來練習將所有的要求設計成一個一個的函數，然後把input依序執行你設計的函數，
這樣不僅可以訓練把函數的作到高內聚(只負責單一項功能)，避免牽動其他不必要的麻煩，debug的速度也會提升很多，
另外如果從事寫軟體業相關的工作，程式碼通常不是自己看得懂就好，後續的維護跟合作也很重要，
如果別人無法一目了然，就會浪費很多時間在溝通上，
所以有時間的話可以利用這題來挑戰一下自己，順便養成好習慣唷~

**Comment by afudog91** [comment]
有點抽象.... 可以舉例嗎? 或是可以參考助教的 code 嗎?  XD

**Comment by siddwang827** [comment]
這是我原本寫的虛擬碼參考，不過你可以發現其中有些函式並不只執行了一項功能，而是復合的功能，
用意是希望學員能觸類旁通XD
舉例:
函式一 我把split()也包在裡面了，這樣函式一就變成作了兩件事: 1.刪除符號 2.分割成list
函式二 其實還可以分得更細，把處理奇數位與處理偶數位分別定義為函式，然後用函式二來call這兩個函式
這樣在debug的時候就可以針對函式一個一個切開來測試，有時間可以好好培養這種習慣哦~

```python
def 函式一(字串):
    """功能:刪除符號+將各單字分割為串列"""

    刪除符號後的字串 = re.sub(符合的情況, 取代後的值, 輸入的字串)

    return 刪除符號後的字串.split()
```
```python
def 函式二(字串):
    """功能:奇數位ASCII值相加升序 and 偶數位ASCII值相加降序"""

    odd_case = 0
    even_case = 0	

    for i in range(len(字串)):
        if i % 2 == 0: 奇數情況:
	    odd_case += i的ASCII值
	else:
	    even_case += i的ASCII值

    return (odd_case取末兩位值, even_case取末兩位值)  #需考慮升降序分別處理情況
```
```python
def 函式三(串列):
      """倒數第三個字串加權相乘值，結果用0補足四位輸出"""
      
      pw = 1
      for i in 串列中倒數第三個值:
	  pw *= i對應的加權值
        
      if pw大於四位數:
	  return pw首四位數
      else:
	  return pw補0至四位數
```
```python
#主程式
文章 = input()
函式一處理後結果 = 函式一(文章)
函式二排序後結果 = sorted(經函式一處理後結果, key=函式二)
print(函式三(函式二排序後結果)
```

**Comment by afudog91** [comment]
! ! ! ! ! ! ! !
太 酷 了
非常感謝

**Comment by ricecake0329** [comment]
> 你的問題應該釋出在
> 
> ```python
> def odd_even(word):
>     count_odd = 0
>     count_even = 0
>     for i in word:
>         if word.index(i) % 2 != 0:
>             count_even += ord(i)
>         else:
>             count_odd += ord(i)
>     return (int(str(count_odd)[-2:]) , int(str(count_even)[-2:])*(-1) )
> ```
> 
> 這個函式裡面 你是利用word.index()這個方法來回傳該字母在word裡的index值，接著在判斷這個值是奇數或偶數， 但你可能沒考慮到如果這個word裡面有重複的字母，那他會回傳什麼index值呢？ 如果你知道答案應該就能想到該怎麼避免這種情況了~

不好意思助教，我想再了解一下有關這個提示的更多細節，碰巧看到這位同學的程式覺得很有趣，但是看不太懂這個提示，煩請助教再解釋一次，謝謝。

**Comment by siddwang827** [comment]
假設今天有兩個單字，我們分別要知道單字內各個字母的序號，
```python
word1 = apple
word2 = big
```
一般我們會用for loop去迭代他的單字長度，就可以依序得到index值
```python
for i in range(len(word1)):
    print(i)
for j in range(len(word2)):
    print(j)
```
那這位同學所使用的方法是迭代這個單字內的所有字母，再反查這個字母於單字內的index值
```python
for i in word1:
    print(word1.index(i)
for j in word2:
    print(word2.index(j)
```
你先可以執行一下這兩段程式碼看看差異是什麼，然後google一下string.index()這個方法的特性，
先去試試看~
