### ISSUE TITLE
[General] pip3與beautifulsoup套件安裝失敗

### ISSUE THREAD

**Issue by joyshiang** [coding-coworking-club/basic-python-fall-2021#355]
## 程式碼

```python
import requests
from bs4 import BeautifulSuop

url = "https://mail.ntu.edu.tw/owa/#path=/mail"
re = requests.get(url)

soup = BeautifulSoup(re,text, "html.parser")

print(soup)
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/91731774/143161000-9054b398-7b5c-47bd-9eb3-42beba50aefd.png)

## 問題描述

根據教學影片影片(影片連結:https://www.youtube.com/watch?v=X9iH08BxXXA) 的最後面安裝pip3與beautifulsoup套件，並嘗試印出soup(如上面程式碼)，但卻出現錯誤訊息。圖片中前兩段是安裝pip3與beautifulsoup時收到的回應，最後一段是執行程式碼時得到的錯誤訊息。想請問哪裡出錯了><

**Comment by SleeperShark** [comment]
這位同學，你typo了。
看一下你的Soup怎麼拼的。
