### ISSUE TITLE
[General] 綜合1-2：一奇多偶

### ISSUE THREAD

**Issue by chuhao** [coding-coworking-club/basic-python-fall-2021#36]
## 提交連結
https://judge.ccclub.io/status/1d76ec6860053d37ee4a3212514a791d

## 程式碼
```python
listA=input().split()
result=[]

 ### 輸入轉成 list int
for i in range (0,len(listA),1): 
    listA[i] = int(listA[i])

### 設立一個新的 list  為 唯一的值
for t in listA:       
    if t not in result:
        result.append(t)

 ###  判斷出現在 list 數字的次數      
for z in result:   
    if listA.count(z) % 2 == 1:
        print (z)



```

## 問題描述

1 在 Jupyter Notebook 上是可以輸入 sample 的題目輸出是沒有問題的，但是送到 Judge 得到的結果是 Time Limit Exceeded
想請問用什麼方法或是結構才能縮短運算的時間？

**Comment by waukin** [comment]
也許可以使用字典的資料格式去處理會比較方便
字典的key和其對應的value分別是數字、出現的次數
假設有一個串列 `[1, 2, 3, 2, 1, 1, 1, 3, 3, 3, 3]` 
產生的字典會是
`
dict = 
{
  1: 4,
  2: 2,
  3: 5
}
`
再去判斷 `dict` 這個字典哪一個數字出現的次數為奇數

**Comment by chuhao** [comment]
我依照你的建議改成用字典的方式做，計算出字典後再去做奇偶數的判定，但是這一次變成 wrong answer (WA)
## 提交連結
https://judge.ccclub.io/status/a33051b4125215e01e8877b864ec8dd1

## 程式碼
```python
listA = input()
result={}
temp=[]

## 建立比較列
for i in range (0,len(listA),1): 
    if listA[i] not in temp:
        temp.append(listA[i])

## 移除空格        
temp.remove(" ")

##建立字典
for t in temp:
    result[t] = 0   

## 計算出現次數並加入字典    
for tt in range (0,len(listA),1):
    if listA[tt] in temp:
        result[listA[tt]]= result[listA[tt]]+1

##判斷出現次數並輸出整數        
for jj in temp:
    if result[jj] % 2 == 1:
        print (int(jj))

**Comment by waukin** [comment]
這裡輸入串列中的元素不一定是個位數
例如這組input `1000 1000 1000`
因為有3組1000的數值
預期程式會輸出1000
但你的程式會輸出 
```
1
0
```

**Comment by chuhao** [comment]
我試了您的建議，發現從 WA 變成 Time Limit Exceeded 後來嘗試分段發現最花時間在建立比較列 的部份花了 1300 ms
所以我嘗試改寫不要建立比較表直接用原本的數列進行比較，最後花了 88ms 完成

## 提交連結
https://judge.ccclub.io/status/4b408f63a48c2c311da9a32ed16d16bf

謝謝你的指導
