### ISSUE TITLE
[Homework 4] 小仔解密碼

### ISSUE THREAD

**Issue by garykhtw** [coding-coworking-club/basic-python-fall-2021#361]
## 提交連結

https://judge.ccclub.io/contest/83/problem/03

## 程式碼

```python

```

## 問題描述

助教你好，問題看不太懂(每個單字的奇數位按照ascii排列，這句就看不太懂了)。

題目給定一篇由全英文組成的文章，請先將文章中全部的標點符號去除，再將文章中所有單字重新排序，排序規則為每個單字的奇數位依照 ascii code 編碼相加後，取數字的後兩碼由小排到大，如果數值相同，就以偶數位依照 ascii code 編碼相加，取數字的後兩碼由大排到小。完成排序後，取倒數第三個單字，把單字每個位元依照字母序每個相乘(a -> 1, z->26, 大小寫皆相同)，取得出來的數字的前四碼(不足四位，就在數字前面補 0)，即為大門的密碼

**Comment by siddwang827** [comment]
假設單字 a，取奇數位依照 ascii code 編碼相加後，取數字的後兩碼由小排到大
找到奇數位的字母a, p, e
```python
a = apple
#1 2 3 4 5
#a p p l e
```
取a p e 的 ascii code值相加 
```python
ascii_sum = 97 +112 + 101 = 310 
```
取相加後的值的後兩碼來比大小
```python
#310 - > 10
```
[ASCII碼請參照](https://zh.wikipedia.org/wiki/ASCII)
