### ISSUE TITLE
[Homework 02] 直角三角形

### ISSUE THREAD

**Issue by hrplt7** [coding-coworking-club/basic-python-fall-2021#37]
## 提交連結

https://judge.ccclub.io/status/8bf59dfe6d34ddc5c753f50d92ced259

## 程式碼

```python
c = int(input())
x = input().split(' ')
x = [int(i) for i in x]
x.append(c)
x.sort()

for a in range(x[0],x[1]+1) :
    b = (c**2 - a**2)**0.5  #c**2=a**2+b**2 移項開根號
    if x[2]**2 == b**2 + a**2:   #c**2=a**2 + b**2
        print("True")
        break
else:
    print("False")


```

## 錯誤訊息

Wrong Answer

## 問題描述

抱歉我實在想不出來我邏輯哪邊出問題了，爬過其他人的發問也把亂break的問題修好了，但是還是錯，我知道一定有哪裡我沒考慮到，但我想不出來了，抱歉。

**Comment by lazyYC** [comment]
@hrplt7 
```
for a in range(x[0],x[1]+1) :
    b = (c**2 - a**2)**0.5  #c**2=a**2+b**2 移項開根號
    if x[2]**2 == b**2 + a**2:   #c**2=a**2 + b**2
        print("True")
        break
```
用這個方法找出來的 b 可能不是整數

**Comment by hrplt7** [comment]
@lazyYC 

```python

c = int(input())
x = input().split(' ')
x = [int(i) for i in x]
x.append(c)
x.sort()

for a in range(x[0],x[1]+1) :
    b = (c**2 - a**2)**0.5 #c**2=a**2+b**2 移項開根號
    if type(b) != "complex" and type(b) != "float":
        if x[2]**2 == b**2 + a**2: #c**2=a**2 + b**2
            print("True")
            break
else:
    print("False")
  

```
 我有再增加B的數值條件判斷了 但還是錯QQ

**Comment by lazyYC** [comment]
> @lazyYC
> 
> ```python
> c = int(input())
> x = input().split(' ')
> x = [int(i) for i in x]
> x.append(c)
> x.sort()
> 
> for a in range(x[0],x[1]+1) :
>     b = (c**2 - a**2)**0.5 #c**2=a**2+b**2 移項開根號
>     if type(b) != "complex" and type(b) != "float":
>         if x[2]**2 == b**2 + a**2: #c**2=a**2 + b**2
>             print("True")
>             break
> else:
>     print("False")
>   
> ```
> 
> 我有再增加B的數值條件判斷了 但還是錯QQ

你可以在 Jupyter 上嘗試看看， 對一個整數作 ** 0.5，總是會得到 float，所以這樣也不行
另外就是你做了sort，但是 y & z 的範圍有可能超過 c ，這樣你的 x[2] 有可能不是長邊 c

可以用巢狀迴圈做做看比較直觀

**Comment by hrplt7** [comment]
```python
c = int(input())
x = input().split(' ')
x = [int(i) for i in x]

for a in range(x[0],x[1]+1):
    for b in range(x[0],x[1]+1):
        if c**2 == a**2 + b**2:
            print("True")
            break
        else:
            continue
    if c**2 == a**2 + b**2 :
        break
else:
    print("False")
```
我後面修改好了！ 但是測資也測了很多組 但還是wrong answer TT
想請問助教可以幫我看看有哪些我沒考慮到的情況嗎

**Comment by hrplt7** [comment]
我發現我少了一個 yz要先sort過 感謝助教們的hints
