### ISSUE TITLE
[Homework 4] 文句處理

### ISSUE THREAD

**Issue by normanchiang** [coding-coworking-club/basic-python-fall-2021#373]
## 提交連結

https://judge.ccclub.io/contest/83/problem/01

## 程式碼

    kw = input().split(' ')
    #重新排列key word
    kw.sort(key=lambda i: len(i),reverse=False)
    sentence = input()
    new_sen = ''
    while True:
        w_index = []
        for word in kw:
            w_index.append(sentence.find(word))
    # 用這個list紀錄每個word出現的index
    # 選出index最前面的
        for i in range(len(kw)):
            if (w_index[i] == min([n for n in w_index if n >= 0])):    
                pos = i
            
    #將加好外框的keyword和keyword前的文章加入new_sen 
        new_sen += sentence[: w_index[pos]]+'「'+ sentence[(w_index[pos]): w_index[pos]+len(kw[pos]) ] +'」'
    
    # 讓sentence從新的紀錄點開始繼續下一次的key word選擇
        sentence = sentence[w_index[pos]+len(kw[pos]):]
    #停止條件
        if sentence ==''and input()=='end':
            break

    print(new_sen)

```python

```

## 錯誤訊息

<img width="719" alt="截圖 2021-11-29 下午6 55 03" src="https://user-images.githubusercontent.com/22269933/143857698-4d015276-9774-4641-9714-f834a5f02dd0.png">

## 問題描述

前兩個測資都可以正常運作答案也都是對的,第三個測資只要輸入文章的部分就會出現ValueError: min() arg is an empty sequence試過很多方式結果都一樣,麻煩助教幫忙～感謝。

**Comment by SleeperShark** [comment]
你的程式有幾個問題: 
1. 你用來抓取sentence的 input 在迴圈裡設計的不太正確，這樣接你只會處理到第一個 sentence，可能要再思考一下。
2. 會出現 `min() arg is an empty sequence` 其實很簡單: 你沒有設想如果剩餘的句子裡已經沒有kw了，也就是w_index裡全部都是 -1 時，你該做甚麼來結束迴圈。
這個檢查應該是要優先於  `if (w_index[i] == min([n for n in w_index if n >= 0])):`    這個判斷式，否則就會造成error。

想一想該怎麼調整吧~

**Comment by normanchiang** [comment]
感謝助教有ＡＣ了～
