### ISSUE TITLE
[Homework 4] 統神端火鍋

### ISSUE THREAD

**Issue by JumpingBoar** [coding-coworking-club/basic-python-fall-2021#38]
## 提交連結

https://judge.ccclub.io/contest/71/submissions?myself=1&page=1&contestID=71&problemID=04#:~:text=10%3A02%3A01-,eb1c5ac822fd,-Wrong%20Answer

## 程式碼

price = input()
price_list = price.split(",")
int_price_list = list(map(int, price_list))
sorted_price_list = sorted(int_price_list)
sorted_price_list.reverse()
list_num = len(price_list)
a = 0
for i in range(list_num):
    if int_price_list[i] != sorted_price_list[i]:
        a = a + 1
if a != 0 :
    print("過來一下，你又端錯"+str(a)+"次了")

```python

```

## 問題描述

我在notebook裡執行成功，但judge不給過，我不知道甚麼原因

**Comment by jasonchen1125** [comment]
提醒您**提交連結部分的連結是錯誤的**並**請注意縮排問題**哦，細節請參考[github 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

題目並沒有說0次就不記錄哦~稍微修改一下就會過了！
使用jupyter notebook執行兩筆範例測資正確但judge錯誤的話，代表有些情況可能沒考慮到。
建議可以先自行想一些測資來找尋問題。
