### ISSUE TITLE
[Homework 5] 又是喵球

### ISSUE THREAD

**Issue by JumpingBoar** [coding-coworking-club/basic-python-fall-2021#39]
## 提交連結

https://judge.ccclub.io/status/8433658b1a7901dbfa07983340c19cca

## 程式碼

str = input()
list_str = list(str)

if all(i.isalpha() or i==' ' for i in list_str):
    ord_list_str = list(map(ord, list_str))
    alphabet = []
    for i in ord_list_str :
        if i > 77 and i <= 90 :
            i += 32
            alphabet.append(chr(i))
        elif i < 77:
            i += 0
            alphabet.append(chr(i))
        elif i > 110:
            i += 0
            alphabet.append(chr(i))
        elif i >= 97 and i <=109 :
            i -= 32
            alphabet.append(chr(i))
    for j in alphabet:
        print(j, end="")
else:
    print(False)

```python

```

## 問題描述

一樣在notebook可以順利執行，但judge說錯誤，可以提示我錯在哪嗎?謝謝

**Comment by jasonchen1125** [comment]
你的ASCII 編碼有兩個情況沒考慮到哦
可以檢查看看範圍是不是有數字被漏掉了，尤其是等於的部分

**Comment by JumpingBoar** [comment]
> ## 提交連結
> https://judge.ccclub.io/status/8433658b1a7901dbfa07983340c19cca
> 
> ## 程式碼
> str = input() list_str = list(str)
> 
> if all(i.isalpha() or i==' ' for i in list_str): ord_list_str = list(map(ord, list_str)) alphabet = [] for i in ord_list_str : if i > 77 and i <= 90 : i += 32 alphabet.append(chr(i)) elif i < 77: i += 0 alphabet.append(chr(i)) elif i > 110: i += 0 alphabet.append(chr(i)) elif i >= 97 and i <=109 : i -= 32 alphabet.append(chr(i)) for j in alphabet: print(j, end="") else: print(False)
> 
> ## 錯誤訊息
> ## 問題描述
> 一樣在notebook可以順利執行，但judge說錯誤，可以提示我錯在哪嗎?謝謝



> 你的ASCII 編碼有兩個情況沒考慮到哦 可以檢查看看範圍是不是有數字被漏掉了，尤其是等於的部分

我找到了，感謝提醒！
