### ISSUE TITLE
[General] Python程式碼問題

### ISSUE THREAD

**Issue by ChengbaiLee** [coding-coworking-club/basic-python-fall-2021#4]
## 程式碼

a = input()
b = input()
print("a + b")

## 問題描述

根據影片輸入完這個程式碼後系統會詢問我a, b分別是甚麼，但執行後都完全沒有反應直接進到下一行編輯，為什麼會這樣?

**Comment by linyuzz** [comment]
我也有一樣的問題！

**Comment by dennisc1213** [comment]
你用Jupyter 嗎？
程式碼寫完，要按上面的"播放"的箭頭，才會執行喔！

對了，你的print()內容，""中間會被當成純文字不會運算喔
