### ISSUE TITLE
[Homework 1-2] 直角三角形

### ISSUE THREAD

**Issue by MarsTsraM** [coding-coworking-club/basic-python-fall-2021#40]
## 提交連結

https://judge.ccclub.io/status/13be1c0a00ef5a3d2d27feeaecea59a8

10/11 Updated
https://judge.ccclub.io/status/3e5ccec4e477fd027eed10201f4be845

## 程式碼

```python

#Runtime error
triC = int(input())
triAB = str(input())
triRange = [ int(i) for i in triAB.split() ]


if c > min(triRange) and min(triRange) > 0: ###確認為正整數 且 第三邊C至少大於起算點
    
    ###把所有符合條件的整數都丟入List
    ###條件1:(c**2 - i**2)**0.5) 為整數
    ###條件2:(c**2 - i**2)**0.5) 小於等於 範圍上限 
    results = [ i for i in range(min(triRange),max(triRange)+1) if ((triC**2 - i**2)**0.5).is_integer()  and int((triC**2 - i**2)**0.5) <= max(triRange) ]

    ###print (results) ###驗證用
    print (int(len(results)) >= 2) ###至少有一組值存在
else:
    print (False)   

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/51158800/136403035-0f1ebf2d-6781-42e1-91bd-33035e0e287e.png)

## 問題描述

1. 不管怎麼修改都是Runtime Error，兩筆測資都正確
2. 能把資料型態限定的地方，都限定起來了，但是依然測不出來

- 10/11 Udated
1. 抱歉，那時候為了要改的更好理解一點，中間沒有改到，但是就算改了也還是 runtime error
2. 已更新連結於上方

**Comment by Chongfong** [comment]
c....是什麼
可以先看錯誤訊息喔

**Comment by lazyYC** [comment]
@MarsTsraM 
你最前面定義的變數叫做TriC

**Comment by MarsTsraM** [comment]
10/11 Udated
抱歉，那時候為了要改的更好理解一點，中間沒有改到，但是就算改了也還是 runtime error
已更新連結於上方

**Comment by Chongfong** [comment]
1. if 後面的c變數沒改
2. 可以直接強迫讓輸入變整數
3. 測資：13，4,18 ->True
