### ISSUE TITLE
[Week 3] 串列切割

### ISSUE THREAD

**Issue by ting8931** [coding-coworking-club/basic-python-fall-2021#41]
## 程式碼

```python
a=[int(i) for i in input().split(',')]
total=0
sum=0
check=False

for i in range(len(a)):
    total+=a[i]
    
for j in range(len(a)):
    sum+=a[j]
    if sum==total/2:
        check=True
print(check)
```

## 問題描述

在jupyter上測試一切正常，但是judge顯示 Runtime Error，請問哪裡出問題了呢

**Comment by jasonchen1125** [comment]
要看清楚題目是說 **浮點數** 還是 **整數** 哦

另外記得下次要補上**提交連結**，細節請參考[github 發文須知](https://www.notion.so/GitHub-Issue-3835cacb3d6747bfb964d5cae5e85036)

**Comment by ting8931** [comment]
好的謝謝

**Comment by Tsi-ho** [comment]
我也遇到相同的問題，但即使知道輸入是 float，也不確定要如何修正。

想請問 @ting8931  用什麼方法解決這個問題？
