### ISSUE TITLE
[Homework 1] 直角三角形

### ISSUE THREAD

**Issue by Lipahak** [coding-coworking-club/basic-python-fall-2021#43]
## 提交連結

https://judge.ccclub.io/contest/71/problem/02

## 程式碼

```python
c = int(input())
yz = input().split()  
yznum = [int(i) for i in yz]
yznum.sort()
y = yznum[0]
z = yznum[1]

if c>y and c>z and y+z>c and y+c>z and z+c>y and y*y+z*z==c*c:
  print("True")

else:
  print("False")
```

## 問題描述

在colab可以順利跑出結果，在Judge 出現 Wrong Answer。

我對這句話的理解「請判斷範圍在y跟z之間（包含y和z，y可能小於或大於z），是否存在兩個整數a, b滿足 c^2 = a^2 + b^2。」，其實不是很了解，不知道是不是這裏出疏漏了什麼。

**Comment by lazyYC** [comment]
@Lipahak 
「請判斷範圍在y跟z之間（包含y和z，y可能小於或大於z」的意思：
例如 `c = 5`，我們知道常見的整數解 `a , b = 3, 4`，這時候如果3, 4 有在題目給的上下限 y, z 範圍內，就是輸出 `True`  
因為你會需要用迴圈去操作

**Comment by Lipahak** [comment]
好的，我懂了謝謝助教
