### ISSUE TITLE
[Week 3] 小明採蘋果

### ISSUE THREAD

**Issue by jessyikea** [coding-coworking-club/basic-python-fall-2021#44]
## 提交連結

https://judge.ccclub.io/status/c87f981196d75e2d5adb9adaa95684f6

## 程式碼

```python

apple = [int(i) for i in input().split(',')]
total = 0
lst = [] 

for j in range(len(apple)):
    if j == 0:
        total = apple[j] + apple[j+1]
    elif j == len(apple) - 1:
        total = apple[j] + apple[j-1]
    else:
        total = apple[j] + apple[j-1] + apple[j+1]
    lst += [total]

m = max(lst)

for k in range(len(lst)):
    if m == lst[k]:
        print(k)
        break

```

## 問題描述

在Jupyter notebook上有跑出正確的output，但在judge系統上顯示Runtime Error。
解題思路：把input用逗號分割，丟進名為apple的list中，透過迴圈計算從第一顆樹到最後一顆樹的自己與左右兩棵樹的蘋果數量總和，接著把不同蘋果總和丟進新的list中，找到lst中的最大值，再回找最大值的位置，得到可以計算出最多蘋果數目的蘋果樹位置。

**Comment by jasonchen1125** [comment]
題目說"至少有一棵樹"，可以思考看看若**只有一顆樹**是否仍然符合你的解題思路
