### ISSUE TITLE
[Homework 1-2] 直角三角形

### ISSUE THREAD

**Issue by Doristangcy** [coding-coworking-club/basic-python-fall-2021#45]
## 提交連結

https://judge.ccclub.io/status/c10bf4c30fb17670c9588451fb9a12d8

## 程式碼

```c = int(input())
yz = input().split(" ")
y = int(yz[0])
z = int(yz[1])
lst1 = []
lst2 = []
a = True

for k in range (y+1):
    y_sq = k**2
    lst1.append(y_sq)
for s in range(z+1):
    z_sq = s**2
    lst2.append(z_sq)
    
for g in range(len(lst2)):
    for f in range(len(lst1)):
            
        if lst1[f]+lst2[g] == c**2:
            a = True             
        else:
            a = False
            
print(a)

```

## 問題描述

想請問我在Jupyter 裡面跑上面這串程式碼時，輸入[13,5,12]和[3,5,7]都可以正確印出True和False, 但是我到Judge提交時，卻一直顯示出wrong answer，我在想是不是我設的a = True 這個Flag有點問題，但又不知道到該如何調整，可以請助教幫忙看一下嗎?謝謝!

**Comment by lazyYC** [comment]
請參考 https://github.com/coding-coworking-club/basic-python-fall-2021/issues/28
你們的寫法跟問題幾乎一樣XD
