### ISSUE TITLE
[Week 3] 小明管倉庫

### ISSUE THREAD

**Issue by jessyikea** [coding-coworking-club/basic-python-fall-2021#46]
## 程式碼

```python

inventory = [int(i) for i in input().split(',')]
sales = [int(j) for j in input().split(',')]
n = inventory[0]
m = 0

while n > 0:
    for k in range(7):
        n = n - sales[k]
        m += 1
        if k != 6 and n <= sales[k + 1]:
            print(m + 1 - inventory[1])
        elif k == 6 and n <= sales[0]:
            print(m + 1 - inventory[1])
    break

```

## 問題描述

輸入judge系統中的Sample Input1，有得到正確的output，但在jupyter notebook中，輸入Sample Input2時，不會跑出任何output或錯誤的訊息。
解題思路：只要存貨總數n大於零時，以迴圈形式不斷扣除當天的出貨量，並且m增加一天，直到當天的存貨數量小於明天的出貨量時，得到m+1天的庫存會不足，所以用m+1減掉下訂天數inventory[1]。

**Comment by TungLee518** [comment]
迴圈範圍被限制住了，可以在最後 print 出 m 看看。

**Comment by jessyikea** [comment]
> 迴圈範圍被限制住了，可以在最後 print 出 m 看看。

![擷取](https://user-images.githubusercontent.com/92155118/136663194-ffa81981-8c1a-4c8b-a541-cc724dd69e59.JPG)
我更改了一下程式碼，這樣迴圈好像沒有被限制住了，雖然jupyter notebook上有跑出兩題範例的output，但judge系統上還是顯示wrong answer。

**Comment by TungLee518** [comment]
while n > 0: 的意思會是當 n 還是大於零的話迴圈會繼續跑
note : jupyter都對但WA的話可以自己編幾個測資試看看~
