### ISSUE TITLE
[Homework 1-02] 直角三角形

### ISSUE THREAD

**Issue by yuting85919s** [coding-coworking-club/basic-python-fall-2021#47]
## 提交連結

https://judge.ccclub.io/status/47fbdaaa6163ed69b9361f093ef8face
## 程式碼

```
#直角三角形
num1=int(input())
m,n=map(int,input().split()) 					

if m>n:  										
    small=n
    big=m
elif(m<n):
    small=m
    big=n

minus=big-small
record=0


for i in range(minus+1):
    if small**2 + (small+i)**2 == num1**2:
        record=1

if(record==1):
    print('True')
else:
    print('False')

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/34641533/136591915-b07e6d64-2ada-43ab-ac4c-903394c9e960.png)

## 問題描述

1.在jupyter run都沒問題，除了judge提供的兩題測資之外，自己也找了很多直角三角形的組合測試都True（也有故意亂打的，的確也是false)，但到了judge顯示wrong answer。
2.有把issue內所有和本題相關的看過一輪，但因為大家的邏輯寫法都不太一樣，本題有點難互相參考。
3.從wrong answer看不出來哪裡錯誤，可能也有自己的盲點，再麻煩助教（或各位同學大大）了，謝謝您們！

**Comment by lazyYC** [comment]
@yuting85919s 

```
record=0
for i in range(minus+1):
    if small**2 + (small+i)**2 == num1**2:
        record=1
if(record==1):
    print('True')
else:
    print('False')
```
猜測你或許有點誤解 `range` 或 `for` 的用法，`range()` 的參數是 `range(start , end,  interval)`
不設起點的話，`for i in range (n)` 得到的 i 會是 0 ~ n -1
本題需要的是探索 y , z 之間的解，所以需要設起始點 y

另外，在這個情況下設 flag 的方式，可以從 `record = 0` 直接改用 `ans = True` 之類的

**Comment by yuting85919s** [comment]
@lazyYC 您好，謝謝您的回覆！

1.謝謝設flag的簡潔寫法提供！學起來了（更改如下）
2.我知道 `range` 和 `for`的用法～不過不知道為何我這樣寫不行呢？一樣也是給定一個用input兩個數字相減得到的範圍，並且考慮到index從0開始取，所以還用minus+1，避免y,z中的z沒有被取到

```
minus=big-small
ans='False'

for i in range(minus+1):   #+1是要讓big也被考慮進去,因range開始計算是從0,if minus=7,那只會算到0~6
    if small**2 + (small+i)**2 == num1**2:
        ans='True'

print(ans)
```

我用`minus+1`其實意思是一樣的。我有嘗試改成`range(small,big+1,1)` 不過還是一樣jupyter ok, judge wrong answer

我的撰寫邏輯：
目的在於從題目的y,z(此為small,big)之間去找是否有讓規則成立的數字存在，所以`for`這段會依序從small開始往上加
ex: small=5, big=12  `small**2 + (small+i)**2 == num1**2` 會從 `(5**2+6**2),(5**2+7**2),(5**2+8**2)`...依序判斷到`(5**2+12**2)`成立

**Comment by lazyYC** [comment]
> @lazyYC 您好，謝謝您的回覆！
> 
> 1.謝謝設flag的簡潔寫法提供！學起來了（更改如下） 2.我知道 `range` 和 `for`的用法～不過不知道為何我這樣寫不行呢？一樣也是給定一個用input兩個數字相減得到的範圍，並且考慮到index從0開始取，所以還用minus+1，避免y,z中的z沒有被取到
> 
> ```
> minus=big-small
> ans='False'
> 
> for i in range(minus+1):   #+1是要讓big也被考慮進去,因range開始計算是從0,if minus=7,那只會算到0~6
>     if small**2 + (small+i)**2 == num1**2:
>         ans='True'
> 
> print(ans)
> ```
> 
> 我用`minus+1`其實意思是一樣的。我有嘗試改成`range(small,big+1,1)` 不過還是一樣jupyter ok, judge wrong answer

啊我沒注意到你有用 (small + i) XD
那沒事

> 
> 我的撰寫邏輯： 目的在於從題目的y,z(此為small,big)之間去找是否有讓規則成立的數字存在，所以`for`這段會依序從small開始往上加 ex: small=5, big=12 `small**2 + (small+i)**2 == num1**2` 會從 `(5**2+6**2),(5**2+7**2),(5**2+8**2)`...依序判斷到`(5**2+12**2)`成立

不過看起來你只有用一層迴圈，因此如你所述 small 是固定的，
但如果 small = 5 的時候沒有符合的答案，你需要繼續找 small =6, 7, .., 12 的情況。

**Comment by yuting85919s** [comment]
> > @lazyYC 您好，謝謝您的回覆！
> > 1.謝謝設flag的簡潔寫法提供！學起來了（更改如下） 2.我知道 `range` 和 `for`的用法～不過不知道為何我這樣寫不行呢？一樣也是給定一個用input兩個數字相減得到的範圍，並且考慮到index從0開始取，所以還用minus+1，避免y,z中的z沒有被取到
> > ```
> > minus=big-small
> > ans='False'
> > 
> > for i in range(minus+1):   #+1是要讓big也被考慮進去,因range開始計算是從0,if minus=7,那只會算到0~6
> >     if small**2 + (small+i)**2 == num1**2:
> >         ans='True'
> > 
> > print(ans)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我用`minus+1`其實意思是一樣的。我有嘗試改成`range(small,big+1,1)` 不過還是一樣jupyter ok, judge wrong answer
> 
> 啊我沒注意到你有用 (small + i) XD 那沒事
> 
> > 我的撰寫邏輯： 目的在於從題目的y,z(此為small,big)之間去找是否有讓規則成立的數字存在，所以`for`這段會依序從small開始往上加 ex: small=5, big=12 `small**2 + (small+i)**2 == num1**2` 會從 `(5**2+6**2),(5**2+7**2),(5**2+8**2)`...依序判斷到`(5**2+12**2)`成立
> 
> 不過看起來你只有用一層迴圈，因此如你所述 small 是固定的， 但如果 small = 5 的時候沒有符合的答案，你需要繼續找 small =6, 7, .., 12 的情況。

喔！對耶，這樣會沒考慮到small =6, 7, .., 12 的情況
我來改改，謝謝您！
