### ISSUE TITLE
[Homework 1] OOXX

### ISSUE THREAD

**Issue by Mandy825** [coding-coworking-club/basic-python-fall-2021#48]
## 提交連結

https://judge.ccclub.io/status/1c3707c716a443415cc18e82318b046c

## 程式碼

```python
a=input()
lst1=[" "," "," "]
lst2=[" "," "," "]
lst3=[" "," "," "]
for i in range(len(a)):
    if 0<int(a[i])<4:
        lst1.insert(int(a[i])-1,"O")
    elif 3<int(a[i])<7:
        lst2.insert(int(a[i])-4,"O")
    elif 6<int(a[i])<10:
        lst3.insert(int(a[i])-7,"O")
print(f"({str(lst1[0])}{str(lst1[1])}{str(lst1[2])})")
print(f"({str(lst2[0])}{str(lst2[1])}{str(lst2[2])})")
print(f"({str(lst3[0])}{str(lst3[1])}{str(lst3[2])})")
```

## 問題描述

在jupyter上是可以的，想請問哪裡有問題，謝謝！

**Comment by Tsi-ho** [comment]
嗨，我猜問題在於圈圈的表示字符。

我記得題目要求最後輸出的圈圈要以大寫的 O 表示，但你目前是用數字的零。

**Comment by Mandy825** [comment]
@Tsi-ho 我這邊應該是用大寫O（只是上面O跟0看起來很像><）還是謝謝你！

**Comment by Tsi-ho** [comment]
@Mandy825 抱歉我之前搞錯了！

問題可能在於目前的 code 可能無法解決某些狀況。例如當數字不是由小到大時就可能出錯，可以試試：132、64、798。要解決這個問題，我建議你可以用 `print()` 去檢視 list 1 到 list 3 和原先結果的差異。

**Comment by Mandy825** [comment]
@Tsi-ho 喔喔喔我沒想到這個！我剛用sort就順利解出來了！！感謝你！！！
