### ISSUE TITLE
[Week 3] 串列切割

### ISSUE THREAD

**Issue by cynnancy** [coding-coworking-club/basic-python-fall-2021#49]
## 提交連結

https://judge.ccclub.io/status/60a1765a76120ec0d93b519d386869ea

## 程式碼

```python
lst = input().split(',')

for i in range (len(lst)):
    lst [i] = float(lst[i])
    
for i in range(len(lst)):
    firstpart = lst[:i]
    secondpart = lst[i:]
    
if sum(firstpart) == sum(secondpart):
    print(True)
else:
    print(False)
```

## 問題描述

在jupyter上測試都顯示正常，不知道為甚麼在judge系統顯示Wrong Answer

**Comment by jasonchen1125** [comment]
這樣的寫法並沒有做到逐一去切割檢查哦。

你有寫迴圈按照位子一個個切割為左右沒錯，但因為你最後的 **條件判斷是在迴圈之外** ，等於是迴圈整個跑完停留在最後一個 i你才做條件判斷，所以這個 if 只會去判斷切在最後一個位子左右左和是否相同，如果今天是在其他位子可以讓左右總和相同，你的程式就會出錯了。

可以想一下要怎麼讓他可以在切割每個位子的時候同時檢查左右總和是否相等，一找到就print True，若都找不到在print False。

**Comment by cynnancy** [comment]
瞭解了，謝謝你！！！
