### ISSUE TITLE
[General] 關於boolean的問題

### ISSUE THREAD

**Issue by organicguava** [coding-coworking-club/basic-python-fall-2021#5]
## 提交連結
https://edabit.com/challenge/NLY7zGMYocsTbeS6n

## 程式碼

```python
def reverse(*n):
    if isinstance(n,bool):
        if n=True:
            return False
        else:
            return True
    else:
        return "boolean expected"
```

## 錯誤訊息
![2021-09-26](https://user-images.githubusercontent.com/91002499/134794160-477871f1-2c8d-43bf-9248-5a0836eb963c.png)

## 問題描述
Create a function that reverses a boolean value and returns the string "boolean expected" if another variable type is given.

Examples
reverse(True) ➞ False

reverse(False) ➞ True

reverse(0) ➞ "boolean expected"

reverse(None) ➞ "boolean expected"

**Comment by zhilinsu** [comment]
```python
if n == True:  # 邏輯判斷是雙等號
    return False
```

**Comment by Viggochang** [comment]
這邊回覆一下
ccClub 的 GitHub 提供大家針對judge題目發問 或是 開放式提問關於python的相關問題
但如果是別的平台的題目慶不要在這邊發問喔
