### ISSUE TITLE
[General] 7-2：加減長方形

### ISSUE THREAD

**Issue by Terry0807** [coding-coworking-club/basic-python-fall-2021#51]
## 提交連結
https://judge.ccclub.io/problem/180019

## 程式碼

                

```
I=int(input())
W=int(input())
for x in range(1,W+1):
    if x%2!=0:
        for y in range(1,I+1):
            if y%2!=0:
                print("+",end="")
            elif y%2==0:
                print("-",end="")
    if x%2==0:
        for y in range(1,I+1):
            if y%2!=0:
                print("-",end="")
            elif y%2==0:
                print("+",end="")
    print(end='\n')
```

## 問題描述
自己在jupyter notebook 上run是沒有問題的，也符合題目要求「加減相間隔」，但在ccClub judge上寫wrong answer。
（我有看到judge上面的sample input是4 3的情況下，上下兩排的「+ -」似乎沒有相間隔，不太確定為何sample沒有符合題目敘述，或是我有理解錯誤？）

**Comment by Tsi-ho** [comment]
嗨，我猜 sample 沒有問題。

題目有一個沒說的條件是：當第一個 input 為奇數時，奇偶數行的 +- 排列不同；若為偶數，每行的 +- 排列相同。

**Comment by Terry0807** [comment]
了解了！修正之後為正確答案，謝謝。
