### ISSUE TITLE
[Week 3] 小明管倉庫

### ISSUE THREAD

**Issue by 40743203S** [coding-coworking-club/basic-python-fall-2021#54]
## 提交連結

https://judge.ccclub.io/status/521bd43eef637be87b9fd6799a430993
## 程式碼

```python
import_day = [int(num) for num in input().split(",")]  #表初始存貨與進貨天數
export = [int(num) for num in input().split(",")]          #表出貨量
remain_goods = import_day[0]                                  #提取初始存貨量
elapsed_times = []                                                      #利用每天扣除的動作計算經過天數
for i in export:    
    for y in export:                                                        #利用兩迴圈增加可運算的空間
        remain_goods -= y                                             #執行每天扣除的動作
        elapsed_times.append(remain_goods)               #丟進序列以計算經過天數
        if remain_goods < 0:                             
            break
    if remain_goods < 0: 
        break
print(len(elapsed_times) - import_day[1])                   #將經過天數扣除進貨天數
```

## 問題描述

助教大大！其實我是成功的... 但很抱歉我覺得我的程式有一點bug，所以想請問助教，原因是我用了兩迴圈增加運算的空間，但假如把一開始的存貨量增加或是把每日出貨量削減，以致其超出兩迴圈的運算，是否程式就不成立了？ 不知道我有沒有清楚的表達我的想法，如果可以，不好意思麻煩助教解惑！！在這裡獻上十二萬分的感激！！
想說在程式後面補上說明可以更方便閱讀，結果在編輯畫面調好，在預覽卻完全跑版且無法調整，希望助教不會介意...   (十分覺得難過

**Comment by jasonchen1125** [comment]
@40743203S 

你說的沒錯，如果一開始的存貨量非常高或是每日出貨量非常低造成可以持續出貨49天以上，你的程式就會停留在49天
更好的做法應該是寫一個迴圈加上條件，使得迴圈除非遇到存貨低於出貨量要停止，否則可以持續下去而不受到迴圈運算範圍的牽制。

而要做到這件事，必須使得在扣掉第七天出貨後準備進到下一天時，讓他的位置索引值直接assign成第一天，重新從0開始，如此一來便可以解決超出兩迴圈運算的範圍而出錯，可以想一想該怎麼寫才能做到這件事。可以試試看用 while 迴圈並用到位置索引，來達到我前面說的作法。

你可以試試看，若有遇到問題就把程式貼上來我們可以討論！

**Comment by 40743203S** [comment]
好的~謝謝助教！！！
