### ISSUE TITLE
[Week 3] 串列切割

### ISSUE THREAD

**Issue by chenboshiun** [coding-coworking-club/basic-python-fall-2021#58]
## 提交連結

https://judge.ccclub.io/status/94b3451c9826b8c717cb3a31afc7c0c6

## 程式碼

```python
# 各浮點數轉串列並重新排序元素
float_num = [float(x) for x in input().split(",")]
float_num.sort()

# 串列切割並重新排序元素
half = len(float_num) // 2
float_num[:half].sort()
float_num[half:].sort()

#加總
x = sum(float_num[:half+1])
y = sum(float_num[half+1:])

#轉正值判斷是否相等
if abs(x) == abs(y):
    print("True")
else:
    print("False")
```

## 錯誤訊息

Wrong Answer

## 問題描述

在 PyCharm 顯示是正常的，但在 judge 系統顯示 Wrong Answer，懷疑是不是串列切割的問題，因為切出來的的串列元素個數，其實不等於左半邊

Input example: 
1,-1,2,-2,0,0

Output example:
x = [-2.0, -1.0, 0.0, 0.0]
y = [1.0, 2.0]

再麻煩助教大大指點迷津，謝謝。

**Comment by chenboshiun** [comment]
```python
float_num = [float(x) for x in input().split(",")]
float_num.sort()
half = len(float_num) // 2
float_num[:half].sort()
float_num[half:].sort()
x = sum(float_num[:half])
y = sum(float_num[half:])
if abs(x) == abs(y):
    print("True")
else:
    print("False")
```

有試著把 +1 拿掉，如果串列內是偶數個元素，能夠使切出來的左串列與右串列的個數是相等，但是如果輸入奇數個元素，EX: 1,2,3
加總判斷就會噴 False 了，不知道怎麼切會比較好了

**Comment by LinYuanSheng** [comment]
題目理解好像有錯誤喔~題目沒有要求你將數列重新依序排列，而是依照現在有的狀態去切割左邊右邊後加總是否相等。
因為你兩個都有用sort排過，所以都無法AC

**Comment by chenboshiun** [comment]
好哦～感謝。
