### ISSUE TITLE
9-1：數字總和排序

### ISSUE THREAD

**Issue by Yating2021** [coding-coworking-club/basic-python-fall-2021#6]
## 提交連結

https://judge.ccclub.io/problem/180024

## 程式碼

```
def sumy(x):  #各數字相加
    b=[]
    n=0
    for i in range(len(x)):
        for j in range(len(x[i])):
            k = x[i]
            n+=int(k[j])
        b.append(n)
        n=0
    return b
def lis(x):  #轉換input的資料為[" "," "]
    l=x.split(" ")
    return l
def lis_int(x): #轉換成int[  ,  ]
    b=[]
    for i in range(len(x)):
        b.append(int(x[i]))
    return b


x=input()
l=lis(x)  #轉換成可以資料
print('l:',l)
print('數字相加結果:',sumy(l)) #相加結果
x=sorted(l,key=sumy)
print('排序後結果:',lis_int(x)) #排序結果
```

## 問題描述

 key的自訂義內容 看起來沒有錯,不知道為什麼沒有進行排序

**Comment by Yating2021** [comment]
無法排序

**Comment by Yating2021** [comment]
> ## 提交連結
> https://judge.ccclub.io/problem/180024
> 
> ## 程式碼
> <
> def sumy(x): #各數字相加
> b=[]
> n=0
> for i in range(len(x)):
> for j in range(len(x[i])):
> k = x[i]
> n+=int(k[j])
> b.append(n)
> n=0
> return b
> def lis(x): #轉換input的資料為[" "," "]
> l=x.split(" ")
> return l
> def lis_int(x): #轉換成int[ , ]
> b=[]
> for i in range(len(x)):
> b.append(int(x[i]))
> return b
> 
> x=input()
> l=lis(x) #轉換成可以資料
> print('l:',l)
> print('數字相加結果:',sumy(l)) #相加結果
> x=sorted(l,key=sumy)
> print('排序後結果:',lis_int(x)) #排序結果
> 
> > 
> 
> ## 錯誤訊息
> ## 問題描述
> < key的自訂義內容 看起來沒有錯,不知道為什麼沒有進行排序 >

**Comment by zhilinsu** [comment]
我覺得看起來的原因是，你所定義的 `sumy(l)` parameter 為 list，並且回傳另外一個 list。
但是 `sorted()` 中的 `key=`，其用法是將 key 的函數套用在 list 當中的每一個 element。

你可以將單獨一個數字的 string (e.g., `'123'`) 丟入你的 `sumy(l)` 當中試試看，會發現其 return 的會是將這個數字 string 每一個數字拆開來的 list，而非其總和。
