### ISSUE TITLE
[Homework 04] 統神端火鍋

### ISSUE THREAD

**Issue by hrplt7** [coding-coworking-club/basic-python-fall-2021#64]
## 提交連結

他暫時沒出現 系統好像怪怪的

## 程式碼

```python
real = input().split(",")
real = [int(i) for i in real]
ideal = sorted(real, reverse = True) #sorted is function not method
t = 0 #從0開始計算錯幾次

for sev1 in real:
    for sev2 in ideal:
        if real.index(sev1) == ideal.index(sev2):
            break #比較實際與理想的端出順序 確認同一順序後跳出去看是否為正確的價格
    if sev1 != sev2:
        t += 1 #累計錯幾次

print(f"過來一下，你又端錯{t}次了")


```

## 錯誤訊息

Wrong Answer
## 問題描述

我之後才想到可以直接用range配合slice，在那之前我是想到，我先將實際端出去的跟理想端出去的，這兩個list的index對齊，之後比較數值，如果一樣就沒問題，不一樣就代表這不是理想該班出去的，錯誤次數會+1，做了很多資測，也試過負數或者是0，但都正確，因此想問助教有哪些狀況是我沒考慮到的嗎？

**Comment by RayZhao0310** [comment]
如果你直接問index，出現重複元素的時候，他會回傳第一次出現的index。
舉例來說 ：
2, 2, 1
你如果問sev2 == 2時的index，永遠只會回傳0喔~

**Comment by hrplt7** [comment]
原來如此！ 謝謝您！
