### ISSUE TITLE
[General] 192201 檢查日期

### ISSUE THREAD

**Issue by afudog91** [coding-coworking-club/basic-python-fall-2021#65]
## 提交連結

https://judge.ccclub.io/status/d998bd6b2042eef438d1341ec23f4c38
## 程式碼

```python
def date_check(year,month,day):
    correct_month_list = [1,2,3,4,5,6,7,8,9,10,11,12]
    big_month_list = [1,3,5,7,8,10,12]
    small_month_list = [4,6,9,11]
    if year < 1 or month < 1 or day < 1:
        return False
    else:
        if month == 2 and day < 29:
            return True
        elif month in big_month_list and day < 32:
            return True
        elif month in small_month_list and day < 31:
            return True
        else:
            return False

date_str_list = input().split("\n")
while True:
    for date_str in date_str_list:
        if date_str == "end":
            break
        else:   
            date_list = [int(_) for _ in date_str.split(", ")]
            year = date_list[0]
            month = date_list[1]
            day = date_list[2]
            if date_check(year,month,day) == True:
                print("OK")
            else:
                print("error")
    break
```

## 問題描述

    新手發問 請多多包涵
    有幾個癥結點: 
     1. 不清楚題目 Input 會給的字串樣子，要怎麼切割它勒..  (有試過 split(",  ") 切日期、以及split("\n") 切換行)...
     2. 不清楚正確日期的定義，用過題目 sample 的日期分批輸入自製的函數，執行起來無誤.. 請教是否有其他定義...
     3. while loop 這樣設計 break 的出來嗎?
    感謝助教大大們的協助~

**Comment by LiYiJie321** [comment]
想請教後來如何解決?
要怎麼輸入多行，最後再print出結果?
謝謝!

**Comment by afudog91** [comment]
> 想請教後來如何解決? 要怎麼輸入多行，最後再print出結果? 謝謝!

後來發現 題目input 的意思應該是 "分別" 丟一行、一行的字串給你，所以只要針對"一行"字串做判斷和處理就好 (一開始想太多 才會想說要先針對換行"\n"切割)。
關於日期的判定似乎沒有大問題....
另外經過高人指點，發現我的程式 while loop 設計不良 才會一直跑出 TLE，問題不單純是 break，而是要讓題目 input 的值一次一次的放進 while loop 裡面檢查。後來我把 input() 搬進 while loop 裡，就得到開心的綠色 accepted 了! 
( 這樣有幫到你嗎@@? )

**Comment by LiYiJie321** [comment]
解決了，謝謝!
