### ISSUE TITLE
[General] 180101 停車費

### ISSUE THREAD

**Issue by cccc1995** [coding-coworking-club/basic-python-fall-2021#66]
## 提交連結

https://judge.ccclub.io/status/9eada0e3ed48a958d01be070370de7a6

## 程式碼

```python
inparking = [int(i) for i in input().split(":")]
outparking = [int(i) for i in input().split(":")]
w = input("是否有台大證件(Ｙ/Ｎ)：")

hour_dif = outparking[0]-inparking[0]
min_dif = outparking[1]-inparking[1]
hour_change = (hour_dif)*60
total_mins = hour_change + min_dif

if w == "Y":
    if total_mins >= 30:
        z=round((total_mins/30))*20/2
        print(int(z))
    else:
        print(0)
else:
    if total_mins >= 30:
        y=round((total_mins/30))*20
        print(int(y))
    else:
        if total_mins == 0:
            print(0)
        else:
            print(20)
```

## 錯誤訊息

Wrong Answer

## 問題描述

在Jupyter上答案都是正確的，但在Judge上卻一直出現Wrong Answer，不知道是哪裡出錯了（我也有考慮過同分鐘進出的問題，但還是不知道自己哪裡錯誤ＱＱ）

**Comment by Tsi-ho** [comment]
嗨，我目前看到一個可能的問題是：停車時間未滿半小時的某些情況會計算錯誤。

考慮以下可能：11:00 進場、11:31 離場、有無證件皆可。這個例子多出來的一分鐘因為未滿三十分鐘，應該以三十分鐘計算並且計費，所以應該和 12:00 離場的費用相同。不過依照以上程式的計算方式，這個一分鐘不會被考慮並計費，也和 12:00 離場的收費不同。

**Comment by cccc1995** [comment]
> 嗨，我目前看到一個可能的問題是：停車時間未滿半小時的某些情況會計算錯誤。
> 
> 考慮以下可能：11:00 進場、11:31 離場、有無證件皆可。這個例子多出來的一分鐘因為未滿三十分鐘，應該以三十分鐘計算並且計費，所以應該和 12:00 離場的費用相同。不過依照以上程式的計算方式，這個一分鐘不會被考慮並計費，也和 12:00 離場的收費不同。

您好，我剛剛有嘗試過11:00 進場、11:31 離場，但在式子的運算上是符合題目的><（也就是沒有台大證件的話會被收取20元，有的話則免費），所以看起來好像不是這個問題ＱＱ

**Comment by Tsi-ho** [comment]
@cccc1995 你可能誤解題目意思了。

我想「不滿30分鐘算為30分鐘」的意思就是以三十分鐘一個單位，而未滿一個單位則直接計算為一個單位。 11:00 - 11:31 的停車時間為 31 分鐘。扣掉 30 分鐘後，多出來的 1 分鐘直接計算為 30分鐘。所以依照題目要求，有證件應收 20 元，無證件應收 40 元。
