### ISSUE TITLE
[General] 8-3：及格門檻

### ISSUE THREAD

**Issue by lily27404** [coding-coworking-club/basic-python-fall-2021#67]
## 提交連結

https://judge.ccclub.io/status/de967297804ef32a15f5e69bbea65e5d

## 程式碼

```python

```
def threshold (x,y):
    answer = []
    for i in range(len(x)):
        answer.append(x[i] > = y)
        return answer
I = [int(num) for num in input().split()]
t = int(input())
print(threshold(I,t))

## 錯誤訊息

<img width="730" alt="問題" src="https://user-images.githubusercontent.com/92163022/136760740-ba8b9e87-5e4a-4f1d-b19d-87d4dabbe7f1.png">

<img width="357" alt="問題2" src="https://user-images.githubusercontent.com/92163022/136760946-15111697-d195-4514-a626-4a9e197e8dfc.png">
## 問題描述

利用jupyter和進行trace code時都發現 只有比較到串列第一個值，沒有進行到迴圈，但我已經寫了for迴圈了，不清楚是哪裡導致for迴圈沒有成功。
想請助教協助解惑，謝謝助教!

**Comment by jasonchen1125** [comment]
提示一下，你的 return 應該要在迴圈內還是迴圈外呢？
return 放的位子不同會影響整個程式哦

**Comment by lily27404** [comment]
我通過了!謝謝助教!
