### ISSUE TITLE
[General] 6-3：母音種類個數

### ISSUE THREAD

**Issue by physkevin** [coding-coworking-club/basic-python-fall-2021#68]
## 程式碼

```python
word = input()
vowels = ['a','e','i','o','u']
#以下的迴圈跑上面那個串列的五個母音，如果任何一個母音不在原本的字串之中，就拿掉那個母音，最後計算母音還剩幾個
for vowel in vowels:
    if vowel not in word:
        vowels.remove(vowel)
#下面那個註解是我用來檢視母音拿掉的過程，print出來可以發現常常拿掉的過程中會漏掉，但不知道為什麼
#        print (vowels)
print (len(vowels))
```

## 問題描述

在拿掉母音的過程中常常會漏掉，例如輸入是bc，如果在中間print一次vowels的串列，可以發現拿掉的過程是
['e', 'i', 'o', 'u']
['e', 'o', 'u']
['e', 'o']
原本理應全部都拿掉的，但不知道為什麼e和o被留下了
懇請助教大大幫我看看哪裡出了問題，感激不盡 @@
p.s.我知道題目希望區分大小寫，但這裡先用小寫試試看，如果可以的話在vowels的串列中再加入大寫就好了～～

**Comment by jasonchen1125** [comment]
for 迴圈是看位子，所以當你 ['a','e','i','o','u'] 刪掉位子 0 的 a 之後，list 剩下 ['e', 'i', 'o', 'u']
接著進到第二次迴圈，他會抓位子1，但這時候位子 1 在 list 中是 i ，所以 e 就被跳過了，刪除 i 後剩下 ['e', 'o', 'u']
同理，進到第三次迴圈，他抓位子2，這時候位子 2 在 list 中是 u，所以 o 就被跳過了，刪除 o 後剩下 ['e', 'o']

可以想看看該怎麼解決這個問題或是還有什麼更好的方法可以做到你想要的目的~有問題可以再提出！

**Comment by physkevin** [comment]
我懂了，這個問題真的很難自己發現，謝謝助教！！！
我之後應該會把remove改成replace，統一取代成某一特定字元，再數取代掉的數量，這樣就不會改變串列長度，應該就解決了～～再次感謝～
