### ISSUE TITLE
[Homework 05] 又是喵球

### ISSUE THREAD

**Issue by Doristangcy** [coding-coworking-club/basic-python-fall-2021#69]
## 程式碼

```
lst1 = [str(word) for word in list(input().lower())]


for x in lst1:
    if ord(x) < ord("m"):
        print(x.upper(),end = "")  

    else:
        print(x.lower(),end = "")   
```

## 問題描述

想請問助教我在Jupyter 上測試這段code的時候，輸入ccClub 和 ABCXYZ 都可以輸出正確答案，但我在judge送出時卻一直顯示wrong answer，我有嘗試過去pythontutor看每一步的輸出，但還是不懂到底哪一段的邏輯有問題，能否請助教幫忙確認一下呢? 謝謝!

**Comment by lazyYC** [comment]
@Doristangcy 

> 如果是m或排序在m以前的字母，那麼喵球會習慣總是寫成大寫

你的 code 裡面 m 不會被轉成大寫哦～

btw 標題請用[Homework 1]
