### ISSUE TITLE
[General] 7-2：加減長方形

### ISSUE THREAD

**Issue by daniel860305** [coding-coworking-club/basic-python-fall-2021#7]
## 提交連結

https://judge.ccclub.io/status/e94b596d638365fd2a76ca4012570701
## 程式碼

```python
l = int(input())
w = int(input())
lst1 = []
lst2 = []

for i in range(l): #先將每行的元素+ -交錯加到字串中
    if i % 2 == 0:
        lst1.append('+')
        lst2.append('-')
    else:
        lst1.append('-')
        lst2.append('+')

for i in range(w): #根據不同行 輸出不同的列表
        print(''.join(lst1)) if i % 2 == 0 else print(''.join(lst2))
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/91551415/135114025-48965d37-5d53-40a2-a8dc-90ad0f15a297.png)

## 問題描述

題目和Udemy上是一樣的，在Udemy上也通過
不知道為何Judge系統顯示wrong answer

**Comment by zhilinsu** [comment]
你目前的寫法在 `l` 為偶數的時候，print 出來的結果會跟 sample output 不同 (e.g., Sample Input/Output 2)。

因為題目的意思是，感覺上有一條很長的由 `+` 跟 `-` 組成的線，用它來形成不同長寬的長方形；
所以如果長為偶數時，每個新的一行都會是由 `+` 開頭，而非 `-`。

但你目前寫法的邏輯，看起來是以 `+` 與 `-` 開頭交錯的形式來組成長方形，與題目的意思不太相同。
