### ISSUE TITLE
[Homework 1] OOXX

### ISSUE THREAD

**Issue by ChiaMin1929** [coding-coworking-club/basic-python-fall-2021#72]
## 提交連結

https://judge.ccclub.io/status/a8d3bb83bcc1dae6eeb55af60fe084bb

## 程式碼

```python

lst=[int(num) for num in input().split()]

for i in range(1,10):
    if i in lst:
        if i%3 == 1:
            print('(O',end="")
        elif i%3 == 2:
            print('O',end="")
        else:
            print('O)')
    else:
        if i%3 == 1:
            print('(',end="")
        elif i%3 == 2:
            print(' ',end="")
        else:
            print(')')

```

## 問題描述

輸出的只有括號，但沒有Ｏ，是程式哪裡有遺漏了呢？麻煩助教提點了，謝謝！
![截圖 2021-10-12 下午10 19 41](https://user-images.githubusercontent.com/92382407/136973810-be29b541-b092-44bd-bb27-06631fc43282.png)

**Comment by 40743203S** [comment]
我也遇到這種狀況~ 是因為147沒有被分割 如果中間隔一個空格(1 4 7)，就可以跑了， 也想問助教要怎麼分割相連的數字

**Comment by ChiaMin1929** [comment]
> 我也遇到這種狀況~ 是因為147沒有被分割 如果中間隔一個空格(1 4 7)，就可以跑了， 也想問助教要怎麼分割相連的數字

我後來用這個方式取代第一行，是可行的！
lst=list(input())
lst1= [int(num) for num in lst] 

但不知道這兩者的差別是什麼

**Comment by siddwang827** [comment]
使用split()這個函數的時候會將原本的string依照括號內參數來切割並轉為list，
這題的input因為數字間沒有符號分開，所以會把整個字串轉為list，
ex :  "147".split() →  ["147"]
這就是為什麼你的for迴圈裡面判斷都會跑到else而只輸出括號的原因，

而list(string)會把string中每個值分開再轉為list，
ex: list("147") → ["1", "4", "7"] 
接著再用list comprehension 把值轉換為int就是你要的結果

可以關鍵字搜尋 python list string轉換~

**Comment by 40743203S** [comment]
謝謝助教！

**Comment by ChiaMin1929** [comment]
> 使用split()這個函數的時候會將原本的string依照括號內參數來切割並轉為list， 這題的input因為數字間沒有符號分開，所以會把整個字串轉為list， ex : "147".split() → ["147"] 這就是為什麼你的for迴圈裡面判斷都會跑到else而只輸出括號的原因，
> 
> 而list(string)會把string中每個值分開再轉為list， ex: list("147") → ["1", "4", "7"] 接著再用list comprehension 把值轉換為int就是你要的結果
> 
> 可以關鍵字搜尋 python list string轉換~

感謝助教！
