### ISSUE TITLE
[Homework 1] OOXX

### ISSUE THREAD

**Issue by chiehlinjo** [coding-coworking-club/basic-python-fall-2021#73]
## 提交連結
https://judge.ccclub.io/status/89ee08527fadb603dcd59e0b89a42c80

## 程式碼
```
miao_num=[int(_) for _ in list(input())] #這個list代表喊的數字
place=[1,4,7,2,5,8,3,6,9] #這個list刻意排列，代表的是位置
for i in range(1,10): #先把每個數字都判斷
    if i in miao_num: #先判斷這些數字當中哪些是要劃圈的
        if i in place[0:3]:
            print("(O",end="")
        elif i in place[3:6]:
            print(" ",end="")
        else:
            print("O)",end="\n")
    else: #再判斷這些數字當中哪些是要畫空格的
        if i in place[0:3]:
            print("( ",end="")
        elif i in place[3:6]:
            print(" ",end="")
        else:
            print(" )",end="\n")

```

## 錯誤訊息
wrong answer 

## 問題描述
設了兩個list，分別代表喊的數字和畫圈畫空格的位置，再跑迴圈去判斷哪些要畫圈，哪些要畫空格。
到jupyter 跑都可以，但在批改系統上是wrong answer，找很久看不出盲點，想麻煩助教提點一下，謝謝

**Comment by siddwang827** [comment]
你的ouput都有少空格的情況，這個錯誤應該蠻明顯的哦~
確定jupyter上code沒有複製錯誤嗎?

**Comment by chiehlinjo** [comment]
對因為一直嘗試不同的寫法我複製錯了，
一開始我是像底下這樣寫的(上面issue寫程式碼的地方也更新了)，也是wrong answer 
再麻煩助教了QQ
miao_num=[int(_) for _ in list(input())] #這個list代表喊的數字
miao_num.sort
place=[1,4,7,2,5,8,3,6,9] #這個list刻意排列，代表的是位置
for i in range(1,10): #先把每個數字都判斷
    if i in miao_num: #先判斷這些數字當中哪些是要劃圈的
        if i in place[0:3]:
            print("(O",end="")
        elif i in place[3:6]:
            print(" ",end="")
        else:
            print("O)",end="\n")
    else: #再判斷這些數字當中哪些是要畫空格的
        if i in place[0:3]:
            print("( ",end="")
        elif i in place[3:6]:
            print(" ",end="")
        else:
            print(" )",end="\n")
