### ISSUE TITLE
[General] jupyter 無法Run

### ISSUE THREAD

**Issue by 40743203S** [coding-coworking-club/basic-python-fall-2021#76]
## 程式碼

```python

```

## 問題描述

我的jupyter偶爾會有無法執行code的情況，按下run他會直接跳到下一個執行方塊，而不執行程式，重開新的jupyter後就可以執行同樣的程式，故應非程式問題，想請問助教這種情況是我誤按什麼鍵了嗎，希望我能及早發現問題癥結，謝謝助教

**Comment by hchbiggrass** [comment]
依我自己使用Jupyter notebook的經驗，這東西本身很穩定。我根據經驗來回答，不一定能回答到你的狀況。

狀況一：在In右邊的[ ]裡面如果變成「*」，表示這一個cell正在執行。
1. 如果這時候無法輸入東西的話表示他當了。我發現新手剛開始學的時候比較容易遇到這種狀況，可能跟不同cell用到相同名稱的變數有關，要避免這種狀況發生就是練習的時候，變數名稱盡量不要重複，還有只要執行要跑的那一個cell就好，不要沒事就run all cell。
2. 如果你有寫while迴圈，表示他進到無窮迴圈。至少初期寫程式不會有需要跑那麼久的狀況。以後有要寫跑比較久的程式可以加個tqdm(進度條)，可以看出來他是死了還是在忙。

解決方法: 只要restart kernel就可以解決。步驟如下:
在上面File Edit那一列找到kernel
kernel → restart → 確定
直接按Run右邊那個轉圈的按鈕也行

狀況二：輸出東西沒有寫print
要print東西盡量都寫個print()，雖然可以像下面那樣寫也能輸出，但這種作法只能輸出最後一個東西，要輸出多個東西就不適合
a = 1
a #可以輸出a

a = 1
b = 2
a #不會輸出a
b #可以輸出b

解決方法: 要輸出的所有東西都用print()

**Comment by 40743203S** [comment]
謝謝助教這麼詳細回覆，太感謝了！！！！
