### ISSUE TITLE
[Week 3] 乘積最大值

### ISSUE THREAD

**Issue by sihci47** [coding-coworking-club/basic-python-fall-2021#77]
## 提交連結

https://judge.ccclub.io/status?myself=1#:~:text=00%3A32%3A43-,827d5e970acd,-Runtime%20Error
## 程式碼

```python
def max_mul():
    for i in range(len(a)):
        if i<int(len(a))-1:
            a[i]=a[i]*a[i+1]
    return max(a)
a=[int(num) for num in input().split()]
print(max_mul(a))
```

## 問題描述

在jupyter上試過很多資料都可以，但在judge 上就出現 runtime error ，想知道哪裡錯了

**Comment by siddwang827** [comment]
分類跟連結提供的資訊都有錯誤，
連結請提供submission裡面你錯誤那條的ID連結~

**Comment by sihci47** [comment]
好的
那我再重新開一個~
