### ISSUE TITLE
[Homework 1] 直角三角形

### ISSUE THREAD

**Issue by girl4412** [coding-coworking-club/basic-python-fall-2021#78]
## 提交連結

https://judge.ccclub.io/status/219c0458836219a66a5aa9cb26bf5c81

## 程式碼

```python
c = input()
yz = sorted(input().split(), reverse = True)
y = int(yz[0])
z = int(yz[1])

result = False

for i in range(y, z+1):
    for j in range(y, z+1):
        if int(c)**2 == int(i)**2 + int(j)**2:
            result = True
print(result)
```

## 問題描述

首先，先讓使用者第一行輸入一個整數c，第二行輸入整數 y, z 並由小到大排列。
【問題1】reverse = True 我查找資料是由大到小排列，但我放在這裡出現的結果卻是由小到大排列，因此還是先留著。若拿掉反而在jupyter中跑出錯誤結果（能跑出true or false，但非正確答案）。不知道是什麼原因造成的？

先設定 result 為 False
再來設定兩個變數分別都代入整數 y 到 z+1，如果c**2 = i**2 + j**2，則 result = True，若無，回傳原設定的 False。

【問題2】在jupyter中代入題目的範例（13, 5, 12 和 3, 5 ,7），皆顯示正確答案。但在judge顯示 wrong answer.

再請助教解惑了～謝謝！

**Comment by huaitzu** [comment]
@girl4412 你的第二行 `yz = sorted(input().split(), reverse = True)` 是用字串的形式在排序而非數字喔！建議你先把第二行輸入的內容轉成整數型態再進行排序並把 `reverse = True` 拿掉，就可以由小排到大了。基本上那邊改好應該就會 AC 了～

**Comment by girl4412** [comment]
好的！我再試試看，謝謝助教！
