### ISSUE TITLE
[General] 181103_字串加密 II

### ISSUE THREAD

**Issue by LiYiJie321** [coding-coworking-club/basic-python-fall-2021#79]
## 提交連結

https://judge.ccclub.io/status/c52d72f413f02acd4e91f64899f09bae

## 程式碼

```
def str_code(code) :
    str_list = list()
    number_list = list()
    if len(str_list) == len(number_list) :
        return True
    elif len(str_list) < len(number_list) :
        number_list = number_list[0:len(str_list)]
        return True
    else :
        return False

str_list = list(input())
number_list = [int(num) for num in input().split()]
if str_code(code) == True :
    for i in range(len(str_list)) : 
        for j in range(len(number_list)) :
            str_list_ord = ord(str(str_list[i]))
            code = str_list_ord + number_list[j]
        print(chr(code), end="")

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/91873933/137068283-2014996b-b599-445d-9b4b-55a9f28c0de3.png)

## 問題描述

想請問不知道是哪個環節出錯，跑出來的結果跟預想的不同，是奇怪的符號?

**Comment by hchbiggrass** [comment]
你的code沒有定義，你重開程式之後應該就會發現了。如果不清楚程式運作中有什麼問題，可以多利用[trace code](https://pythontutor.com/visualize.html#mode=edit)來檢查。

**Comment by LiYiJie321** [comment]
![image](https://user-images.githubusercontent.com/91873933/137262577-de52a15a-f7ce-433a-906a-4468c5f72fbc.png)


我修正後跑出來是正確的，但是放到 judge 還是 WA，想請問不知道是哪裡出錯?

**Comment by hchbiggrass** [comment]
可以麻煩提供新提交的連結嗎? 這樣看比較快

**Comment by LiYiJie321** [comment]
> 可以麻煩提供新提交的連結嗎? 這樣看比較快

https://judge.ccclub.io/status/d380bc78d0f8d216b802cd0abb5a348a

好的，不好意思，謝謝您！

**Comment by hchbiggrass** [comment]
第22行，為什麼 j == 1時要特別抓 number_list[0] 呢?

**Comment by LiYiJie321** [comment]
> 第22行，為什麼 j == 1時要特別抓 number_list[0] 呢?

對欸!! 那時候想說只要加上index等於0的數字。
刪掉之後有成功了。
謝謝！
