### ISSUE TITLE
[General] 8-3：及格門檻

### ISSUE THREAD

**Issue by dennisc1213** [coding-coworking-club/basic-python-fall-2021#8]
## 提交連結

https://judge.ccclub.io/status/4cd6626f605d0e52ce60f1f4d319b57e

## 程式碼

```python
def threshold(l,t):
    l = str.split(l)
    quantity = len(l)
    result = []
    for i in range(quantity):
        '''if l[i] >= t:
            result.append(True)
        else:
            result.append(False)
            '''
        result.append(bool(l[i]>=t))

    print(result)
    
l = input()
t = input()
threshold(l,t)
```

## 錯誤訊息

<img width="619" alt="Screen Shot 2021-09-29 at 2 50 39 PM" src="https://user-images.githubusercontent.com/89033441/135217571-5cba4c0e-10d5-4836-8445-fe717593c952.png">

## 問題描述

在Jupiter or Thonny上跑出的結果看來都是符合預期的，但在Judge上都是Wrong Answer

**Comment by hinihow** [comment]
split完的list裡面為string
所以後面比大小的時候會去比string的大小而不是int的大小
要事先將string轉成int再比大小才會是正確的

string比大小只會看第一位字元的ascii碼誰大，所以 "5" 會比 "10" 大就會出錯(因為5的ascii比1大)

**Comment by dennisc1213** [comment]
> split完的list裡面為string 所以後面比大小的時候會去比string的大小而不是int的大小 要事先將string轉成int再比大小才會是正確的
> 
> string比大小只會看第一位字元的ascii碼誰大，所以 "5" 會比 "10" 大就會出錯(因為5的ascii比1大)

感謝！
改成這樣就過了！

`        
result.append(bool(int(l[i])>= int(t)))

`
