### ISSUE TITLE
[General] 8-4最大公因數

### ISSUE THREAD

**Issue by JumpingBoar** [coding-coworking-club/basic-python-fall-2021#80]
## 提交連結

https://judge.ccclub.io/status/477e8dd42ef36ce1fa7417f755bf871e
## 程式碼

def gcd():
    l1 = input().split(" ")
    l2 = input().split(" ")
    int_list1 = list(map(int, l1))
    int_list2 = list(map(int, l2))
    l = len(int_list1)

    big_ans_list = []
    for i in range(l):
        if int_list1[i] > int_list2[i] :
            bigger_num = int_list1[i]
            smaller_num = int_list2[i]
        else:
            bigger_num = int_list2[i]
            smaller_num = int_list1[i]
        ans_list = []
        for j in range(smaller_num,1,-1):
            if bigger_num % j == 0 and smaller_num % j == 0:
                ans = j
                ans_list.append(ans)
                m = max(ans_list)
        big_ans_list.append(m)
    print(big_ans_list)

gcd()

```python

```

## 錯誤訊息

runtime error
## 問題描述

notebook上面測試沒問題，但judge就是runtime error
想請問是哪個細節出問題了呢？

**Comment by hchbiggrass** [comment]
在 smaller_num 等於 2 而且下面一行的 if 不成立的時候，m會沒有定義，所以runtime error
