### ISSUE TITLE
[General] 8-1 乘積最大值

### ISSUE THREAD

**Issue by ting8931** [coding-coworking-club/basic-python-fall-2021#82]
## 程式碼

```python
def max_mul(s):
    for i in range(1,len(s)):
        max_s=[int(s[i-1])*int(s[i])]
        max_s.sort(reverse=True)
    return(max_s[0])

n=[int(i) for i in input().split(' ')]
print(max_mul(n))
```

## 問題描述

測試時只會算出最後兩個數值的乘積，請問要怎麼用遞減的方式選出最大值呢？

**Comment by hchbiggrass** [comment]
麻煩補充提交的連結(長得像是 https://judge.ccclub.io/status/一堆由英文和數字組成的亂碼 )，這樣助教會看比較快

**Comment by ting8931** [comment]
我最後在Judge上用別的寫法已經成功解決，只是想知道這個解法而已，所以沒有連結可以提供

**Comment by hchbiggrass** [comment]
只有一個問題。max_s是一個串列，但每次做完 max_s=[int(s[i-1])*int(s[i])] 之後數值就直接蓋掉前面的計算結果，要用append。如果不清楚程式在幹嘛，請多利用[trace code](https://pythontutor.com/visualize.html#mode=edit)

**Comment by ting8931** [comment]
剛剛測試就成功了！謝謝你
