### ISSUE TITLE
[Homework 1] 直角三角形

### ISSUE THREAD

**Issue by linyuzz** [coding-coworking-club/basic-python-fall-2021#83]
## 提交連結

https://judge.ccclub.io/status/14cb8b01a9573b061fefacf65ce9eb12

## 程式碼

```python

#直角三角形

x = int(input()) #轉為整數
yz = [int(x) for x in input().split(',')] #轉為整數串列
yz.sort() #先排序
ANS = 'False'
for a in range(yz[0],yz[1]+1):   #檢查
    for b in range(yz[0],yz[1]+1):   #檢查
        if a**2 + b**2 == x**2:
            ANS = 'True'
            break
print(ANS)

```

## 錯誤訊息

<img width="247" alt="截圖 2021-10-13 下午11 33 14" src="https://user-images.githubusercontent.com/91477748/137166077-60457eda-909f-4d89-83cd-c6017e77373a.png">

## 問題描述

在jupyter 裡面打了數個測資都是對的，且有跑出結果，改寫了蠻多次，但不知道為什麼還是出現runtime error

**Comment by siddwang827** [comment]
你的分隔符號跟input不相符哦，題目是空格~
