### ISSUE TITLE
[General] 8-4：最大公因數

### ISSUE THREAD

**Issue by yuting85919s** [coding-coworking-club/basic-python-fall-2021#86]
## 提交連結
https://judge.ccclub.io/status/5a188ea964152620802ab11b7c853e30

## 程式碼

```
def gcd(lst1,lst2):

    big=[]
    small=[]
    hcf=[] #highest common factor最大公因數

    for k in range(len(lst1)):
        if lst1[k] > lst2[k]:
            big.append(lst1[k])
            small.append(lst2[k])
        elif lst1[k] < lst2[k]:
            big.append(lst2[k])
            small.append(lst1[k])

        for j in range(small[k],0,-1):
            if big[k]%j==0 and small[k]%j==0:
                hcf.append(j)
                break
    return(hcf)

lst1=[int(num) for num in input().split()]
lst2=[int(num) for num in input().split()]
print(gcd(lst1,lst2))

```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/34641533/137245132-ee8c68cb-11ed-4403-a454-f795de73e354.png)

## 問題描述

1.在jupyter上judge提供的測資通過之外，也有考慮到質數的可能，自己用(11 13 17) (2 4 6)測試過，是可以print出[1,1,1]。
2.有看到#80別人提的問題，寫法相近，但應該是沒有該回覆中提到的狀況。因為我的`for j in range(small[k],0,-1)`，`range`有到0，所以最大公因數為1的可能也有考慮進去。
3.果然自己還是有了很多盲點，先謝謝助教和各位同學大大的指導！

**Comment by yuting85919s** [comment]
(補充一下，我有把`return(hcf)`的括弧去掉了>> `return hcf`，不過這是不影響runtime error結果

**Comment by hchbiggrass** [comment]
如果lst1[k] == lst2[k]的話會發生什麼事呢?

**Comment by yuting85919s** [comment]
> 如果lst1[k] == lst2[k]的話會發生什麼事呢?

謝謝助教！加上去就過了！
