### ISSUE TITLE
[General] 7-2：加減長方形

### ISSUE THREAD

**Issue by linachentw1993** [coding-coworking-club/basic-python-fall-2021#87]
## 提交連結

https://judge.ccclub.io/problem/180019 

## 程式碼

```python
l = int(input())
w = int(input())

for i in range(w):
    for j in range(l):
        if i % 2 == 0:
            if j % 2 == 0:
                print("+", end="")
            else:
                print("-", end="")
        else:
            if j % 2 == 0:
                print("-", end="")
            else:
                print("+", end="")
    print()
```
## 錯誤訊息

Wrong Answer

## 問題描述

在Udemy是正確的、在Jupyter跑出來的out put 也是對的，不確定是哪邊出問題
有發現Judge上的Sample Input 2 的output 樣子跟Udemy上面的outout 長不一樣
![243088660_393733025805650_527441917949258634_n](https://user-images.githubusercontent.com/73411599/137249796-70058444-8a1a-43b6-ba2a-2e9c8e140ac8.png)
![245225478_576508147109233_5128417448524699995_n](https://user-images.githubusercontent.com/73411599/137249814-970d167f-fd23-4eb9-b804-463cb6da9649.png)

**Comment by siddwang827** [comment]
題意中的交錯使用+,-符號不單只單行內哦，可以仔細觀察一下，
換行的頭尾也需要交錯使用~
