### ISSUE TITLE
[Week 4] 字母拼圖

### ISSUE THREAD

**Issue by 40743203S** [coding-coworking-club/basic-python-fall-2021#90]
## 提交連結

https://judge.ccclub.io/status/398e06a9ed94ac43379c75977df740f6

## 程式碼

```python
def char_puzzle(lst):
    lst = "".join(lst)   # list變相連的字串
    lst = sorted(lst)    # 排序，型態變成list
    letter = 1      
    while letter < len(lst):    # 因為要remove所以用while迴圈
        if lst[letter] == lst[letter-1]:    # 從index等於1開始，當字母與前一個子母相同時去掉
            lst.remove(lst[letter])           
        else:
            letter += 1
    return "".join(lst)         # 輸出字串
```

## 錯誤訊息

![image](https://user-images.githubusercontent.com/91603602/137351806-dd37e49f-2663-4da7-90b4-8ce1d3e5e1c5.png)

## 問題描述

顯示Time Limit Exceeded，是代表方法太low了嗎，jupyter可印出範例的答案，請問助教我有什麼地方可以修改或是應該要換另一種解法比較好呢

**Comment by lazyYC** [comment]
@40743203S 
這個方法在input非常長的時候會太慢的原因，我想應該是因為在while內部用到remove的關係，
有點難快速解釋XD 有興趣的話可以去google "time complexity python"
比較理想的做法是：
定義一個空字串，比對lst中每個字，空字串沒有的字才加進空字串。

**Comment by 40743203S** [comment]
了解~謝謝助教
