### ISSUE TITLE
[Homework 4] 直線等加速度 

### ISSUE THREAD

**Issue by Roy19890616** [coding-coworking-club/basic-python-fall-2021#95]
## 程式碼

l = input().split(',')
ans = {}
if l[0] == '' and l[1] == '':
    ans['s'] = float(l[2])
    ans['t'] = float(l[3])
    ans['a'] = (ans['s']-ans['t'])*2/(ans['t']**2)
    ans['v'] = (1 + 2*ans['a']*ans['s'])**0.5
elif l[0] == '' and l[2] =='':
    ans['a'] = float(l[1])
    ans['t'] = float(l[3])
    ans['v'] = 1 + ans['a'] * ans['t']
    ans['s'] = ans['t'] + 0.5*ans['a']*ans['t']*ans['t']
elif l[0] == '' and l[3] =='':
    ans['a'] = float(l[1])
    ans['s'] = float(l[2])
    ans['v'] = (1 + 2*ans['a']*ans['s'])**0.5
    ans['t'] = (ans['v'] - 1) / ans['a']
elif l[1] == '' and l[2] =='':
    ans['v'] = float(l[0])
    ans['t'] = float(l[3])
    ans['a'] = (ans['v'] - 1) / ans['t']
    ans['s'] = ans['t'] + 0.5*ans['a']*ans['t']*ans['t']
elif l[1] == '' and l[3] =='':
    ans['v'] = float(l[0])
    ans['s'] = float(l[2])
    ans['a'] = (ans['v'] ** 2 - 1) / (2*ans['s'])
    ans['t'] = (ans['v'] - 1) / ans['a']
elif l[2] == '' and l[3] =='':
    ans['v'] = float(l[0])
    ans['a'] = float(l[1])
    ans['s'] = (ans['v'] ** 2 - 1) / (2*ans['a'])
    ans['t'] = (ans['v'] - 1) / ans['a']
elif l[0] == '':
    ans['s'] = float(l[2])
    ans['t'] = float(l[3])
    ans['a'] = (ans['s']-ans['t'])*2/(ans['t']**2)
    ans['v'] = (1 + 2*ans['a']*ans['s'])**0.5
elif l[1] == '':    
    ans['v'] = float(l[0])
    ans['t'] = float(l[3])
    ans['a'] = (ans['v'] - 1) / ans['t']
    ans['s'] = ans['t'] + 0.5*ans['a']*ans['t']*ans['t']
elif l[2] == '':    
    ans['v'] = float(l[0])
    ans['a'] = float(l[1])
    ans['s'] = (ans['v'] ** 2 - 1) / (2*ans['a'])
    ans['t'] = (ans['v'] - 1) / ans['a']
elif l[3] == '':
    ans['v'] = float(l[0])
    ans['a'] = float(l[1])
    ans['s'] = (ans['v'] ** 2 - 1) / (2*ans['a'])
    ans['t'] = (ans['v'] - 1) / ans['a']
elif l[0] != '' and l[1] != '' and l[2] != '' and l[3] != '':
    ans['v'] = l[0]
    ans['a'] = l[1]
    ans['s'] = l[2]
    ans['t'] = l[3]

ans['v'] = str(float(ans['v']))
ans['a'] = str(float(ans['a']))
ans['t'] = str(float(ans['t']))
ans['s'] = str(float(ans['s']))
print('v=' + ans['v'] + ', v0=1.0, '+'a=' + ans['a'] + ', S=' + ans['s'] + ', t=' + ans['t'])

## 錯誤訊息

![image](https://user-images.githubusercontent.com/91719956/137497264-745789b0-b5dd-4211-96b7-520dbab7dd67.png)

## 問題描述

用了很笨的方法，在jupyter上測試OK，
但丟進ccClub Judge顯示Runtime Error，再麻煩大大解惑

**Comment by jasonchen1125** [comment]
題目給的數字可能造成公式 **分母是0** 的狀況而失效
可以思考看看該如何排除這樣的狀況

**提醒您**
請注意發文程式碼 **縮排問題** 與 **提交連結**，且 **乘號** 都不見了
發文格式與注意事項請詳閱 [GitHub使用須知](https://www.notion.so/ccclub/GitHub-Issue-5a270fb3e09448e1a6012082d10eb3dc)
有助於我們更快發現哪邊出錯哦
