### ISSUE TITLE
[Homework 2] 色碼轉換

### ISSUE THREAD

**Issue by JumpingBoar** [coding-coworking-club/basic-python-fall-2021#96]
## 提交連結

https://judge.ccclub.io/status/69a0f80719eeb8ff6f4ee7f30699fbc3

## 程式碼

num = input().split(" ")
num_list = list(map(float, num))
point_num_list = []
for num in num_list :
    if num >= 255:
        point_num_list.append(255)
    elif num <= 0 :
        point_num_list.append(0)
    else:
        point_num_list.append(int(num))

hex_num_list = [] 
for i in point_num_list :
    hex_num = hex(i)
    hex_num_list.append(hex_num)
new_hex_num_list = "".join(hex_num_list).replace("0x"," ").split(" ")
hex_list = []
for j in new_hex_num_list[1:] :
    if len(j) == 1:
        j = j +"0"
    hex_list.append(j)
ans = ''.join(hex_list)

print("0x"+ ans)

```python

```

## 錯誤訊息

wrong answer

## 問題描述

我在notebook上面測試沒有問題，但judge不給過，希望助教可以給點提示，是程式碼有誤?還是題目敘述哪裏我沒注意到。
謝謝。

**Comment by jasonchen1125** [comment]
若長度只有1的話要注意0是補在前面或後面呢？ `j = j +"0"` 這樣是補在後面哦
若你跑第二個input會發現0的位子不對，正確應為 **0x000b38** ，但你目前的程式碼結果為 **0x00b038**
修正完這個問題就可以拿到AC摟~

**Comment by JumpingBoar** [comment]
我懂了，感謝提醒！
