### ISSUE TITLE
[Week 4] 打字機

### ISSUE THREAD

**Issue by YFK2120** [coding-coworking-club/basic-python-fall-2021#98]
## 提交連結
https://judge.ccclub.io/contest/63/problem/03

## 程式碼
s = input()
a = list()
n = len(s)
if s[0] == '+':  #針對字串的第一個字做處理
    a = a
else:
    a.append(s[0])
          
for i in range(1,n): #從字串的第二個字開始
    if s[i] == '+':
        a.append(a[-1]) 
    elif s[i] == '-':
        a = a.pop()
    elif s[i] == '*':
        a.append(s[:i])
    else:
        a.append(s[i])
      
a = ''.join(a)
print(a)

```python

```

## 錯誤訊息
![image](https://user-images.githubusercontent.com/73774348/137506325-3a6201f0-a797-4555-9c62-f87ea87cd0b3.png)

## 問題描述
將程式碼放在 https://pythontutor.com/visualize.html#mode=edit 及 google colab 上均能執行，但在 judge 中則是出現錯誤訊息。謝謝
(程式碼貼上後，preview的縮排就不見了。)

**Comment by lazyYC** [comment]
@YFK2120 
提交的連結應該是圈起來那邊的連結喔
![image](https://user-images.githubusercontent.com/71726501/137563555-90937b21-5d20-4d01-b602-033d1cca5b21.png)
不過好在你還是有提供code的截圖～

以下兩個小建議：
1. 第5行實際上可以直接寫`pass`就好了，既然沒有要更動任何變數的話
2. `list.pop()`滿容易用錯的，要得到你想要的效果不需再把它assign回去，因為只要執行`list.pop()`就會改動list本身，而它`return`的值是被刪除的那個元素，所以你的a會變成剩下被刪掉那個字

我不確定這樣講夠不夠好理解，不太懂再跟我說XD

**Comment by YFK2120** [comment]
https://judge.ccclub.io/status/96c989b9f26c7886b47980675b31fa46

程試碼修改後如下(有參考其他學員的問題，考量到'C+--+'的狀況)，但仍是WA，請問該如何修改? 謝謝
s = input()
a = list()
n = len(s)
if s[0] == '+':
    pass
else:
    a.append(s[0])  
for i in range(1,n):
    if s[i] == '+':
        if a != []:
            a.append(a[-1]) 
        else:
            pass
    elif s[i] == '-':
        a.pop()
    elif s[i] == '*':
        a.append(s[:i])
    else:
        a.append(s[i])
      
a = ''.join(a)
print(a)
![image](https://user-images.githubusercontent.com/73774348/137609980-779ced31-8cb8-43e3-b1ab-cc8c646d5913.png)

**Comment by r05521230** [comment]
請再確認 * 號出現時的狀況喔，可以想幾個有 * 的例子試試看
